# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  optkit_dynamic_config = debug
  optkit_static_config = debug
  optkit_py_config = debug
  optkit_c_config = debug
  optkit_test_config = debug

else ifeq ($(config),release)
  optkit_dynamic_config = release
  optkit_static_config = release
  optkit_py_config = release
  optkit_c_config = release
  optkit_test_config = release

else ifeq ($(config),test)
  optkit_dynamic_config = test
  optkit_static_config = test
  optkit_py_config = test
  optkit_c_config = test
  optkit_test_config = test

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := optkit_dynamic optkit_static optkit_py optkit_c optkit_test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

optkit_dynamic:
ifneq (,$(optkit_dynamic_config))
	@echo "==== Building optkit_dynamic ($(optkit_dynamic_config)) ===="
	@${MAKE} --no-print-directory -C . -f optkit_dynamic.make config=$(optkit_dynamic_config)
endif

optkit_static:
ifneq (,$(optkit_static_config))
	@echo "==== Building optkit_static ($(optkit_static_config)) ===="
	@${MAKE} --no-print-directory -C . -f optkit_static.make config=$(optkit_static_config)
endif

optkit_py: optkit_dynamic
ifneq (,$(optkit_py_config))
	@echo "==== Building optkit_py ($(optkit_py_config)) ===="
	@${MAKE} --no-print-directory -C . -f optkit_py.make config=$(optkit_py_config)
endif

optkit_c: optkit_dynamic
ifneq (,$(optkit_c_config))
	@echo "==== Building optkit_c ($(optkit_c_config)) ===="
	@${MAKE} --no-print-directory -C . -f optkit_c.make config=$(optkit_c_config)
endif

optkit_test:
ifneq (,$(optkit_test_config))
	@echo "==== Building optkit_test ($(optkit_test_config)) ===="
	@${MAKE} --no-print-directory -C . -f optkit_test.make config=$(optkit_test_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f optkit_dynamic.make clean
	@${MAKE} --no-print-directory -C . -f optkit_static.make clean
	@${MAKE} --no-print-directory -C . -f optkit_py.make clean
	@${MAKE} --no-print-directory -C . -f optkit_c.make clean
	@${MAKE} --no-print-directory -C . -f optkit_test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  test"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   optkit_dynamic"
	@echo "   optkit_static"
	@echo "   optkit_py"
	@echo "   optkit_c"
	@echo "   optkit_test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"