# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -Isrc -Ilib/libpfm4/include -Ilib/spdlog/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS += -lpthread -ldl
LDDEPS +=
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
	@echo Running prebuild commands
	@if [ ! -f "./lib/spdlog/build/libspdlog.a" ]; then cd ./lib/spdlog && ./compile.sh; fi && echo [✅ COMPILE SPDLOG] || echo [❌ COMPILE SPDLOG ERROR]
	@if [ ! -f "./lib/libpfm4/lib/libpfm.a" ]; then cd ./lib/libpfm4 && ./compile.sh; fi && echo [✅ COMPILE LIBPFM] || echo [❌ COMPILE LIBPFM ERROR]
	@if [ ! -f ./src/core/pmu/cpu/perf/events/all_set ]; then \
	    echo "⛏️ Exporting events from libpfm4" && \
	    mkdir -p ./src/core/pmu/cpu/perf/events && \
	    cd ./src/utils && \
	    python3 pmu_parser.py $(shell find ./lib/libpfm4/lib/events -type f \( -name "intel*.h" -or -name "amd*.h" -or -name "arm*.h" -or -name "power*.h" \) -exec echo "../../{}" \;) && \
	    touch ../.././src/core/pmu/cpu/perf/events/all_set;\
	fi && \
	echo [✅ CHECK EVENTS] || echo [❌ CHECK EVENTS ERROR]
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/optkit_app
OBJDIR = bin/obj/Debug/optkit_app
DEFINES += -DOPTKIT_MODE_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g -Wall -O0 -g -fopenmp -fPIC -msse -march=native -DCONF_LOG_PRINT_GUID_LENGTH=5 -DCONF_LOG_DISABLE_DEBUG=0 -DCONF_LOG_DISABLE_TRACE=0 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g -std=c++11 -Wall -O0 -g -fopenmp -fPIC -msse -march=native -DCONF_LOG_PRINT_GUID_LENGTH=5 -DCONF_LOG_DISABLE_DEBUG=0 -DCONF_LOG_DISABLE_TRACE=0 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0
ALL_LDFLAGS += $(LDFLAGS) -fopenmp ./lib/spdlog/build/libspdlog.a ./lib/libpfm4/lib/libpfm.a

else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/optkit_app
OBJDIR = bin/obj/Release/optkit_app
DEFINES += -DOPTKIT_MODE_NDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -O2 -fopenmp -fPIC -msse -march=native -DCONF_LOG_PRINT_GUID_LENGTH=5 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -std=c++11 -Wall -O2 -fopenmp -fPIC -msse -march=native -DCONF_LOG_PRINT_GUID_LENGTH=5 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0
ALL_LDFLAGS += $(LDFLAGS) -s -fopenmp ./lib/spdlog/build/libspdlog.a ./lib/libpfm4/lib/libpfm.a

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/bdw_recepies.o
GENERATED += $(OBJDIR)/block_group_profiler.o
GENERATED += $(OBJDIR)/block_profiler.o
GENERATED += $(OBJDIR)/cpu_frequency.o
GENERATED += $(OBJDIR)/icl_recepies.o
GENERATED += $(OBJDIR)/libpfm4_wrapper.o
GENERATED += $(OBJDIR)/logger.o
GENERATED += $(OBJDIR)/main.o
GENERATED += $(OBJDIR)/optkit.o
GENERATED += $(OBJDIR)/pmu_event_manager.o
GENERATED += $(OBJDIR)/pmu_utils.o
GENERATED += $(OBJDIR)/profiler_config.o
GENERATED += $(OBJDIR)/profiler_config1.o
GENERATED += $(OBJDIR)/query.o
GENERATED += $(OBJDIR)/query_cpu_frequency.o
GENERATED += $(OBJDIR)/query_pmu.o
GENERATED += $(OBJDIR)/query_rapl.o
GENERATED += $(OBJDIR)/rapl.o
GENERATED += $(OBJDIR)/rapl_perf_reader.o
GENERATED += $(OBJDIR)/rapl_profiler.o
GENERATED += $(OBJDIR)/rapl_utils.o
GENERATED += $(OBJDIR)/skl_recepies.o
GENERATED += $(OBJDIR)/tma_metrics.o
GENERATED += $(OBJDIR)/tmanalysis.o
GENERATED += $(OBJDIR)/utils.o
GENERATED += $(OBJDIR)/zen3_recepies.o
OBJECTS += $(OBJDIR)/bdw_recepies.o
OBJECTS += $(OBJDIR)/block_group_profiler.o
OBJECTS += $(OBJDIR)/block_profiler.o
OBJECTS += $(OBJDIR)/cpu_frequency.o
OBJECTS += $(OBJDIR)/icl_recepies.o
OBJECTS += $(OBJDIR)/libpfm4_wrapper.o
OBJECTS += $(OBJDIR)/logger.o
OBJECTS += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/optkit.o
OBJECTS += $(OBJDIR)/pmu_event_manager.o
OBJECTS += $(OBJDIR)/pmu_utils.o
OBJECTS += $(OBJDIR)/profiler_config.o
OBJECTS += $(OBJDIR)/profiler_config1.o
OBJECTS += $(OBJDIR)/query.o
OBJECTS += $(OBJDIR)/query_cpu_frequency.o
OBJECTS += $(OBJDIR)/query_pmu.o
OBJECTS += $(OBJDIR)/query_rapl.o
OBJECTS += $(OBJDIR)/rapl.o
OBJECTS += $(OBJDIR)/rapl_perf_reader.o
OBJECTS += $(OBJDIR)/rapl_profiler.o
OBJECTS += $(OBJDIR)/rapl_utils.o
OBJECTS += $(OBJDIR)/skl_recepies.o
OBJECTS += $(OBJDIR)/tma_metrics.o
OBJECTS += $(OBJDIR)/tmanalysis.o
OBJECTS += $(OBJDIR)/utils.o
OBJECTS += $(OBJDIR)/zen3_recepies.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking optkit_app
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning optkit_app
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/profiler_config.o: src/core/energy/cpu/rapl/profiler_config.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query_rapl.o: src/core/energy/cpu/rapl/query_rapl.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rapl.o: src/core/energy/cpu/rapl/rapl.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rapl_perf_reader.o: src/core/energy/cpu/rapl/rapl_perf_reader.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rapl_profiler.o: src/core/energy/cpu/rapl/rapl_profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rapl_utils.o: src/core/energy/cpu/rapl/rapl_utils.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cpu_frequency.o: src/core/frequency/cpu/cpu_frequency.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query_cpu_frequency.o: src/core/frequency/cpu/query_cpu_frequency.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zen3_recepies.o: src/core/metrics/cpu/amd/zen3/zen3_recepies.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/bdw_recepies.o: src/core/metrics/cpu/intel/bdw/bdw_recepies.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/icl_recepies.o: src/core/metrics/cpu/intel/icl/icl_recepies.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/skl_recepies.o: src/core/metrics/cpu/intel/skl/skl_recepies.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/tma_metrics.o: src/core/metrics/tma_metrics.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/tmanalysis.o: src/core/metrics/tmanalysis.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/block_group_profiler.o: src/core/pmu/cpu/perf/block_group_profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/block_profiler.o: src/core/pmu/cpu/perf/block_profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/libpfm4_wrapper.o: src/core/pmu/cpu/perf/libpfm4_wrapper.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pmu_event_manager.o: src/core/pmu/cpu/perf/pmu_event_manager.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pmu_utils.o: src/core/pmu/cpu/perf/pmu_utils.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/profiler_config1.o: src/core/pmu/cpu/perf/profiler_config.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query_pmu.o: src/core/pmu/cpu/perf/query_pmu.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query.o: src/core/query.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main.o: src/main.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/optkit.o: src/optkit.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/logger.o: src/utils/logging/logger.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utils.o: src/utils/utils.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif