# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug)
  RESCOMP = windres
  TARGETDIR = bin/Debug
  TARGET = $(TARGETDIR)/liboptkit_dynamic.so
  OBJDIR = bin/obj/Debug/optkit_dynamic
  DEFINES += -DOPTKIT_MODE_DEBUG
  INCLUDES += -Isrc -Ilib/libpfm4/include -Ilib/spdlog/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -fPIC -g -Wall -O0 -g -fopenmp -fPIC -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=0 -DCONF_LOG_DISABLE_TRACE=0 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -fPIC -g -std=c++11 -Wall -O0 -g -fopenmp -fPIC -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=0 -DCONF_LOG_DISABLE_TRACE=0 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -lpthread -ldl -lpfm
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -Llib/libpfm4/lib -shared -Wl,-soname=liboptkit_dynamic.so -fopenmp ./lib/spdlog/build/libspdlog.a
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release)
  RESCOMP = windres
  TARGETDIR = bin/Release
  TARGET = $(TARGETDIR)/liboptkit_dynamic.so
  OBJDIR = bin/obj/Release/optkit_dynamic
  DEFINES += -DOPTKIT_MODE_NDEBUG
  INCLUDES += -Isrc -Ilib/libpfm4/include -Ilib/spdlog/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -Wall -O2 -fopenmp -fPIC -march=native -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -msse
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -std=c++11 -Wall -O2 -fopenmp -fPIC -march=native -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -msse
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -lpthread -ldl -lpfm
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -Llib/libpfm4/lib -shared -Wl,-soname=liboptkit_dynamic.so -s -fopenmp ./lib/spdlog/build/libspdlog.a
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),test)
  RESCOMP = windres
  TARGETDIR = bin/Test
  TARGET = $(TARGETDIR)/liboptkit_dynamic.so
  OBJDIR = bin/obj/Test/optkit_dynamic
  DEFINES += -DOPTKIT_MODE_NDEBUG
  INCLUDES += -Isrc -Ilib/libpfm4/include -Ilib/spdlog/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -Wall -O2 -fopenmp -fPIC -march=native -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -DOPTKIT_TESTING=1 -msse
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -std=c++11 -Wall -O2 -fopenmp -fPIC -march=native -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -DOPTKIT_TESTING=1 -msse
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -lpthread -ldl -lpfm
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -Llib/libpfm4/lib -shared -Wl,-soname=liboptkit_dynamic.so -s -fopenmp ./lib/spdlog/build/libspdlog.a
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/disk_profiler.o \
	$(OBJDIR)/profiler_config.o \
	$(OBJDIR)/query_rapl.o \
	$(OBJDIR)/rapl.o \
	$(OBJDIR)/rapl_perf_reader.o \
	$(OBJDIR)/rapl_profiler.o \
	$(OBJDIR)/rapl_utils.o \
	$(OBJDIR)/cpu_frequency.o \
	$(OBJDIR)/query_cpu_frequency.o \
	$(OBJDIR)/event_mapper.o \
	$(OBJDIR)/native_events.o \
	$(OBJDIR)/event_mapper1.o \
	$(OBJDIR)/native_events1.o \
	$(OBJDIR)/core_events.o \
	$(OBJDIR)/bdw_recepies.o \
	$(OBJDIR)/event_mapper2.o \
	$(OBJDIR)/icl_recepies.o \
	$(OBJDIR)/native_events2.o \
	$(OBJDIR)/skl_recepies.o \
	$(OBJDIR)/core_events1.o \
	$(OBJDIR)/libpfm4_wrapper.o \
	$(OBJDIR)/block_group_profiler.o \
	$(OBJDIR)/block_profiler.o \
	$(OBJDIR)/profiler_config1.o \
	$(OBJDIR)/block_group_profiler1.o \
	$(OBJDIR)/block_profiler1.o \
	$(OBJDIR)/profiler_config2.o \
	$(OBJDIR)/pmu_event_manager.o \
	$(OBJDIR)/query_pmu.o \
	$(OBJDIR)/query.o \
	$(OBJDIR)/instructions.o \
	$(OBJDIR)/optkit.o \
	$(OBJDIR)/logger.o \
	$(OBJDIR)/metric_builder.o \
	$(OBJDIR)/utils.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking optkit_dynamic
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning optkit_dynamic
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/disk_profiler.o: src/core/disk/disk_profiler.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/profiler_config.o: src/core/energy/cpu/rapl/profiler_config.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query_rapl.o: src/core/energy/cpu/rapl/query_rapl.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rapl.o: src/core/energy/cpu/rapl/rapl.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rapl_perf_reader.o: src/core/energy/cpu/rapl/rapl_perf_reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rapl_profiler.o: src/core/energy/cpu/rapl/rapl_profiler.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rapl_utils.o: src/core/energy/cpu/rapl/rapl_utils.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cpu_frequency.o: src/core/frequency/cpu/cpu_frequency.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query_cpu_frequency.o: src/core/frequency/cpu/query_cpu_frequency.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/event_mapper.o: src/core/metrics/cpu/amd/event_mapper.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/native_events.o: src/core/metrics/cpu/amd/native_events.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/event_mapper1.o: src/core/metrics/cpu/arm/event_mapper.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/native_events1.o: src/core/metrics/cpu/arm/native_events.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_events.o: src/core/metrics/cpu/core_events.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/bdw_recepies.o: src/core/metrics/cpu/intel/bdw/bdw_recepies.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/event_mapper2.o: src/core/metrics/cpu/intel/event_mapper.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/icl_recepies.o: src/core/metrics/cpu/intel/icl/icl_recepies.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/native_events2.o: src/core/metrics/cpu/intel/native_events.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/skl_recepies.o: src/core/metrics/cpu/intel/skl/skl_recepies.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_events1.o: src/core/metrics/disk/core_events.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/libpfm4_wrapper.o: src/core/pmu/cpu/libpfm4_wrapper.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/block_group_profiler.o: src/core/pmu/cpu/msr/block_group_profiler.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/block_profiler.o: src/core/pmu/cpu/msr/block_profiler.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/profiler_config1.o: src/core/pmu/cpu/msr/profiler_config.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/block_group_profiler1.o: src/core/pmu/cpu/perf/block_group_profiler.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/block_profiler1.o: src/core/pmu/cpu/perf/block_profiler.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/profiler_config2.o: src/core/pmu/cpu/perf/profiler_config.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pmu_event_manager.o: src/core/pmu/cpu/pmu_event_manager.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query_pmu.o: src/core/pmu/cpu/query_pmu.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query.o: src/core/query.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/instructions.o: src/instructions.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/optkit.o: src/optkit.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/logger.o: src/utils/logging/logger.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/metric_builder.o: src/utils/metric_builder.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utils.o: src/utils/utils.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif