# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -Isrc -Itest -Ilib/libpfm4/include -Ilib/spdlog/include -Ilib/googletest/googletest/include -Ilib/googletest/googlemock/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS += -lgtest -lgtest_main -lpthread -ldl
LDDEPS +=
ALL_LDFLAGS += $(LDFLAGS) -Llib/googletest/build/lib -s -fopenmp ./bin/Test/liboptkit_static.a
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/optkit_test
OBJDIR = bin/obj/Debug/optkit_test
DEFINES += -DOPTKIT_MODE_NDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -Wall -O0 -fopenmp -fPIC -DOPTKIT_TESTING=1
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -std=c++17 -Wall -O0 -fopenmp -fPIC -DOPTKIT_TESTING=1

else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/optkit_test
OBJDIR = bin/obj/Release/optkit_test
DEFINES +=
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS)
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -std=c++17

else ifeq ($(config),test)
TARGETDIR = bin/Test
TARGET = $(TARGETDIR)/optkit_test
OBJDIR = bin/obj/Test/optkit_test
DEFINES +=
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS)
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -std=c++17

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/block_group_profiler_test.o
GENERATED += $(OBJDIR)/block_profiler_test.o
GENERATED += $(OBJDIR)/branches.o
GENERATED += $(OBJDIR)/core_events_test.o
GENERATED += $(OBJDIR)/cpu_frequency_test.o
GENERATED += $(OBJDIR)/instructions.o
GENERATED += $(OBJDIR)/main_test.o
GENERATED += $(OBJDIR)/metric_builder_test.o
GENERATED += $(OBJDIR)/pmu_event_manager_test.o
GENERATED += $(OBJDIR)/query_cpu_frequency_test.o
GENERATED += $(OBJDIR)/query_pmu_test.o
GENERATED += $(OBJDIR)/query_rapl_test.o
GENERATED += $(OBJDIR)/query_test.o
GENERATED += $(OBJDIR)/rapl_profiler_test.o
GENERATED += $(OBJDIR)/tmanalysis_test.o
GENERATED += $(OBJDIR)/utils_test.o
OBJECTS += $(OBJDIR)/block_group_profiler_test.o
OBJECTS += $(OBJDIR)/block_profiler_test.o
OBJECTS += $(OBJDIR)/branches.o
OBJECTS += $(OBJDIR)/core_events_test.o
OBJECTS += $(OBJDIR)/cpu_frequency_test.o
OBJECTS += $(OBJDIR)/instructions.o
OBJECTS += $(OBJDIR)/main_test.o
OBJECTS += $(OBJDIR)/metric_builder_test.o
OBJECTS += $(OBJDIR)/pmu_event_manager_test.o
OBJECTS += $(OBJDIR)/query_cpu_frequency_test.o
OBJECTS += $(OBJDIR)/query_pmu_test.o
OBJECTS += $(OBJDIR)/query_rapl_test.o
OBJECTS += $(OBJDIR)/query_test.o
OBJECTS += $(OBJDIR)/rapl_profiler_test.o
OBJECTS += $(OBJDIR)/tmanalysis_test.o
OBJECTS += $(OBJDIR)/utils_test.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking optkit_test
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning optkit_test
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/branches.o: test/common/branches.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/instructions.o: test/common/instructions.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query_rapl_test.o: test/core/energy/cpu/rapl/query_rapl_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rapl_profiler_test.o: test/core/energy/cpu/rapl/rapl_profiler_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cpu_frequency_test.o: test/core/frequency/cpu/cpu_frequency_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query_cpu_frequency_test.o: test/core/frequency/cpu/query_cpu_frequency_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_events_test.o: test/core/metrics/cpu/core_events_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/metric_builder_test.o: test/core/metrics/metric_builder_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/tmanalysis_test.o: test/core/metrics/tmanalysis_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/block_group_profiler_test.o: test/core/pmu/cpu/perf/block_group_profiler_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/block_profiler_test.o: test/core/pmu/cpu/perf/block_profiler_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pmu_event_manager_test.o: test/core/pmu/cpu/pmu_event_manager_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query_pmu_test.o: test/core/pmu/cpu/query_pmu_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query_test.o: test/core/query_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main_test.o: test/main_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utils_test.o: test/utils/utils_test.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif