# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -Isrc -Ilib/libpfm4/include -Ilib/spdlog/include -I/opt/rocm/include -I/usr/local/cuda/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/liboptkit_c.so
OBJDIR = bin/obj/Debug/optkit_c
DEFINES += -DOPTKIT_MODE_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -fPIC -g -Wall -O0 -g -fopenmp -fPIC -fno-omit-frame-pointer -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=0 -DCONF_LOG_DISABLE_TRACE=0 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -DOPTKIT_TESTING=1
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -fPIC -g -std=c++11 -Wall -O0 -g -fopenmp -fPIC -fno-omit-frame-pointer -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=0 -DCONF_LOG_DISABLE_TRACE=0 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -DOPTKIT_TESTING=1
LIBS += bin/Debug/liboptkit_dynamic.so -lpthread -ldl -lnvidia-ml -lamd_smi -lcupti
LDDEPS += bin/Debug/liboptkit_dynamic.so
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib/x86_64-linux-gnu -L/opt/rocm/lib -L/usr/local/cuda/lib64 -Wl,-rpath,'$$ORIGIN' -shared -Wl,-soname=liboptkit_c.so -fopenmp -rdynamic ./lib/spdlog/build/libspdlog.a

else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/liboptkit_c.so
OBJDIR = bin/obj/Release/optkit_c
DEFINES +=
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -Wall -O2 -fopenmp -fPIC -march=native -funroll-loops -ftree-vectorize -fno-omit-frame-pointer -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -msse
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -std=c++11 -Wall -O2 -fopenmp -fPIC -march=native -funroll-loops -ftree-vectorize -fno-omit-frame-pointer -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -msse
LIBS += bin/Release/liboptkit_dynamic.so -lpthread -ldl -lnvidia-ml -lamd_smi -lcupti
LDDEPS += bin/Release/liboptkit_dynamic.so
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib/x86_64-linux-gnu -L/opt/rocm/lib -L/usr/local/cuda/lib64 -Wl,-rpath,'$$ORIGIN' -shared -Wl,-soname=liboptkit_c.so -s -fopenmp -rdynamic ./lib/spdlog/build/libspdlog.a

else ifeq ($(config),test)
TARGETDIR = bin/Test
TARGET = $(TARGETDIR)/liboptkit_c.so
OBJDIR = bin/obj/Test/optkit_c
DEFINES += -DOPTKIT_MODE_NDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -Wall -O2 -fopenmp -fPIC -march=native -funroll-loops -ftree-vectorize -fopt-info-vec -fno-omit-frame-pointer -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -DOPTKIT_TESTING=1 -msse
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -std=c++11 -Wall -O2 -fopenmp -fPIC -march=native -funroll-loops -ftree-vectorize -fopt-info-vec -fno-omit-frame-pointer -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -DOPTKIT_TESTING=1 -msse
LIBS += bin/Test/liboptkit_dynamic.so -lpthread -ldl -lnvidia-ml -lamd_smi -lcupti
LDDEPS += bin/Test/liboptkit_dynamic.so
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib/x86_64-linux-gnu -L/opt/rocm/lib -L/usr/local/cuda/lib64 -Wl,-rpath,'$$ORIGIN' -shared -Wl,-soname=liboptkit_c.so -s -fopenmp -rdynamic ./lib/spdlog/build/libspdlog.a

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/optkit_c.o
OBJECTS += $(OBJDIR)/optkit_c.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking optkit_c
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning optkit_c
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/optkit_c.o: src/optkit_c.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif