# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -Isrc -Ilib/libpfm4/include -Ilib/spdlog/include -I/usr/local/cuda/include -I/opt/rocm/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS += -lpthread -ldl -lnvidia-ml -lamd_smi
LDDEPS +=
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/liboptkit_static.a
OBJDIR = bin/obj/Debug/optkit_static
DEFINES += -DOPTKIT_MODE_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g -Wall -O0 -g -fopenmp -fPIC -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=0 -DCONF_LOG_DISABLE_TRACE=0 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -DOPTKIT_TESTING=1
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g -std=c++11 -Wall -O0 -g -fopenmp -fPIC -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=0 -DCONF_LOG_DISABLE_TRACE=0 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -DOPTKIT_TESTING=1
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib/x86_64-linux-gnu -L/opt/rocm/lib -fopenmp ./lib/spdlog/build/libspdlog.a
define POSTBUILDCMDS
endef

else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/liboptkit_static.a
OBJDIR = bin/obj/Release/optkit_static
DEFINES += -DOPTKIT_MODE_NDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -O2 -fopenmp -fPIC -march=native -funroll-loops -ftree-vectorize -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -msse
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -std=c++11 -Wall -O2 -fopenmp -fPIC -march=native -funroll-loops -ftree-vectorize -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -msse
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib/x86_64-linux-gnu -L/opt/rocm/lib -s -fopenmp ./lib/spdlog/build/libspdlog.a
define POSTBUILDCMDS
	@echo Running postbuild commands
	mkdir -p bin/obj/pfm_extract
	cd bin/obj/pfm_extract && ar -x /home/rt7/Desktop/OPTKIT/lib/libpfm4/lib/libpfm.a
	cd bin/obj/pfm_extract && ar -r ../../Release/liboptkit_static.a *.o
	rm -rf bin/obj/pfm_extract
	@echo [COMPILE UTILITY TOOLS]
	@cd ./tools && ./compile.sh && echo [✅ COMPILE UTILITY TOOLS]
endef

else ifeq ($(config),test)
TARGETDIR = bin/Test
TARGET = $(TARGETDIR)/liboptkit_static.a
OBJDIR = bin/obj/Test/optkit_static
DEFINES += -DOPTKIT_MODE_NDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -O2 -fopenmp -fPIC -march=native -funroll-loops -ftree-vectorize -fopt-info-vec -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -DOPTKIT_TESTING=1 -msse
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -std=c++11 -Wall -O2 -fopenmp -fPIC -march=native -funroll-loops -ftree-vectorize -fopt-info-vec -DCONF_LOG_PRINT_GUID_LENGTH=10 -DCONF_LOG_DISABLE_DEBUG=1 -DCONF_LOG_DISABLE_TRACE=1 -DCONF_LOG_DISABLE_INFO=0 -DCONF_LOG_DISABLE_WARN=0 -DCONF_LOG_DISABLE_ERROR=0 -DOPTKIT_TESTING=1 -msse
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib/x86_64-linux-gnu -L/opt/rocm/lib -s -fopenmp ./lib/spdlog/build/libspdlog.a
define POSTBUILDCMDS
	@echo Running postbuild commands
	mkdir -p bin/obj/pfm_extract
	cd bin/obj/pfm_extract && ar -x /home/rt7/Desktop/OPTKIT/lib/libpfm4/lib/libpfm.a
	cd bin/obj/pfm_extract && ar -r ../../Test/liboptkit_static.a *.o
	rm -rf bin/obj/pfm_extract
endef

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/bdw_recepies.o
GENERATED += $(OBJDIR)/block_group_profiler.o
GENERATED += $(OBJDIR)/block_group_profiler1.o
GENERATED += $(OBJDIR)/block_profiler.o
GENERATED += $(OBJDIR)/block_profiler1.o
GENERATED += $(OBJDIR)/core_events.o
GENERATED += $(OBJDIR)/core_events1.o
GENERATED += $(OBJDIR)/core_events2.o
GENERATED += $(OBJDIR)/core_events3.o
GENERATED += $(OBJDIR)/cpu_frequency.o
GENERATED += $(OBJDIR)/disk_profiler.o
GENERATED += $(OBJDIR)/event_mapper.o
GENERATED += $(OBJDIR)/event_mapper1.o
GENERATED += $(OBJDIR)/event_mapper2.o
GENERATED += $(OBJDIR)/gpu.o
GENERATED += $(OBJDIR)/gpu_query.o
GENERATED += $(OBJDIR)/icl_recepies.o
GENERATED += $(OBJDIR)/libpfm4_wrapper.o
GENERATED += $(OBJDIR)/logger.o
GENERATED += $(OBJDIR)/native_events.o
GENERATED += $(OBJDIR)/native_events1.o
GENERATED += $(OBJDIR)/native_events2.o
GENERATED += $(OBJDIR)/optkit.o
GENERATED += $(OBJDIR)/pmu_event_manager.o
GENERATED += $(OBJDIR)/profiler.o
GENERATED += $(OBJDIR)/profiler1.o
GENERATED += $(OBJDIR)/profiler2.o
GENERATED += $(OBJDIR)/profiler3.o
GENERATED += $(OBJDIR)/profiler4.o
GENERATED += $(OBJDIR)/profiler_config.o
GENERATED += $(OBJDIR)/profiler_config1.o
GENERATED += $(OBJDIR)/query.o
GENERATED += $(OBJDIR)/query1.o
GENERATED += $(OBJDIR)/query_cpu_frequency.o
GENERATED += $(OBJDIR)/query_pmu.o
GENERATED += $(OBJDIR)/rapl.o
GENERATED += $(OBJDIR)/skl_recepies.o
GENERATED += $(OBJDIR)/utils.o
GENERATED += $(OBJDIR)/utils1.o
OBJECTS += $(OBJDIR)/bdw_recepies.o
OBJECTS += $(OBJDIR)/block_group_profiler.o
OBJECTS += $(OBJDIR)/block_group_profiler1.o
OBJECTS += $(OBJDIR)/block_profiler.o
OBJECTS += $(OBJDIR)/block_profiler1.o
OBJECTS += $(OBJDIR)/core_events.o
OBJECTS += $(OBJDIR)/core_events1.o
OBJECTS += $(OBJDIR)/core_events2.o
OBJECTS += $(OBJDIR)/core_events3.o
OBJECTS += $(OBJDIR)/cpu_frequency.o
OBJECTS += $(OBJDIR)/disk_profiler.o
OBJECTS += $(OBJDIR)/event_mapper.o
OBJECTS += $(OBJDIR)/event_mapper1.o
OBJECTS += $(OBJDIR)/event_mapper2.o
OBJECTS += $(OBJDIR)/gpu.o
OBJECTS += $(OBJDIR)/gpu_query.o
OBJECTS += $(OBJDIR)/icl_recepies.o
OBJECTS += $(OBJDIR)/libpfm4_wrapper.o
OBJECTS += $(OBJDIR)/logger.o
OBJECTS += $(OBJDIR)/native_events.o
OBJECTS += $(OBJDIR)/native_events1.o
OBJECTS += $(OBJDIR)/native_events2.o
OBJECTS += $(OBJDIR)/optkit.o
OBJECTS += $(OBJDIR)/pmu_event_manager.o
OBJECTS += $(OBJDIR)/profiler.o
OBJECTS += $(OBJDIR)/profiler1.o
OBJECTS += $(OBJDIR)/profiler2.o
OBJECTS += $(OBJDIR)/profiler3.o
OBJECTS += $(OBJDIR)/profiler4.o
OBJECTS += $(OBJDIR)/profiler_config.o
OBJECTS += $(OBJDIR)/profiler_config1.o
OBJECTS += $(OBJDIR)/query.o
OBJECTS += $(OBJDIR)/query1.o
OBJECTS += $(OBJDIR)/query_cpu_frequency.o
OBJECTS += $(OBJDIR)/query_pmu.o
OBJECTS += $(OBJDIR)/rapl.o
OBJECTS += $(OBJDIR)/skl_recepies.o
OBJECTS += $(OBJDIR)/utils.o
OBJECTS += $(OBJDIR)/utils1.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking optkit_static
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning optkit_static
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/disk_profiler.o: src/core/disk/disk_profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/profiler.o: src/core/energy/cpu/rapl/profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query.o: src/core/energy/cpu/rapl/query.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rapl.o: src/core/energy/cpu/rapl/rapl.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utils.o: src/core/energy/cpu/rapl/utils.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/profiler1.o: src/core/energy/gpu/amd/profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/profiler2.o: src/core/energy/gpu/nvidia/profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cpu_frequency.o: src/core/frequency/cpu/cpu_frequency.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query_cpu_frequency.o: src/core/frequency/cpu/query_cpu_frequency.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/gpu_query.o: src/core/gpu_query.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_events.o: src/core/metrics/disk/core_events.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_events1.o: src/core/metrics/energy/core_events.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/event_mapper.o: src/core/metrics/performance/cpu/amd/event_mapper.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/native_events.o: src/core/metrics/performance/cpu/amd/native_events.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/event_mapper1.o: src/core/metrics/performance/cpu/arm/event_mapper.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/native_events1.o: src/core/metrics/performance/cpu/arm/native_events.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_events2.o: src/core/metrics/performance/cpu/core_events.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/bdw_recepies.o: src/core/metrics/performance/cpu/intel/bdw/bdw_recepies.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/event_mapper2.o: src/core/metrics/performance/cpu/intel/event_mapper.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/icl_recepies.o: src/core/metrics/performance/cpu/intel/icl/icl_recepies.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/native_events2.o: src/core/metrics/performance/cpu/intel/native_events.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/skl_recepies.o: src/core/metrics/performance/cpu/intel/skl/skl_recepies.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core_events3.o: src/core/metrics/temperature/core_events.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/libpfm4_wrapper.o: src/core/pmu/cpu/libpfm4_wrapper.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/block_group_profiler.o: src/core/pmu/cpu/msr/block_group_profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/block_profiler.o: src/core/pmu/cpu/msr/block_profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/profiler_config.o: src/core/pmu/cpu/msr/profiler_config.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/block_group_profiler1.o: src/core/pmu/cpu/perf/block_group_profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/block_profiler1.o: src/core/pmu/cpu/perf/block_profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/profiler_config1.o: src/core/pmu/cpu/perf/profiler_config.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pmu_event_manager.o: src/core/pmu/cpu/pmu_event_manager.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query_pmu.o: src/core/pmu/cpu/query_pmu.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/query1.o: src/core/query.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/profiler3.o: src/core/temperature/gpu/profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/profiler4.o: src/core/temperature/hwmon/profiler.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/optkit.o: src/optkit.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/gpu.o: src/utils/gpu.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/logger.o: src/utils/logging/logger.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utils1.o: src/utils/utils.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif