#pragma once
#include <cstdint>
#define INTEL_X86_EDGE_BIT	18
#define INTEL_X86_ANY_BIT	21
#define INTEL_X86_INV_BIT	23
#define INTEL_X86_CMASK_BIT 24
#define INTEL_X86_MOD_EDGE	(1 << INTEL_X86_EDGE_BIT)
#define INTEL_X86_MOD_ANY	(1 << INTEL_X86_ANY_BIT)
#define INTEL_X86_MOD_INV	(1 << INTEL_X86_INV_BIT)
namespace optkit::intel::icx_unc_iio{
	enum icx_unc_iio : uint64_t {
		UNC_IIO_BANDWIDTH_IN = 0x0000, // Free running counter that increments for every 32 bytes of data sent from the IO agent to the SOC
		UNC_IIO_BANDWIDTH_IN__MASK__ICX_UNC_IIO_BANDWIDTH_IN__PART0_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_IN__MASK__ICX_UNC_IIO_BANDWIDTH_IN__PART1_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_IN__MASK__ICX_UNC_IIO_BANDWIDTH_IN__PART2_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_IN__MASK__ICX_UNC_IIO_BANDWIDTH_IN__PART3_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_IN__MASK__ICX_UNC_IIO_BANDWIDTH_IN__PART4_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_IN__MASK__ICX_UNC_IIO_BANDWIDTH_IN__PART5_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_IN__MASK__ICX_UNC_IIO_BANDWIDTH_IN__PART6_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_IN__MASK__ICX_UNC_IIO_BANDWIDTH_IN__PART7_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_OUT = 0x0000, // Free running counter that increments for every 32 bytes of data sent from the IO agent to the SOC
		UNC_IIO_BANDWIDTH_OUT__MASK__ICX_UNC_IIO_BANDWIDTH_OUT__PART0_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_OUT__MASK__ICX_UNC_IIO_BANDWIDTH_OUT__PART1_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_OUT__MASK__ICX_UNC_IIO_BANDWIDTH_OUT__PART2_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_OUT__MASK__ICX_UNC_IIO_BANDWIDTH_OUT__PART3_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_OUT__MASK__ICX_UNC_IIO_BANDWIDTH_OUT__PART4_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_OUT__MASK__ICX_UNC_IIO_BANDWIDTH_OUT__PART5_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_OUT__MASK__ICX_UNC_IIO_BANDWIDTH_OUT__PART6_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_BANDWIDTH_OUT__MASK__ICX_UNC_IIO_BANDWIDTH_OUT__PART7_FREERUN = 0x0000ull, // TBD (experimental)
		UNC_IIO_CLOCKTICKS = 0x0001, // Clockticks of the integrated IO (IIO) traffic controller
		UNC_IIO_CLOCKTICKS_FREERUN = 0x0000, // Free running counter that increments for IIO clocktick
		UNC_IIO_COMP_BUF_OCCUPANCY = 0x00d5, // PCIe Completion Buffer Occupancy of completions with data
		UNC_IIO_COMP_BUF_OCCUPANCY__MASK__ICX_UNC_IIO_COMP_BUF_OCCUPANCY__CMPD_ALL = 0x400000000ff00ull, // Part 0-7 (experimental)
		UNC_IIO_COMP_BUF_OCCUPANCY__MASK__ICX_UNC_IIO_COMP_BUF_OCCUPANCY__CMPD_ALL_PARTS = 0x400000000ff00ull, // Part 0-7
		UNC_IIO_COMP_BUF_OCCUPANCY__MASK__ICX_UNC_IIO_COMP_BUF_OCCUPANCY__CMPD_PART0 = 0x4000000000100ull, // Part 0
		UNC_IIO_COMP_BUF_OCCUPANCY__MASK__ICX_UNC_IIO_COMP_BUF_OCCUPANCY__CMPD_PART1 = 0x4000000000200ull, // Part 1
		UNC_IIO_COMP_BUF_OCCUPANCY__MASK__ICX_UNC_IIO_COMP_BUF_OCCUPANCY__CMPD_PART2 = 0x4000000000400ull, // Part 2
		UNC_IIO_COMP_BUF_OCCUPANCY__MASK__ICX_UNC_IIO_COMP_BUF_OCCUPANCY__CMPD_PART3 = 0x4000000000800ull, // Part 3
		UNC_IIO_COMP_BUF_OCCUPANCY__MASK__ICX_UNC_IIO_COMP_BUF_OCCUPANCY__CMPD_PART4 = 0x4000000001000ull, // Part 4
		UNC_IIO_COMP_BUF_OCCUPANCY__MASK__ICX_UNC_IIO_COMP_BUF_OCCUPANCY__CMPD_PART5 = 0x4000000002000ull, // Part 5
		UNC_IIO_COMP_BUF_OCCUPANCY__MASK__ICX_UNC_IIO_COMP_BUF_OCCUPANCY__CMPD_PART6 = 0x4000000004000ull, // Part 6
		UNC_IIO_COMP_BUF_OCCUPANCY__MASK__ICX_UNC_IIO_COMP_BUF_OCCUPANCY__CMPD_PART7 = 0x4000000008000ull, // Part 7
		UNC_IIO_DATA_REQ_BY_CPU = 0x00c0, // Data requested by the CPU
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_READ_IOMMU0 = 0x7100000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_READ_IOMMU1 = 0x7200000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_READ_PART0 = 0x7001000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_READ_PART1 = 0x7002000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_READ_PART2 = 0x7004000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_READ_PART3 = 0x7008000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_READ_PART4 = 0x7010000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_READ_PART5 = 0x7020000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_READ_PART6 = 0x7040000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_READ_PART7 = 0x7080000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_WRITE_IOMMU0 = 0x7100000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_WRITE_IOMMU1 = 0x7200000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_WRITE_PART0 = 0x7001000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_WRITE_PART1 = 0x7002000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_WRITE_PART2 = 0x7004000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_WRITE_PART3 = 0x7008000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_WRITE_PART4 = 0x7010000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_WRITE_PART5 = 0x7020000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_WRITE_PART6 = 0x7040000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__CFG_WRITE_PART7 = 0x7080000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_READ_IOMMU0 = 0x7100000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_READ_IOMMU1 = 0x7200000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_READ_PART0 = 0x7001000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_READ_PART1 = 0x7002000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_READ_PART2 = 0x7004000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_READ_PART3 = 0x7008000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_READ_PART4 = 0x7010000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_READ_PART5 = 0x7020000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_READ_PART6 = 0x7040000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_READ_PART7 = 0x7080000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_WRITE_IOMMU0 = 0x7100000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_WRITE_IOMMU1 = 0x7200000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_WRITE_PART0 = 0x7001000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_WRITE_PART1 = 0x7002000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_WRITE_PART2 = 0x7004000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_WRITE_PART3 = 0x7008000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_WRITE_PART4 = 0x7010000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_WRITE_PART5 = 0x7020000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_WRITE_PART6 = 0x7040000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__IO_WRITE_PART7 = 0x7080000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_READ_IOMMU0 = 0x7100000000400ull, // Core reporting completion of Card read from Core DRAM (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_READ_IOMMU1 = 0x7200000000400ull, // Core reporting completion of Card read from Core DRAM (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_READ_PART0 = 0x7001000000400ull, // Core reporting completion of Card read from Core DRAM
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_READ_PART1 = 0x7002000000400ull, // Core reporting completion of Card read from Core DRAM
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_READ_PART2 = 0x7004000000400ull, // Core reporting completion of Card read from Core DRAM
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_READ_PART3 = 0x7008000000400ull, // Core reporting completion of Card read from Core DRAM
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_READ_PART4 = 0x7010000000400ull, // Core reporting completion of Card read from Core DRAM
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_READ_PART5 = 0x7020000000400ull, // Core reporting completion of Card read from Core DRAM
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_READ_PART6 = 0x7040000000400ull, // Core reporting completion of Card read from Core DRAM
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_READ_PART7 = 0x7080000000400ull, // Core reporting completion of Card read from Core DRAM
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_WRITE_IOMMU0 = 0x7100000000100ull, // Core writing to Card's MMIO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_WRITE_IOMMU1 = 0x7200000000100ull, // Core writing to Card's MMIO space (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_WRITE_PART0 = 0x7001000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_WRITE_PART1 = 0x7002000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_WRITE_PART2 = 0x7004000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_WRITE_PART3 = 0x7008000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_WRITE_PART4 = 0x7010000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_WRITE_PART5 = 0x7020000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_WRITE_PART6 = 0x7040000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__MEM_WRITE_PART7 = 0x7080000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_READ_IOMMU0 = 0x7100000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_READ_IOMMU1 = 0x7200000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_READ_PART0 = 0x7001000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_READ_PART1 = 0x7002000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_READ_PART2 = 0x7004000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_READ_PART3 = 0x7008000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_READ_PART4 = 0x7010000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_READ_PART5 = 0x7020000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_READ_PART6 = 0x7040000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_READ_PART7 = 0x7080000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_WRITE_IOMMU0 = 0x7100000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_WRITE_IOMMU1 = 0x7200000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_WRITE_PART0 = 0x7001000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_WRITE_PART1 = 0x7002000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_WRITE_PART2 = 0x7004000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_WRITE_PART3 = 0x7008000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_WRITE_PART4 = 0x7010000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_WRITE_PART5 = 0x7020000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_WRITE_PART6 = 0x7040000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_DATA_REQ_BY_CPU__MASK__ICX_UNC_IIO_DATA_REQ_BY_CPU__PEER_WRITE_PART7 = 0x7080000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_DATA_REQ_OF_CPU = 0x0083, // Four byte data request of the CPU
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__ATOMIC_IOMMU0 = 0x7100000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__ATOMIC_IOMMU1 = 0x7200000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__ATOMIC_PART0 = 0x7001000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__ATOMIC_PART1 = 0x7002000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__ATOMIC_PART2 = 0x7004000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__ATOMIC_PART3 = 0x7008000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__ATOMIC_PART4 = 0x7010000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__ATOMIC_PART5 = 0x7020000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__ATOMIC_PART6 = 0x7040000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__ATOMIC_PART7 = 0x7080000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__CMPD_IOMMU0 = 0x7100000008000ull, // CmpD - device sending completion to CPU request (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__CMPD_IOMMU1 = 0x7200000008000ull, // CmpD - device sending completion to CPU request (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__CMPD_PART0 = 0x7001000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__CMPD_PART1 = 0x7002000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__CMPD_PART2 = 0x7004000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__CMPD_PART3 = 0x7008000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__CMPD_PART4 = 0x7010000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__CMPD_PART5 = 0x7020000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__CMPD_PART6 = 0x7040000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__CMPD_PART7 = 0x7080000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_READ_IOMMU0 = 0x7100000000400ull, // Card reading from DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_READ_IOMMU1 = 0x7200000000400ull, // Card reading from DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_READ_PART0 = 0x7001000000400ull, // Card reading from DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_READ_PART1 = 0x7002000000400ull, // Card reading from DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_READ_PART2 = 0x7004000000400ull, // Card reading from DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_READ_PART3 = 0x7008000000400ull, // Card reading from DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_READ_PART4 = 0x7010000000400ull, // Card reading from DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_READ_PART5 = 0x7020000000400ull, // Card reading from DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_READ_PART6 = 0x7040000000400ull, // Card reading from DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_READ_PART7 = 0x7080000000400ull, // Card reading from DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_WRITE_IOMMU0 = 0x7100000000100ull, // Card writing to DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_WRITE_IOMMU1 = 0x7200000000100ull, // Card writing to DRAM (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_WRITE_PART0 = 0x7001000000100ull, // Card writing to DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_WRITE_PART1 = 0x7002000000100ull, // Card writing to DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_WRITE_PART2 = 0x7004000000100ull, // Card writing to DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_WRITE_PART3 = 0x7008000000100ull, // Card writing to DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_WRITE_PART4 = 0x7010000000100ull, // Card writing to DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_WRITE_PART5 = 0x7020000000100ull, // Card writing to DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_WRITE_PART6 = 0x7040000000100ull, // Card writing to DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MEM_WRITE_PART7 = 0x7080000000100ull, // Card writing to DRAM
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MSG_IOMMU0 = 0x7100000004000ull, // Messages (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MSG_IOMMU1 = 0x7200000004000ull, // Messages (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MSG_PART0 = 0x7001000004000ull, // Messages (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MSG_PART1 = 0x7002000004000ull, // Messages (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MSG_PART2 = 0x7004000004000ull, // Messages (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MSG_PART3 = 0x7008000004000ull, // Messages (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MSG_PART4 = 0x7010000004000ull, // Messages (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MSG_PART5 = 0x7020000004000ull, // Messages (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MSG_PART6 = 0x7040000004000ull, // Messages (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__MSG_PART7 = 0x7080000004000ull, // Messages (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_READ_IOMMU0 = 0x7100000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_READ_IOMMU1 = 0x7200000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_READ_PART0 = 0x7001000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_READ_PART1 = 0x7002000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_READ_PART2 = 0x7004000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_READ_PART3 = 0x7008000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_READ_PART4 = 0x7010000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_READ_PART5 = 0x7020000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_READ_PART6 = 0x7040000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_READ_PART7 = 0x7080000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_WRITE_IOMMU0 = 0x7100000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_WRITE_IOMMU1 = 0x7200000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_WRITE_PART0 = 0x7001000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_WRITE_PART1 = 0x7002000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_WRITE_PART2 = 0x7004000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_WRITE_PART3 = 0x7008000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_WRITE_PART4 = 0x7010000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_WRITE_PART5 = 0x7020000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_WRITE_PART6 = 0x7040000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_DATA_REQ_OF_CPU__MASK__ICX_UNC_IIO_DATA_REQ_OF_CPU__PEER_WRITE_PART7 = 0x7080000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_INBOUND_ARB_REQ = 0x0086, // Incoming arbitration requests
		UNC_IIO_INBOUND_ARB_REQ__MASK__ICX_UNC_IIO_INBOUND_ARB_WON__DATA = 0x70ff000002000ull, // Passing data to be written (experimental)
		UNC_IIO_INBOUND_ARB_REQ__MASK__ICX_UNC_IIO_INBOUND_ARB_WON__FINAL_RD_WR = 0x70ff000000800ull, // Issuing final read or write of line (experimental)
		UNC_IIO_INBOUND_ARB_REQ__MASK__ICX_UNC_IIO_INBOUND_ARB_WON__IOMMU_HIT = 0x70ff000000200ull, // Processing response from IOMMU (experimental)
		UNC_IIO_INBOUND_ARB_REQ__MASK__ICX_UNC_IIO_INBOUND_ARB_WON__IOMMU_REQ = 0x70ff000000100ull, // Issuing to IOMMU (experimental)
		UNC_IIO_INBOUND_ARB_REQ__MASK__ICX_UNC_IIO_INBOUND_ARB_WON__REQ_OWN = 0x70ff000000400ull, // Request Ownership (experimental)
		UNC_IIO_INBOUND_ARB_REQ__MASK__ICX_UNC_IIO_INBOUND_ARB_WON__WR = 0x70ff000001000ull, // Writing line (experimental)
		UNC_IIO_INBOUND_ARB_WON = 0x0087, // Incoming arbitration requests granted
		UNC_IIO_INBOUND_ARB_WON__MASK__ICX_UNC_IIO_INBOUND_ARB_WON__DATA = 0x70ff000002000ull, // Passing data to be written (experimental)
		UNC_IIO_INBOUND_ARB_WON__MASK__ICX_UNC_IIO_INBOUND_ARB_WON__FINAL_RD_WR = 0x70ff000000800ull, // Issuing final read or write of line (experimental)
		UNC_IIO_INBOUND_ARB_WON__MASK__ICX_UNC_IIO_INBOUND_ARB_WON__IOMMU_HIT = 0x70ff000000200ull, // Processing response from IOMMU (experimental)
		UNC_IIO_INBOUND_ARB_WON__MASK__ICX_UNC_IIO_INBOUND_ARB_WON__IOMMU_REQ = 0x70ff000000100ull, // Issuing to IOMMU (experimental)
		UNC_IIO_INBOUND_ARB_WON__MASK__ICX_UNC_IIO_INBOUND_ARB_WON__REQ_OWN = 0x70ff000000400ull, // Request Ownership (experimental)
		UNC_IIO_INBOUND_ARB_WON__MASK__ICX_UNC_IIO_INBOUND_ARB_WON__WR = 0x70ff000001000ull, // Writing line (experimental)
		UNC_IIO_IOMMU0 = 0x0040, // TBD
		UNC_IIO_IOMMU0__MASK__ICX_UNC_IIO_IOMMU0__1G_HITS = 0x1000ull, // IOTLB Hits to a 1G Page (experimental)
		UNC_IIO_IOMMU0__MASK__ICX_UNC_IIO_IOMMU0__2M_HITS = 0x0800ull, // IOTLB Hits to a 2M Page (experimental)
		UNC_IIO_IOMMU0__MASK__ICX_UNC_IIO_IOMMU0__4K_HITS = 0x0400ull, // IOTLB Hits to a 4K Page (experimental)
		UNC_IIO_IOMMU0__MASK__ICX_UNC_IIO_IOMMU0__ALL_LOOKUPS = 0x0200ull, // IOTLB lookups all (experimental)
		UNC_IIO_IOMMU0__MASK__ICX_UNC_IIO_IOMMU0__CTXT_CACHE_HITS = 0x8000ull, // Context cache hits (experimental)
		UNC_IIO_IOMMU0__MASK__ICX_UNC_IIO_IOMMU0__CTXT_CACHE_LOOKUPS = 0x4000ull, // Context cache lookups (experimental)
		UNC_IIO_IOMMU0__MASK__ICX_UNC_IIO_IOMMU0__FIRST_LOOKUPS = 0x0100ull, // IOTLB lookups first (experimental)
		UNC_IIO_IOMMU0__MASK__ICX_UNC_IIO_IOMMU0__MISSES = 0x2000ull, // IOTLB Fills (same as IOTLB miss) (experimental)
		UNC_IIO_IOMMU1 = 0x0041, // TBD
		UNC_IIO_IOMMU1__MASK__ICX_UNC_IIO_IOMMU1__CYC_PWT_FULL = 0x8000ull, // Cycles PWT full (experimental)
		UNC_IIO_IOMMU1__MASK__ICX_UNC_IIO_IOMMU1__NUM_MEM_ACCESSES = 0x4000ull, // IOMMU memory access (experimental)
		UNC_IIO_IOMMU1__MASK__ICX_UNC_IIO_IOMMU1__PWC_1G_HITS = 0x0800ull, // PWC Hit to a 1G page (experimental)
		UNC_IIO_IOMMU1__MASK__ICX_UNC_IIO_IOMMU1__PWC_2M_HITS = 0x0400ull, // PWC Hit to a 2M page (experimental)
		UNC_IIO_IOMMU1__MASK__ICX_UNC_IIO_IOMMU1__PWC_4K_HITS = 0x0200ull, // PWC Hit to a 4K page (experimental)
		UNC_IIO_IOMMU1__MASK__ICX_UNC_IIO_IOMMU1__PWC_512G_HITS = 0x1000ull, // PWT Hit to a 256T page (experimental)
		UNC_IIO_IOMMU1__MASK__ICX_UNC_IIO_IOMMU1__PWC_CACHE_FILLS = 0x2000ull, // PageWalk cache fill (experimental)
		UNC_IIO_IOMMU1__MASK__ICX_UNC_IIO_IOMMU1__PWT_CACHE_LOOKUPS = 0x0100ull, // PageWalk cache lookup (experimental)
		UNC_IIO_IOMMU3 = 0x0043, // TBD
		UNC_IIO_IOMMU3__MASK__ICX_UNC_IIO_IOMMU3__INT_CACHE_HITS = 0x8000ull, // Interrupt Entry cache hit (experimental)
		UNC_IIO_IOMMU3__MASK__ICX_UNC_IIO_IOMMU3__INT_CACHE_LOOKUPS = 0x4000ull, // Interrupt Entry cache lookup (experimental)
		UNC_IIO_IOMMU3__MASK__ICX_UNC_IIO_IOMMU3__NUM_CTXT_CACHE_INVAL_DEVICE = 0x2000ull, // Device-selective Context cache invalidation cycles (experimental)
		UNC_IIO_IOMMU3__MASK__ICX_UNC_IIO_IOMMU3__NUM_CTXT_CACHE_INVAL_DOMAIN = 0x1000ull, // Domain-selective Context cache invalidation cycles (experimental)
		UNC_IIO_IOMMU3__MASK__ICX_UNC_IIO_IOMMU3__NUM_CTXT_CACHE_INVAL_GBL = 0x0800ull, // Context cache global invalidation cycles (experimental)
		UNC_IIO_IOMMU3__MASK__ICX_UNC_IIO_IOMMU3__NUM_INVAL_DOMAIN = 0x0200ull, // Domain-selective IOTLB invalidation cycles (experimental)
		UNC_IIO_IOMMU3__MASK__ICX_UNC_IIO_IOMMU3__NUM_INVAL_GBL = 0x0100ull, // Global IOTLB invalidation cycles (experimental)
		UNC_IIO_IOMMU3__MASK__ICX_UNC_IIO_IOMMU3__NUM_INVAL_PAGE = 0x0400ull, // Page-selective IOTLB invalidation cycles (experimental)
		UNC_IIO_MASK_MATCH_AND = 0x0002, // AND Mask/match for debug bus
		UNC_IIO_MASK_MATCH_AND__MASK__ICX_UNC_IIO_MASK_MATCH_OR__BUS0 = 0x0100ull, // Non-PCIE bus (experimental)
		UNC_IIO_MASK_MATCH_AND__MASK__ICX_UNC_IIO_MASK_MATCH_OR__BUS0_BUS1 = 0x0800ull, // Non-PCIE bus and PCIE bus (experimental)
		UNC_IIO_MASK_MATCH_AND__MASK__ICX_UNC_IIO_MASK_MATCH_OR__BUS0_NOT_BUS1 = 0x0400ull, // Non-PCIE bus and !(PCIE bus) (experimental)
		UNC_IIO_MASK_MATCH_AND__MASK__ICX_UNC_IIO_MASK_MATCH_OR__BUS1 = 0x0200ull, // PCIE bus (experimental)
		UNC_IIO_MASK_MATCH_AND__MASK__ICX_UNC_IIO_MASK_MATCH_OR__NOT_BUS0_BUS1 = 0x1000ull, // !(Non-PCIE bus) and PCIE bus (experimental)
		UNC_IIO_MASK_MATCH_AND__MASK__ICX_UNC_IIO_MASK_MATCH_OR__NOT_BUS0_NOT_BUS1 = 0x2000ull, // !(Non-PCIE bus) and !(PCIE bus) (experimental)
		UNC_IIO_MASK_MATCH_OR = 0x0003, // OR Mask/match for debug bus
		UNC_IIO_MASK_MATCH_OR__MASK__ICX_UNC_IIO_MASK_MATCH_OR__BUS0 = 0x0100ull, // Non-PCIE bus (experimental)
		UNC_IIO_MASK_MATCH_OR__MASK__ICX_UNC_IIO_MASK_MATCH_OR__BUS0_BUS1 = 0x0800ull, // Non-PCIE bus and PCIE bus (experimental)
		UNC_IIO_MASK_MATCH_OR__MASK__ICX_UNC_IIO_MASK_MATCH_OR__BUS0_NOT_BUS1 = 0x0400ull, // Non-PCIE bus and !(PCIE bus) (experimental)
		UNC_IIO_MASK_MATCH_OR__MASK__ICX_UNC_IIO_MASK_MATCH_OR__BUS1 = 0x0200ull, // PCIE bus (experimental)
		UNC_IIO_MASK_MATCH_OR__MASK__ICX_UNC_IIO_MASK_MATCH_OR__NOT_BUS0_BUS1 = 0x1000ull, // !(Non-PCIE bus) and PCIE bus (experimental)
		UNC_IIO_MASK_MATCH_OR__MASK__ICX_UNC_IIO_MASK_MATCH_OR__NOT_BUS0_NOT_BUS1 = 0x2000ull, // !(Non-PCIE bus) and !(PCIE bus) (experimental)
		UNC_IIO_NOTHING = 0x0080, // Counting disabled (experimental)
		UNC_IIO_NUM_OUSTANDING_REQ_FROM_CPU = 0x00c5, // Occupancy of outbound request queue
		UNC_IIO_NUM_OUSTANDING_REQ_FROM_CPU__MASK__ICX_UNC_IIO_NUM_OUSTANDING_REQ_FROM_CPU__TO_IO = 0x70ff000000800ull, // To device (experimental)
		UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU = 0x0088, // TBD
		UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU__MASK__ICX_UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU__DATA = 0x70ff000002000ull, // Passing data to be written (experimental)
		UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU__MASK__ICX_UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU__FINAL_RD_WR = 0x70ff000000800ull, // Issuing final read or write of line (experimental)
		UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU__MASK__ICX_UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU__IOMMU_HIT = 0x70ff000000200ull, // Processing response from IOMMU (experimental)
		UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU__MASK__ICX_UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU__IOMMU_REQ = 0x70ff000000100ull, // Issuing to IOMMU (experimental)
		UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU__MASK__ICX_UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU__REQ_OWN = 0x70ff000000400ull, // Request Ownership (experimental)
		UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU__MASK__ICX_UNC_IIO_NUM_OUTSTANDING_REQ_OF_CPU__WR = 0x70ff000001000ull, // Writing line (experimental)
		UNC_IIO_NUM_REQ_FROM_CPU = 0x00c2, // Number requests sent to PCIe from main die
		UNC_IIO_NUM_REQ_FROM_CPU__MASK__ICX_UNC_IIO_NUM_REQ_FROM_CPU__IRP = 0x70ff000000100ull, // From IRP (experimental)
		UNC_IIO_NUM_REQ_FROM_CPU__MASK__ICX_UNC_IIO_NUM_REQ_FROM_CPU__ITC = 0x70ff000000200ull, // From ITC (experimental)
		UNC_IIO_NUM_REQ_FROM_CPU__MASK__ICX_UNC_IIO_NUM_REQ_FROM_CPU__PREALLOC = 0x70ff000000400ull, // Completion allocations (experimental)
		UNC_IIO_NUM_REQ_OF_CPU = 0x0085, // Number requests PCIe makes of the main die
		UNC_IIO_NUM_REQ_OF_CPU__MASK__ICX_UNC_IIO_NUM_REQ_OF_CPU__ALL_DROP = 0x70ff000000200ull, // Drop request (experimental)
		UNC_IIO_NUM_REQ_OF_CPU__MASK__ICX_UNC_IIO_NUM_REQ_OF_CPU__COMMIT_ALL = 0x70ff000000100ull, // All
		UNC_IIO_NUM_REQ_OF_CPU_BY_TGT = 0x008e, // Num requests sent by PCIe - by target
		UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__MASK__ICX_UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__ABORT = 0x70ff000008000ull, // Abort (experimental)
		UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__MASK__ICX_UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__CONFINED_P2P = 0x70ff000004000ull, // Confined P2P (experimental)
		UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__MASK__ICX_UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__LOC_P2P = 0x70ff000002000ull, // Local P2P (experimental)
		UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__MASK__ICX_UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__MCAST = 0x70ff000000200ull, // Multi-cast (experimental)
		UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__MASK__ICX_UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__MEM = 0x70ff000000800ull, // Memory (experimental)
		UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__MASK__ICX_UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__MSGB = 0x70ff000000100ull, // MsgB (experimental)
		UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__MASK__ICX_UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__REM_P2P = 0x70ff000001000ull, // Remote P2P (experimental)
		UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__MASK__ICX_UNC_IIO_NUM_REQ_OF_CPU_BY_TGT__UBOX = 0x70ff000000400ull, // Ubox (experimental)
		UNC_IIO_NUM_TGT_MATCHED_REQ_OF_CPU = 0x008f, // ITC address map 1 (experimental)
		UNC_IIO_OUTBOUND_CL_REQS_ISSUED = 0x00d0, // Outbound cacheline requests issued
		UNC_IIO_OUTBOUND_CL_REQS_ISSUED__MASK__ICX_UNC_IIO_OUTBOUND_CL_REQS_ISSUED__TO_IO = 0x70ff000000800ull, // 64B requests issued to device (experimental)
		UNC_IIO_OUTBOUND_TLP_REQS_ISSUED = 0x00d1, // Outbound TLP (transaction layer packet) requests issued
		UNC_IIO_OUTBOUND_TLP_REQS_ISSUED__MASK__ICX_UNC_IIO_OUTBOUND_TLP_REQS_ISSUED__TO_IO = 0x70ff000000800ull, // To device (experimental)
		UNC_IIO_PWT_OCCUPANCY = 0x0042, // PWT occupancy (experimental)
		UNC_IIO_REQ_FROM_PCIE_CL_CMPL = 0x0091, // PCIe Request - cacheline complete
		UNC_IIO_REQ_FROM_PCIE_CL_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_PASS_CMPL__DATA = 0x70ff000002000ull, // Passing data to be written (experimental)
		UNC_IIO_REQ_FROM_PCIE_CL_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_PASS_CMPL__FINAL_RD_WR = 0x70ff000000800ull, // Issuing final read or write of line (experimental)
		UNC_IIO_REQ_FROM_PCIE_CL_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_PASS_CMPL__REQ_OWN = 0x70ff000000400ull, // Request Ownership (experimental)
		UNC_IIO_REQ_FROM_PCIE_CL_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_PASS_CMPL__WR = 0x70ff000001000ull, // Writing line (experimental)
		UNC_IIO_REQ_FROM_PCIE_CMPL = 0x0092, // PCIe Request complete
		UNC_IIO_REQ_FROM_PCIE_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_CMPL__DATA = 0x70ff000002000ull, // Passing data to be written (experimental)
		UNC_IIO_REQ_FROM_PCIE_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_CMPL__FINAL_RD_WR = 0x70ff000000800ull, // Issuing final read or write of line (experimental)
		UNC_IIO_REQ_FROM_PCIE_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_CMPL__IOMMU_HIT = 0x70ff000000200ull, // Processing response from IOMMU (experimental)
		UNC_IIO_REQ_FROM_PCIE_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_CMPL__IOMMU_REQ = 0x70ff000000100ull, // Issuing to IOMMU (experimental)
		UNC_IIO_REQ_FROM_PCIE_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_CMPL__REQ_OWN = 0x70ff000000400ull, // Request Ownership (experimental)
		UNC_IIO_REQ_FROM_PCIE_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_CMPL__WR = 0x70ff000001000ull, // Writing line (experimental)
		UNC_IIO_REQ_FROM_PCIE_PASS_CMPL = 0x0090, // PCIe Request - pass complete
		UNC_IIO_REQ_FROM_PCIE_PASS_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_PASS_CMPL__DATA = 0x70ff000002000ull, // Passing data to be written (experimental)
		UNC_IIO_REQ_FROM_PCIE_PASS_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_PASS_CMPL__FINAL_RD_WR = 0x70ff000000800ull, // Issuing final read or write of line (experimental)
		UNC_IIO_REQ_FROM_PCIE_PASS_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_PASS_CMPL__REQ_OWN = 0x70ff000000400ull, // Request Ownership (experimental)
		UNC_IIO_REQ_FROM_PCIE_PASS_CMPL__MASK__ICX_UNC_IIO_REQ_FROM_PCIE_PASS_CMPL__WR = 0x70ff000001000ull, // Writing line (experimental)
		UNC_IIO_SYMBOL_TIMES = 0x0082, // Symbol Times on Link (experimental)
		UNC_IIO_TXN_REQ_BY_CPU = 0x00c1, // Number Transactions requested by the CPU
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_READ_IOMMU0 = 0x7100000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_READ_IOMMU1 = 0x7200000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_READ_PART0 = 0x7001000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_READ_PART1 = 0x7002000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_READ_PART2 = 0x7004000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_READ_PART3 = 0x7008000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_READ_PART4 = 0x7010000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_READ_PART5 = 0x7020000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_READ_PART6 = 0x7040000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_READ_PART7 = 0x7080000004000ull, // Core reading from Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_WRITE_IOMMU0 = 0x7100000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_WRITE_IOMMU1 = 0x7200000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_WRITE_PART0 = 0x7001000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_WRITE_PART1 = 0x7002000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_WRITE_PART2 = 0x7004000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_WRITE_PART3 = 0x7008000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_WRITE_PART4 = 0x7010000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_WRITE_PART5 = 0x7020000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_WRITE_PART6 = 0x7040000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__CFG_WRITE_PART7 = 0x7080000001000ull, // Core writing to Card's PCICFG space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_READ_IOMMU0 = 0x7100000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_READ_IOMMU1 = 0x7200000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_READ_PART0 = 0x7001000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_READ_PART1 = 0x7002000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_READ_PART2 = 0x7004000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_READ_PART3 = 0x7008000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_READ_PART4 = 0x7010000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_READ_PART5 = 0x7020000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_READ_PART6 = 0x7040000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_READ_PART7 = 0x7080000008000ull, // Core reading from Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_WRITE_IOMMU0 = 0x7100000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_WRITE_IOMMU1 = 0x7200000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_WRITE_PART0 = 0x7001000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_WRITE_PART1 = 0x7002000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_WRITE_PART2 = 0x7004000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_WRITE_PART3 = 0x7008000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_WRITE_PART4 = 0x7010000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_WRITE_PART5 = 0x7020000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_WRITE_PART6 = 0x7040000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__IO_WRITE_PART7 = 0x7080000002000ull, // Core writing to Card's IO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_READ_IOMMU0 = 0x7100000000400ull, // Core reading from Card's MMIO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_READ_IOMMU1 = 0x7200000000400ull, // Core reading from Card's MMIO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_READ_PART0 = 0x7001000000400ull, // Core reading from Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_READ_PART1 = 0x7002000000400ull, // Core reading from Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_READ_PART2 = 0x7004000000400ull, // Core reading from Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_READ_PART3 = 0x7008000000400ull, // Core reading from Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_READ_PART4 = 0x7010000000400ull, // Core reading from Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_READ_PART5 = 0x7020000000400ull, // Core reading from Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_READ_PART6 = 0x7040000000400ull, // Core reading from Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_READ_PART7 = 0x7080000000400ull, // Core reading from Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_WRITE_IOMMU0 = 0x7100000000100ull, // Core writing to Card's MMIO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_WRITE_IOMMU1 = 0x7200000000100ull, // Core writing to Card's MMIO space (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_WRITE_PART0 = 0x7001000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_WRITE_PART1 = 0x7002000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_WRITE_PART2 = 0x7004000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_WRITE_PART3 = 0x7008000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_WRITE_PART4 = 0x7010000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_WRITE_PART5 = 0x7020000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_WRITE_PART6 = 0x7040000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__MEM_WRITE_PART7 = 0x7080000000100ull, // Core writing to Card's MMIO space
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_READ_IOMMU0 = 0x7100000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_READ_IOMMU1 = 0x7200000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_READ_PART0 = 0x7001000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_READ_PART1 = 0x7002000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_READ_PART2 = 0x7004000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_READ_PART3 = 0x7008000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_READ_PART4 = 0x7010000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_READ_PART5 = 0x7020000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_READ_PART6 = 0x7040000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_READ_PART7 = 0x7080000000800ull, // Another card (different IIO stack) reading from this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_WRITE_IOMMU0 = 0x7200000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_WRITE_PART0 = 0x7001000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_WRITE_PART1 = 0x7002000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_WRITE_PART2 = 0x7004000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_WRITE_PART3 = 0x7008000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_WRITE_PART4 = 0x7010000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_WRITE_PART5 = 0x7020000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_WRITE_PART6 = 0x7040000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_TXN_REQ_BY_CPU__MASK__ICX_UNC_IIO_TXN_REQ_BY_CPU__PEER_WRITE_PART7 = 0x7080000000200ull, // Another card (different IIO stack) writing to this card. (experimental)
		UNC_IIO_TXN_REQ_OF_CPU = 0x0084, // Number Transactions requested of the CPU
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__ATOMIC_IOMMU0 = 0x7100000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__ATOMIC_IOMMU1 = 0x7200000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__ATOMIC_PART0 = 0x7001000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__ATOMIC_PART1 = 0x7002000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__ATOMIC_PART2 = 0x7004000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__ATOMIC_PART3 = 0x7008000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__ATOMIC_PART4 = 0x7010000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__ATOMIC_PART5 = 0x7020000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__ATOMIC_PART6 = 0x7040000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__ATOMIC_PART7 = 0x7080000001000ull, // Atomic requests targeting DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__CMPD_IOMMU0 = 0x7100000008000ull, // CmpD - device sending completion to CPU request (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__CMPD_IOMMU1 = 0x7200000008000ull, // CmpD - device sending completion to CPU request (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__CMPD_PART0 = 0x7001000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__CMPD_PART1 = 0x7002000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__CMPD_PART2 = 0x7004000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__CMPD_PART3 = 0x7008000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__CMPD_PART4 = 0x7010000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__CMPD_PART5 = 0x7020000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__CMPD_PART6 = 0x7040000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__CMPD_PART7 = 0x7080000008000ull, // CmpD - device sending completion to CPU request
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_READ_IOMMU0 = 0x7100000000400ull, // Card reading from DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_READ_IOMMU1 = 0x7200000000400ull, // Card reading from DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_READ_PART0 = 0x7001000000400ull, // Card reading from DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_READ_PART1 = 0x7002000000400ull, // Card reading from DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_READ_PART2 = 0x7004000000400ull, // Card reading from DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_READ_PART3 = 0x7008000000400ull, // Card reading from DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_READ_PART4 = 0x7010000000400ull, // Card reading from DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_READ_PART5 = 0x7020000000400ull, // Card reading from DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_READ_PART6 = 0x7040000000400ull, // Card reading from DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_READ_PART7 = 0x7080000000400ull, // Card reading from DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_WRITE_IOMMU0 = 0x7100000000100ull, // Card writing to DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_WRITE_IOMMU1 = 0x7200000000100ull, // Card writing to DRAM (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_WRITE_PART0 = 0x7001000000100ull, // Card writing to DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_WRITE_PART1 = 0x7002000000100ull, // Card writing to DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_WRITE_PART2 = 0x7004000000100ull, // Card writing to DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_WRITE_PART3 = 0x7008000000100ull, // Card writing to DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_WRITE_PART4 = 0x7010000000100ull, // Card writing to DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_WRITE_PART5 = 0x7020000000100ull, // Card writing to DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_WRITE_PART6 = 0x7040000000100ull, // Card writing to DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MEM_WRITE_PART7 = 0x7080000000100ull, // Card writing to DRAM
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MSG_IOMMU0 = 0x7100000004000ull, // Messages (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MSG_IOMMU1 = 0x7200000004000ull, // Messages (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MSG_PART0 = 0x7001000004000ull, // Messages (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MSG_PART1 = 0x7002000004000ull, // Messages (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MSG_PART2 = 0x7004000004000ull, // Messages (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MSG_PART3 = 0x7008000004000ull, // Messages (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MSG_PART4 = 0x7010000004000ull, // Messages (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MSG_PART5 = 0x7020000004000ull, // Messages (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MSG_PART6 = 0x7040000004000ull, // Messages (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__MSG_PART7 = 0x7080000004000ull, // Messages (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_READ_IOMMU0 = 0x7100000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_READ_IOMMU1 = 0x7200000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_READ_PART0 = 0x7001000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_READ_PART1 = 0x7002000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_READ_PART2 = 0x7004000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_READ_PART3 = 0x7008000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_READ_PART4 = 0x7010000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_READ_PART5 = 0x7020000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_READ_PART6 = 0x7040000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_READ_PART7 = 0x7080000000800ull, // Card reading from another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_WRITE_IOMMU0 = 0x7100000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_WRITE_IOMMU1 = 0x7200000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_WRITE_PART0 = 0x7001000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_WRITE_PART1 = 0x7002000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_WRITE_PART2 = 0x7004000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_WRITE_PART3 = 0x7008000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_WRITE_PART4 = 0x7010000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_WRITE_PART5 = 0x7020000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_WRITE_PART6 = 0x7040000000200ull, // Card writing to another Card (same or different stack) (experimental)
		UNC_IIO_TXN_REQ_OF_CPU__MASK__ICX_UNC_IIO_TXN_REQ_OF_CPU__PEER_WRITE_PART7 = 0x7080000000200ull, // Card writing to another Card (same or different stack) (experimental)
		
	};
};

namespace icx_unc_iio = optkit::intel::icx_unc_iio;

#undef INTEL_X86_EDGE_BIT
#undef INTEL_X86_ANY_BIT
#undef INTEL_X86_INV_BIT
#undef INTEL_X86_CMASK_BIT
#undef INTEL_X86_MOD_EDGE
#undef INTEL_X86_MOD_ANY
#undef INTEL_X86_MOD_INV
