#pragma once
#include <cstdint>
#define INTEL_X86_EDGE_BIT	18
#define INTEL_X86_ANY_BIT	21
#define INTEL_X86_INV_BIT	23
#define INTEL_X86_CMASK_BIT 24
#define INTEL_X86_MOD_EDGE	(1 << INTEL_X86_EDGE_BIT)
#define INTEL_X86_MOD_ANY	(1 << INTEL_X86_ANY_BIT)
#define INTEL_X86_MOD_INV	(1 << INTEL_X86_INV_BIT)
namespace optkit::intel::icx_unc_imc{
	enum icx_unc_imc : uint64_t {
		UNC_M_ACT_COUNT = 0x0001, // DRAM Activate Count
		UNC_M_ACT_COUNT__MASK__ICX_UNC_M_ACT_COUNT__ALL = 0x0b00ull, // All Activates
		UNC_M_ACT_COUNT__MASK__ICX_UNC_M_ACT_COUNT__BYP = 0x0800ull, // Activate due to Bypass (experimental)
		UNC_M_CAS_COUNT = 0x0004, // All DRAM read CAS commands issued (including underfills)
		UNC_M_CAS_COUNT__MASK__ICX_UNC_M_CAS_COUNT__ALL = 0x3f00ull, // TBD
		UNC_M_CAS_COUNT__MASK__ICX_UNC_M_CAS_COUNT__RD = 0x0f00ull, // TBD
		UNC_M_CAS_COUNT__MASK__ICX_UNC_M_CAS_COUNT__RD_PRE_REG = 0x0200ull, // DRAM RD_CAS commands w/auto-pre (experimental)
		UNC_M_CAS_COUNT__MASK__ICX_UNC_M_CAS_COUNT__RD_PRE_UNDERFILL = 0x0800ull, // TBD (experimental)
		UNC_M_CAS_COUNT__MASK__ICX_UNC_M_CAS_COUNT__RD_REG = 0x0100ull, // TBD (experimental)
		UNC_M_CAS_COUNT__MASK__ICX_UNC_M_CAS_COUNT__RD_UNDERFILL = 0x0400ull, // TBD (experimental)
		UNC_M_CAS_COUNT__MASK__ICX_UNC_M_CAS_COUNT__WR = 0x3000ull, // TBD
		UNC_M_CAS_COUNT__MASK__ICX_UNC_M_CAS_COUNT__WR_NONPRE = 0x1000ull, // DRAM WR_CAS commands w/o auto-pre (experimental)
		UNC_M_CAS_COUNT__MASK__ICX_UNC_M_CAS_COUNT__WR_PRE = 0x2000ull, // DRAM WR_CAS commands w/ auto-pre (experimental)
		UNC_M_CLOCKTICKS = 0x0000, // DRAM Clockticks
		UNC_M_CLOCKTICKS_FREERUN = 0x0000, // Free running counter that increments for the Memory Controller (experimental)
		UNC_M_DRAM_PRE_ALL = 0x0044, // DRAM Precharge All Commands (experimental)
		UNC_M_DRAM_REFRESH = 0x0045, // Number of DRAM Refreshes Issued
		UNC_M_DRAM_REFRESH__MASK__ICX_UNC_M_DRAM_REFRESH__HIGH = 0x0400ull, // TBD
		UNC_M_DRAM_REFRESH__MASK__ICX_UNC_M_DRAM_REFRESH__OPPORTUNISTIC = 0x0100ull, // TBD
		UNC_M_DRAM_REFRESH__MASK__ICX_UNC_M_DRAM_REFRESH__PANIC = 0x0200ull, // TBD
		UNC_M_HCLOCKTICKS = 0x0000, // Half clockticks for IMC
		UNC_M_PARITY_ERRORS = 0x002c, // UNC_M_PARITY_ERRORS (experimental)
		UNC_M_PCLS = 0x00a0, // UNC_M_PCLS.RD
		UNC_M_PCLS__MASK__ICX_UNC_M_PCLS__RD = 0x0100ull, // TBD (experimental)
		UNC_M_PCLS__MASK__ICX_UNC_M_PCLS__TOTAL = 0x0400ull, // TBD (experimental)
		UNC_M_PCLS__MASK__ICX_UNC_M_PCLS__WR = 0x0200ull, // TBD (experimental)
		UNC_M_PMM_CMD1 = 0x00ea, // PMM Commands
		UNC_M_PMM_CMD1__MASK__ICX_UNC_M_PMM_CMD1__ALL = 0x0100ull, // All
		UNC_M_PMM_CMD1__MASK__ICX_UNC_M_PMM_CMD1__MISC = 0x8000ull, // Misc Commands (error
		UNC_M_PMM_CMD1__MASK__ICX_UNC_M_PMM_CMD1__MISC_GNT = 0x4000ull, // Misc GNTs (experimental)
		UNC_M_PMM_CMD1__MASK__ICX_UNC_M_PMM_CMD1__RD = 0x0200ull, // Reads - RPQ
		UNC_M_PMM_CMD1__MASK__ICX_UNC_M_PMM_CMD1__RPQ_GNTS = 0x1000ull, // RPQ GNTs (experimental)
		UNC_M_PMM_CMD1__MASK__ICX_UNC_M_PMM_CMD1__UFILL_RD = 0x0800ull, // Underfill reads
		UNC_M_PMM_CMD1__MASK__ICX_UNC_M_PMM_CMD1__WPQ_GNTS = 0x2000ull, // Underfill GNTs (experimental)
		UNC_M_PMM_CMD1__MASK__ICX_UNC_M_PMM_CMD1__WR = 0x0400ull, // Writes
		UNC_M_PMM_CMD2 = 0x00eb, // PMM Commands - Part 2
		UNC_M_PMM_CMD2__MASK__ICX_UNC_M_PMM_CMD2__NODATA_EXP = 0x0200ull, // Expected No data packet (ERID matched NDP encoding) (experimental)
		UNC_M_PMM_CMD2__MASK__ICX_UNC_M_PMM_CMD2__NODATA_UNEXP = 0x0400ull, // Unexpected No data packet (ERID matched a Read
		UNC_M_PMM_CMD2__MASK__ICX_UNC_M_PMM_CMD2__OPP_RD = 0x0100ull, // Opportunistic Reads (experimental)
		UNC_M_PMM_CMD2__MASK__ICX_UNC_M_PMM_CMD2__PMM_ECC_ERROR = 0x2000ull, // ECC Errors (experimental)
		UNC_M_PMM_CMD2__MASK__ICX_UNC_M_PMM_CMD2__PMM_ERID_ERROR = 0x4000ull, // ERID detectable parity error (experimental)
		UNC_M_PMM_CMD2__MASK__ICX_UNC_M_PMM_CMD2__PMM_ERID_STARVED = 0x8000ull, // TBD (experimental)
		UNC_M_PMM_CMD2__MASK__ICX_UNC_M_PMM_CMD2__REQS_SLOT0 = 0x0800ull, // Read Requests - Slot 0 (experimental)
		UNC_M_PMM_CMD2__MASK__ICX_UNC_M_PMM_CMD2__REQS_SLOT1 = 0x1000ull, // Read Requests - Slot 1 (experimental)
		UNC_M_PMM_RPQ_CYCLES_FULL = 0x00e2, // PMM Read Queue Cycles Full (experimental)
		UNC_M_PMM_RPQ_CYCLES_NE = 0x00e1, // PMM Read Queue Cycles Not Empty (experimental)
		UNC_M_PMM_RPQ_INSERTS = 0x00e3, // PMM Read Queue Inserts
		UNC_M_PMM_RPQ_OCCUPANCY = 0x00e0, // PMM Read Pending Queue Occupancy
		UNC_M_PMM_RPQ_OCCUPANCY__MASK__ICX_UNC_M_PMM_RPQ_OCCUPANCY__ALL = 0x0100ull, // TBD
		UNC_M_PMM_RPQ_OCCUPANCY__MASK__ICX_UNC_M_PMM_RPQ_OCCUPANCY__GNT_WAIT = 0x0400ull, // TBD (experimental)
		UNC_M_PMM_RPQ_OCCUPANCY__MASK__ICX_UNC_M_PMM_RPQ_OCCUPANCY__NO_GNT = 0x0200ull, // TBD (experimental)
		UNC_M_PMM_WPQ_CYCLES_FULL = 0x00e6, // PMM Write Queue Cycles Full (experimental)
		UNC_M_PMM_WPQ_CYCLES_NE = 0x00e5, // PMM Write Queue Cycles Not Empty (experimental)
		UNC_M_PMM_WPQ_FLUSH = 0x00e8, // UNC_M_PMM_WPQ_FLUSH (experimental)
		UNC_M_PMM_WPQ_FLUSH_CYC = 0x00e9, // UNC_M_PMM_WPQ_FLUSH_CYC (experimental)
		UNC_M_PMM_WPQ_INSERTS = 0x00e7, // PMM Write Queue Inserts
		UNC_M_PMM_WPQ_OCCUPANCY = 0x00e4, // PMM Write Pending Queue Occupancy
		UNC_M_PMM_WPQ_OCCUPANCY__MASK__ICX_UNC_M_PMM_WPQ_OCCUPANCY__ALL = 0x0100ull, // TBD
		UNC_M_PMM_WPQ_OCCUPANCY__MASK__ICX_UNC_M_PMM_WPQ_OCCUPANCY__CAS = 0x0200ull, // TBD (experimental)
		UNC_M_PMM_WPQ_OCCUPANCY__MASK__ICX_UNC_M_PMM_WPQ_OCCUPANCY__PWR = 0x0400ull, // TBD (experimental)
		UNC_M_POWER_CHANNEL_PPD = 0x0085, // Channel PPD Cycles (experimental)
		UNC_M_POWER_CKE_CYCLES = 0x0047, // CKE_ON_CYCLES by Rank
		UNC_M_POWER_CKE_CYCLES__MASK__ICX_UNC_M_POWER_CKE_CYCLES__LOW_0 = 0x0100ull, // DIMM ID (experimental)
		UNC_M_POWER_CKE_CYCLES__MASK__ICX_UNC_M_POWER_CKE_CYCLES__LOW_1 = 0x0200ull, // DIMM ID (experimental)
		UNC_M_POWER_CKE_CYCLES__MASK__ICX_UNC_M_POWER_CKE_CYCLES__LOW_2 = 0x0400ull, // DIMM ID (experimental)
		UNC_M_POWER_CKE_CYCLES__MASK__ICX_UNC_M_POWER_CKE_CYCLES__LOW_3 = 0x0800ull, // DIMM ID (experimental)
		UNC_M_POWER_CRIT_THROTTLE_CYCLES = 0x0086, // Throttle Cycles for Rank 0
		UNC_M_POWER_CRIT_THROTTLE_CYCLES__MASK__ICX_UNC_M_POWER_THROTTLE_CYCLES__SLOT0 = 0x0100ull, // TBD (experimental)
		UNC_M_POWER_CRIT_THROTTLE_CYCLES__MASK__ICX_UNC_M_POWER_THROTTLE_CYCLES__SLOT1 = 0x0200ull, // TBD (experimental)
		UNC_M_POWER_SELF_REFRESH = 0x0043, // Clock-Enabled Self-Refresh (experimental)
		UNC_M_POWER_THROTTLE_CYCLES = 0x0046, // Throttle Cycles for Rank 0
		UNC_M_POWER_THROTTLE_CYCLES__MASK__ICX_UNC_M_POWER_THROTTLE_CYCLES__SLOT0 = 0x0100ull, // TBD (experimental)
		UNC_M_POWER_THROTTLE_CYCLES__MASK__ICX_UNC_M_POWER_THROTTLE_CYCLES__SLOT1 = 0x0200ull, // TBD (experimental)
		UNC_M_PRE_COUNT = 0x0002, // DRAM Precharge commands.
		UNC_M_PRE_COUNT__MASK__ICX_UNC_M_PRE_COUNT__ALL = 0x1c00ull, // TBD
		UNC_M_PRE_COUNT__MASK__ICX_UNC_M_PRE_COUNT__PAGE_MISS = 0x0c00ull, // Precharge due to page miss (experimental)
		UNC_M_PRE_COUNT__MASK__ICX_UNC_M_PRE_COUNT__PGT = 0x1000ull, // Precharge due to page table
		UNC_M_PRE_COUNT__MASK__ICX_UNC_M_PRE_COUNT__RD = 0x0400ull, // Precharge due to read
		UNC_M_PRE_COUNT__MASK__ICX_UNC_M_PRE_COUNT__WR = 0x0800ull, // Precharge due to write
		UNC_M_RDB_FULL = 0x0019, // Read Data Buffer Full (experimental)
		UNC_M_RDB_INSERTS = 0x0017, // Read Data Buffer Inserts (experimental)
		UNC_M_RDB_NOT_EMPTY = 0x0018, // Read Data Buffer Not Empty (experimental)
		UNC_M_RDB_OCCUPANCY = 0x001a, // Read Data Buffer Occupancy (experimental)
		UNC_M_RPQ_CYCLES_FULL_PCH0 = 0x0012, // Read Pending Queue Full Cycles (experimental)
		UNC_M_RPQ_CYCLES_FULL_PCH1 = 0x0015, // Read Pending Queue Full Cycles (experimental)
		UNC_M_RPQ_CYCLES_NE = 0x0011, // Read Pending Queue Not Empty
		UNC_M_RPQ_CYCLES_NE__MASK__ICX_UNC_M_RPQ_INSERTS__PCH0 = 0x0100ull, // TBD
		UNC_M_RPQ_CYCLES_NE__MASK__ICX_UNC_M_RPQ_INSERTS__PCH1 = 0x0200ull, // TBD
		UNC_M_RPQ_INSERTS = 0x0010, // Read Pending Queue Allocations
		UNC_M_RPQ_INSERTS__MASK__ICX_UNC_M_RPQ_INSERTS__PCH0 = 0x0100ull, // TBD
		UNC_M_RPQ_INSERTS__MASK__ICX_UNC_M_RPQ_INSERTS__PCH1 = 0x0200ull, // TBD
		UNC_M_RPQ_OCCUPANCY_PCH0 = 0x0080, // Read Pending Queue Occupancy
		UNC_M_RPQ_OCCUPANCY_PCH1 = 0x0081, // Read Pending Queue Occupancy
		UNC_M_SB_ACCESSES = 0x00d2, // Scoreboard Accesses
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__ACCEPTS = 0x0500ull, // Scoreboard Accesses Accepted (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__FMRD_CMPS = 0x4000ull, // TBD (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__FMWR_CMPS = 0x8000ull, // TBD (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__FM_RD_CMPS = 0x4000ull, // Write Accepts (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__FM_WR_CMPS = 0x8000ull, // Write Rejects (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__NMRD_CMPS = 0x1000ull, // TBD (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__NMWR_CMPS = 0x2000ull, // TBD (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__NM_RD_CMPS = 0x1000ull, // FM read completions (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__NM_WR_CMPS = 0x2000ull, // FM write completions (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__RD_ACCEPTS = 0x0100ull, // Read Accepts (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__RD_REJECTS = 0x0200ull, // Read Rejects (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__REJECTS = 0x0a00ull, // Scoreboard Accesses Rejected (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__WR_ACCEPTS = 0x0400ull, // NM read completions (experimental)
		UNC_M_SB_ACCESSES__MASK__ICX_UNC_M_SB_ACCESSES__WR_REJECTS = 0x0800ull, // NM write completions (experimental)
		UNC_M_SB_CANARY = 0x00d9, // TBD
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__ALLOC = 0x0100ull, // Alloc (experimental)
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__DEALLOC = 0x0200ull, // Dealloc (experimental)
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__FMRD_STARVED = 0x2000ull, // TBD (experimental)
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__FMTGRWR_STARVED = 0x8000ull, // TBD (experimental)
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__FMWR_STARVED = 0x4000ull, // TBD (experimental)
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__FM_RD_STARVED = 0x2000ull, // Near Mem Write Starved (experimental)
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__FM_TGR_WR_STARVED = 0x8000ull, // Far Mem Write Starved (experimental)
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__FM_WR_STARVED = 0x4000ull, // Far Mem Read Starved (experimental)
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__NMRD_STARVED = 0x0800ull, // TBD (experimental)
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__NMWR_STARVED = 0x1000ull, // TBD (experimental)
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__NM_RD_STARVED = 0x0800ull, // Valid (experimental)
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__NM_WR_STARVED = 0x1000ull, // Near Mem Read Starved (experimental)
		UNC_M_SB_CANARY__MASK__ICX_UNC_M_SB_CANARY__VLD = 0x0400ull, // Reject (experimental)
		UNC_M_SB_CYCLES_FULL = 0x00d1, // Scoreboard Cycles Full (experimental)
		UNC_M_SB_CYCLES_NE = 0x00d0, // Scoreboard Cycles Not-Empty (experimental)
		UNC_M_SB_INSERTS = 0x00d6, // Scoreboard Inserts
		UNC_M_SB_INSERTS__MASK__ICX_UNC_M_SB_INSERTS__BLOCK_RDS = 0x1000ull, // Block region reads (experimental)
		UNC_M_SB_INSERTS__MASK__ICX_UNC_M_SB_INSERTS__BLOCK_WRS = 0x2000ull, // Block region writes (experimental)
		UNC_M_SB_INSERTS__MASK__ICX_UNC_M_SB_INSERTS__PMM_RDS = 0x0400ull, // Persistent Mem reads (experimental)
		UNC_M_SB_INSERTS__MASK__ICX_UNC_M_SB_INSERTS__PMM_WRS = 0x0800ull, // Persistent Mem writes (experimental)
		UNC_M_SB_INSERTS__MASK__ICX_UNC_M_SB_INSERTS__RDS = 0x0100ull, // Reads (experimental)
		UNC_M_SB_INSERTS__MASK__ICX_UNC_M_SB_INSERTS__WRS = 0x0200ull, // Writes (experimental)
		UNC_M_SB_OCCUPANCY = 0x00d5, // Scoreboard Occupancy
		UNC_M_SB_OCCUPANCY__MASK__ICX_UNC_M_SB_OCCUPANCY__BLOCK_RDS = 0x2000ull, // Block region reads (experimental)
		UNC_M_SB_OCCUPANCY__MASK__ICX_UNC_M_SB_OCCUPANCY__BLOCK_WRS = 0x4000ull, // Block region writes (experimental)
		UNC_M_SB_OCCUPANCY__MASK__ICX_UNC_M_SB_OCCUPANCY__PMM_RDS = 0x0400ull, // Persistent Mem reads (experimental)
		UNC_M_SB_OCCUPANCY__MASK__ICX_UNC_M_SB_OCCUPANCY__PMM_WRS = 0x0800ull, // Persistent Mem writes (experimental)
		UNC_M_SB_OCCUPANCY__MASK__ICX_UNC_M_SB_OCCUPANCY__RDS = 0x0100ull, // Reads (experimental)
		UNC_M_SB_PREF_INSERTS = 0x00da, // Scoreboard Prefetch Inserts
		UNC_M_SB_PREF_INSERTS__MASK__ICX_UNC_M_SB_PREF_INSERTS__ALL = 0x0100ull, // All (experimental)
		UNC_M_SB_PREF_INSERTS__MASK__ICX_UNC_M_SB_PREF_INSERTS__DDR = 0x0200ull, // DDR4 (experimental)
		UNC_M_SB_PREF_INSERTS__MASK__ICX_UNC_M_SB_PREF_INSERTS__PMM = 0x0400ull, // Persistent Mem (experimental)
		UNC_M_SB_PREF_OCCUPANCY = 0x00db, // Scoreboard Prefetch Occupancy
		UNC_M_SB_PREF_OCCUPANCY__MASK__ICX_UNC_M_SB_PREF_OCCUPANCY__ALL = 0x0100ull, // All (experimental)
		UNC_M_SB_PREF_OCCUPANCY__MASK__ICX_UNC_M_SB_PREF_OCCUPANCY__DDR = 0x0200ull, // DDR4 (experimental)
		UNC_M_SB_PREF_OCCUPANCY__MASK__ICX_UNC_M_SB_PREF_OCCUPANCY__PMEM = 0x0400ull, // TBD (experimental)
		UNC_M_SB_PREF_OCCUPANCY__MASK__ICX_UNC_M_SB_PREF_OCCUPANCY__PMM = 0x0400ull, // Persistent Mem (experimental)
		UNC_M_SB_REJECT = 0x00d4, // Number of Scoreboard Requests Rejected
		UNC_M_SB_REJECT__MASK__ICX_UNC_M_SB_REJECT__CANARY = 0x0800ull, // TBD (experimental)
		UNC_M_SB_REJECT__MASK__ICX_UNC_M_SB_REJECT__DDR_EARLY_CMP = 0x2000ull, // TBD (experimental)
		UNC_M_SB_REJECT__MASK__ICX_UNC_M_SB_REJECT__FM_ADDR_CNFLT = 0x0200ull, // FM requests rejected due to full address conflict (experimental)
		UNC_M_SB_REJECT__MASK__ICX_UNC_M_SB_REJECT__NM_SET_CNFLT = 0x0100ull, // NM requests rejected due to set conflict (experimental)
		UNC_M_SB_REJECT__MASK__ICX_UNC_M_SB_REJECT__PATROL_SET_CNFLT = 0x0400ull, // Patrol requests rejected due to set conflict (experimental)
		UNC_M_SB_STRV_ALLOC = 0x00d7, // This event is deprecated. Refer to new event UNC_M_SB_STRV_ALLOC.NM_RD
		UNC_M_SB_STRV_ALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__FMRD = 0x0200ull, // TBD (experimental)
		UNC_M_SB_STRV_ALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__FMTGR = 0x1000ull, // TBD (experimental)
		UNC_M_SB_STRV_ALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__FMWR = 0x0800ull, // TBD (experimental)
		UNC_M_SB_STRV_ALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__FM_RD = 0x0200ull, // Far Mem Read - Set (experimental)
		UNC_M_SB_STRV_ALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__FM_TGR = 0x1000ull, // Near Mem Read - Clear (experimental)
		UNC_M_SB_STRV_ALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__FM_WR = 0x0800ull, // Far Mem Write - Set (experimental)
		UNC_M_SB_STRV_ALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__NMRD = 0x0100ull, // TBD (experimental)
		UNC_M_SB_STRV_ALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__NMWR = 0x0400ull, // TBD (experimental)
		UNC_M_SB_STRV_ALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__NM_RD = 0x0100ull, // Near Mem Read - Set (experimental)
		UNC_M_SB_STRV_ALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__NM_WR = 0x0400ull, // Near Mem Write - Set (experimental)
		UNC_M_SB_STRV_DEALLOC = 0x00de, // This event is deprecated. Refer to new event UNC_M_SB_STRV_DEALLOC.NM_RD
		UNC_M_SB_STRV_DEALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__FMRD = 0x0200ull, // TBD (experimental)
		UNC_M_SB_STRV_DEALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__FMTGR = 0x1000ull, // TBD (experimental)
		UNC_M_SB_STRV_DEALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__FMWR = 0x0800ull, // TBD (experimental)
		UNC_M_SB_STRV_DEALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__FM_RD = 0x0200ull, // Far Mem Read - Set (experimental)
		UNC_M_SB_STRV_DEALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__FM_TGR = 0x1000ull, // Near Mem Read - Clear (experimental)
		UNC_M_SB_STRV_DEALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__FM_WR = 0x0800ull, // Far Mem Write - Set (experimental)
		UNC_M_SB_STRV_DEALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__NMRD = 0x0100ull, // TBD (experimental)
		UNC_M_SB_STRV_DEALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__NMWR = 0x0400ull, // TBD (experimental)
		UNC_M_SB_STRV_DEALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__NM_RD = 0x0100ull, // Near Mem Read - Set (experimental)
		UNC_M_SB_STRV_DEALLOC__MASK__ICX_UNC_M_SB_STRV_DEALLOC__NM_WR = 0x0400ull, // Near Mem Write - Set (experimental)
		UNC_M_SB_STRV_OCC = 0x00d8, // This event is deprecated. Refer to new event UNC_M_SB_STRV_OCC.NM_RD
		UNC_M_SB_STRV_OCC__MASK__ICX_UNC_M_SB_STRV_OCC__FMRD = 0x0200ull, // TBD (experimental)
		UNC_M_SB_STRV_OCC__MASK__ICX_UNC_M_SB_STRV_OCC__FMTGR = 0x1000ull, // TBD (experimental)
		UNC_M_SB_STRV_OCC__MASK__ICX_UNC_M_SB_STRV_OCC__FMWR = 0x0800ull, // TBD (experimental)
		UNC_M_SB_STRV_OCC__MASK__ICX_UNC_M_SB_STRV_OCC__FM_RD = 0x0200ull, // Far Mem Read (experimental)
		UNC_M_SB_STRV_OCC__MASK__ICX_UNC_M_SB_STRV_OCC__FM_TGR = 0x1000ull, // Near Mem Read - Clear (experimental)
		UNC_M_SB_STRV_OCC__MASK__ICX_UNC_M_SB_STRV_OCC__FM_WR = 0x0800ull, // Far Mem Write (experimental)
		UNC_M_SB_STRV_OCC__MASK__ICX_UNC_M_SB_STRV_OCC__NMRD = 0x0100ull, // TBD (experimental)
		UNC_M_SB_STRV_OCC__MASK__ICX_UNC_M_SB_STRV_OCC__NMWR = 0x0400ull, // TBD (experimental)
		UNC_M_SB_STRV_OCC__MASK__ICX_UNC_M_SB_STRV_OCC__NM_RD = 0x0100ull, // Near Mem Read (experimental)
		UNC_M_SB_STRV_OCC__MASK__ICX_UNC_M_SB_STRV_OCC__NM_WR = 0x0400ull, // Near Mem Write (experimental)
		UNC_M_SB_TAGGED = 0x00dd, // UNC_M_SB_TAGGED.NEW
		UNC_M_SB_TAGGED__MASK__ICX_UNC_M_SB_TAGGED__DDR4_CMP = 0x0800ull, // TBD (experimental)
		UNC_M_SB_TAGGED__MASK__ICX_UNC_M_SB_TAGGED__NEW = 0x0100ull, // TBD (experimental)
		UNC_M_SB_TAGGED__MASK__ICX_UNC_M_SB_TAGGED__OCC = 0x8000ull, // TBD (experimental)
		UNC_M_SB_TAGGED__MASK__ICX_UNC_M_SB_TAGGED__PMM0_CMP = 0x1000ull, // TBD (experimental)
		UNC_M_SB_TAGGED__MASK__ICX_UNC_M_SB_TAGGED__PMM1_CMP = 0x2000ull, // TBD (experimental)
		UNC_M_SB_TAGGED__MASK__ICX_UNC_M_SB_TAGGED__PMM2_CMP = 0x4000ull, // TBD (experimental)
		UNC_M_SB_TAGGED__MASK__ICX_UNC_M_SB_TAGGED__RD_HIT = 0x0200ull, // TBD (experimental)
		UNC_M_SB_TAGGED__MASK__ICX_UNC_M_SB_TAGGED__RD_MISS = 0x0400ull, // TBD (experimental)
		UNC_M_TAGCHK = 0x00d3, // 2LM Tag Check
		UNC_M_TAGCHK__MASK__ICX_UNC_M_TAGCHK__HIT = 0x0100ull, // Hit in Near Memory Cache
		UNC_M_TAGCHK__MASK__ICX_UNC_M_TAGCHK__MISS_CLEAN = 0x0200ull, // Miss
		UNC_M_TAGCHK__MASK__ICX_UNC_M_TAGCHK__MISS_DIRTY = 0x0400ull, // Miss
		UNC_M_TAGCHK__MASK__ICX_UNC_M_TAGCHK__NM_RD_HIT = 0x0800ull, // Read Hit in Near Memory Cache
		UNC_M_TAGCHK__MASK__ICX_UNC_M_TAGCHK__NM_WR_HIT = 0x1000ull, // Write Hit in Near Memory Cache
		UNC_M_WPQ_CYCLES_FULL_PCH0 = 0x0022, // Write Pending Queue Full Cycles (experimental)
		UNC_M_WPQ_CYCLES_FULL_PCH1 = 0x0016, // Write Pending Queue Full Cycles (experimental)
		UNC_M_WPQ_CYCLES_NE = 0x0021, // Write Pending Queue Not Empty
		UNC_M_WPQ_CYCLES_NE__MASK__ICX_UNC_M_WPQ_INSERTS__PCH0 = 0x0100ull, // TBD
		UNC_M_WPQ_CYCLES_NE__MASK__ICX_UNC_M_WPQ_INSERTS__PCH1 = 0x0200ull, // TBD
		UNC_M_WPQ_INSERTS = 0x0020, // Write Pending Queue Allocations
		UNC_M_WPQ_INSERTS__MASK__ICX_UNC_M_WPQ_INSERTS__PCH0 = 0x0100ull, // TBD
		UNC_M_WPQ_INSERTS__MASK__ICX_UNC_M_WPQ_INSERTS__PCH1 = 0x0200ull, // TBD
		UNC_M_WPQ_OCCUPANCY_PCH0 = 0x0082, // Write Pending Queue Occupancy
		UNC_M_WPQ_OCCUPANCY_PCH1 = 0x0083, // Write Pending Queue Occupancy
		UNC_M_WPQ_READ_HIT = 0x0023, // Write Pending Queue CAM Match
		UNC_M_WPQ_READ_HIT__MASK__ICX_UNC_M_WPQ_WRITE_HIT__PCH0 = 0x0100ull, // TBD (experimental)
		UNC_M_WPQ_READ_HIT__MASK__ICX_UNC_M_WPQ_WRITE_HIT__PCH1 = 0x0200ull, // TBD (experimental)
		UNC_M_WPQ_WRITE_HIT = 0x0024, // Write Pending Queue CAM Match
		UNC_M_WPQ_WRITE_HIT__MASK__ICX_UNC_M_WPQ_WRITE_HIT__PCH0 = 0x0100ull, // TBD (experimental)
		UNC_M_WPQ_WRITE_HIT__MASK__ICX_UNC_M_WPQ_WRITE_HIT__PCH1 = 0x0200ull, // TBD (experimental)
		
	};
};

namespace icx_unc_imc = optkit::intel::icx_unc_imc;

#undef INTEL_X86_EDGE_BIT
#undef INTEL_X86_ANY_BIT
#undef INTEL_X86_INV_BIT
#undef INTEL_X86_CMASK_BIT
#undef INTEL_X86_MOD_EDGE
#undef INTEL_X86_MOD_ANY
#undef INTEL_X86_MOD_INV
