#pragma once
#include <cstdint>
#define INTEL_X86_EDGE_BIT	18
#define INTEL_X86_ANY_BIT	21
#define INTEL_X86_INV_BIT	23
#define INTEL_X86_CMASK_BIT 24
#define INTEL_X86_MOD_EDGE	(1 << INTEL_X86_EDGE_BIT)
#define INTEL_X86_MOD_ANY	(1 << INTEL_X86_ANY_BIT)
#define INTEL_X86_MOD_INV	(1 << INTEL_X86_INV_BIT)
namespace optkit::intel::spr_unc_cha{
	enum spr_unc_cha : uint64_t {
		UNC_CHA_BYPASS_CHA_IMC = 0x0057, // CHA to iMC Bypass
		UNC_CHA_BYPASS_CHA_IMC__MASK__SPR_UNC_CHA_BYPASS_CHA_IMC__INTERMEDIATE = 0x0200ull, // Intermediate bypass Taken (experimental)
		UNC_CHA_BYPASS_CHA_IMC__MASK__SPR_UNC_CHA_BYPASS_CHA_IMC__NOT_TAKEN = 0x0400ull, // Not Taken (experimental)
		UNC_CHA_BYPASS_CHA_IMC__MASK__SPR_UNC_CHA_BYPASS_CHA_IMC__TAKEN = 0x0100ull, // Taken (experimental)
		UNC_CHA_CLOCKTICKS = 0x0001, // Clockticks
		UNC_CHA_CMS_CLOCKTICKS = 0x00c0, // CMS Clockticks
		UNC_CHA_CORE_SNP = 0x0033, // Core Cross Snoops Issued
		UNC_CHA_CORE_SNP__MASK__SPR_UNC_CHA_CORE_SNP__ANY_GTONE = 0xf200ull, // Any Cycle with Multiple Snoops (experimental)
		UNC_CHA_CORE_SNP__MASK__SPR_UNC_CHA_CORE_SNP__ANY_ONE = 0xf100ull, // Any Single Snoop (experimental)
		UNC_CHA_CORE_SNP__MASK__SPR_UNC_CHA_CORE_SNP__CORE_GTONE = 0x4200ull, // Multiple Core Requests (experimental)
		UNC_CHA_CORE_SNP__MASK__SPR_UNC_CHA_CORE_SNP__CORE_ONE = 0x4100ull, // Single Core Requests (experimental)
		UNC_CHA_CORE_SNP__MASK__SPR_UNC_CHA_CORE_SNP__EVICT_GTONE = 0x8200ull, // Multiple Eviction (experimental)
		UNC_CHA_CORE_SNP__MASK__SPR_UNC_CHA_CORE_SNP__EVICT_ONE = 0x8100ull, // Single Eviction (experimental)
		UNC_CHA_CORE_SNP__MASK__SPR_UNC_CHA_CORE_SNP__EXT_GTONE = 0x2200ull, // Multiple External Snoops (experimental)
		UNC_CHA_CORE_SNP__MASK__SPR_UNC_CHA_CORE_SNP__EXT_ONE = 0x2100ull, // Single External Snoops (experimental)
		UNC_CHA_CORE_SNP__MASK__SPR_UNC_CHA_CORE_SNP__REMOTE_GTONE = 0x1200ull, // Multiple Snoop Targets from Remote (experimental)
		UNC_CHA_CORE_SNP__MASK__SPR_UNC_CHA_CORE_SNP__REMOTE_ONE = 0x1100ull, // Single Snoop Target from Remote (experimental)
		UNC_CHA_DIRECT_GO = 0x006e, // Direct GO
		UNC_CHA_DIRECT_GO__MASK__SPR_UNC_CHA_DIRECT_GO__HA_SUPPRESS_DRD = 0x0400ull, // Direct GO (experimental)
		UNC_CHA_DIRECT_GO__MASK__SPR_UNC_CHA_DIRECT_GO__HA_SUPPRESS_NO_D2C = 0x0200ull, // Direct GO (experimental)
		UNC_CHA_DIRECT_GO__MASK__SPR_UNC_CHA_DIRECT_GO__HA_TOR_DEALLOC = 0x0100ull, // Direct GO (experimental)
		UNC_CHA_DIRECT_GO_OPC = 0x006d, // Direct GO opcodes
		UNC_CHA_DIRECT_GO_OPC__MASK__SPR_UNC_CHA_DIRECT_GO_OPC__EXTCMP = 0x0100ull, // Direct GO (experimental)
		UNC_CHA_DIRECT_GO_OPC__MASK__SPR_UNC_CHA_DIRECT_GO_OPC__FAST_GO = 0x1000ull, // Direct GO (experimental)
		UNC_CHA_DIRECT_GO_OPC__MASK__SPR_UNC_CHA_DIRECT_GO_OPC__FAST_GO_PULL = 0x2000ull, // Direct GO (experimental)
		UNC_CHA_DIRECT_GO_OPC__MASK__SPR_UNC_CHA_DIRECT_GO_OPC__GO = 0x0400ull, // Direct GO (experimental)
		UNC_CHA_DIRECT_GO_OPC__MASK__SPR_UNC_CHA_DIRECT_GO_OPC__GO_PULL = 0x0800ull, // Direct GO (experimental)
		UNC_CHA_DIRECT_GO_OPC__MASK__SPR_UNC_CHA_DIRECT_GO_OPC__IDLE_DUE_SUPPRESS = 0x8000ull, // Direct GO (experimental)
		UNC_CHA_DIRECT_GO_OPC__MASK__SPR_UNC_CHA_DIRECT_GO_OPC__NOP = 0x4000ull, // Direct GO (experimental)
		UNC_CHA_DIRECT_GO_OPC__MASK__SPR_UNC_CHA_DIRECT_GO_OPC__PULL = 0x0200ull, // Direct GO (experimental)
		UNC_CHA_DIR_LOOKUP = 0x0053, // Multi-socket cacheline Directory state lookups
		UNC_CHA_DIR_LOOKUP__MASK__SPR_UNC_CHA_DIR_LOOKUP__NO_SNP = 0x0200ull, // Snoop Not Needed (experimental)
		UNC_CHA_DIR_LOOKUP__MASK__SPR_UNC_CHA_DIR_LOOKUP__SNP = 0x0100ull, // Snoop Needed (experimental)
		UNC_CHA_DIR_UPDATE = 0x0054, // Multi-socket cacheline Directory state updates
		UNC_CHA_DIR_UPDATE__MASK__SPR_UNC_CHA_DIR_UPDATE__HA = 0x0100ull, // Directory Updated memory write from the HA pipe
		UNC_CHA_DIR_UPDATE__MASK__SPR_UNC_CHA_DIR_UPDATE__TOR = 0x0200ull, // Directory Updated memory write from TOR pipe
		UNC_CHA_EGRESS_ORDERING = 0x00ba, // Egress Blocking due to Ordering requirements
		UNC_CHA_EGRESS_ORDERING__MASK__SPR_UNC_CHA_EGRESS_ORDERING__IV_SNOOPGO_DN = 0x0400ull, // Down (experimental)
		UNC_CHA_EGRESS_ORDERING__MASK__SPR_UNC_CHA_EGRESS_ORDERING__IV_SNOOPGO_UP = 0x0100ull, // Up (experimental)
		UNC_CHA_HITME_HIT = 0x005f, // HitMe Cache hits
		UNC_CHA_HITME_HIT__MASK__SPR_UNC_CHA_HITME_HIT__EX_RDS = 0x0100ull, // Read request from a remote socket which hit in the HitMe Cache to a line In the E state (experimental)
		UNC_CHA_HITME_HIT__MASK__SPR_UNC_CHA_HITME_HIT__SHARED_OWNREQ = 0x0400ull, // Shared hit and op is RdInvOwn
		UNC_CHA_HITME_HIT__MASK__SPR_UNC_CHA_HITME_HIT__WBMTOE = 0x0800ull, // Op is WbMtoE (experimental)
		UNC_CHA_HITME_HIT__MASK__SPR_UNC_CHA_HITME_HIT__WBMTOI_OR_S = 0x1000ull, // Op is WbMtoI
		UNC_CHA_HITME_LOOKUP = 0x005e, // HitMe Cache accesses
		UNC_CHA_HITME_LOOKUP__MASK__SPR_UNC_CHA_HITME_LOOKUP__READ = 0x0100ull, // Op is RdCode
		UNC_CHA_HITME_LOOKUP__MASK__SPR_UNC_CHA_HITME_LOOKUP__WRITE = 0x0200ull, // Op is WbMtoE
		UNC_CHA_HITME_MISS = 0x0060, // HitMe Cache misses
		UNC_CHA_HITME_MISS__MASK__SPR_UNC_CHA_HITME_MISS__NOTSHARED_RDINVOWN = 0x4000ull, // No SF/LLC HitS/F and op is RdInvOwn (experimental)
		UNC_CHA_HITME_MISS__MASK__SPR_UNC_CHA_HITME_MISS__READ_OR_INV = 0x8000ull, // Op is RdCode
		UNC_CHA_HITME_MISS__MASK__SPR_UNC_CHA_HITME_MISS__SHARED_RDINVOWN = 0x2000ull, // SF/LLC HitS/F and op is RdInvOwn (experimental)
		UNC_CHA_HITME_UPDATE = 0x0061, // HitMe Cache updates
		UNC_CHA_HITME_UPDATE__MASK__SPR_UNC_CHA_HITME_UPDATE__DEALLOCATE = 0x1000ull, // Deallocate HitME$ on Reads without RspFwdI* (experimental)
		UNC_CHA_HITME_UPDATE__MASK__SPR_UNC_CHA_HITME_UPDATE__DEALLOCATE_RSPFWDI_LOC = 0x0100ull, // op is RspIFwd or RspIFwdWb for a local request (experimental)
		UNC_CHA_HITME_UPDATE__MASK__SPR_UNC_CHA_HITME_UPDATE__RDINVOWN = 0x0800ull, // Update HitMe Cache on RdInvOwn even if not RspFwdI* (experimental)
		UNC_CHA_HITME_UPDATE__MASK__SPR_UNC_CHA_HITME_UPDATE__RSPFWDI_REM = 0x0200ull, // op is RspIFwd or RspIFwdWb for a remote request (experimental)
		UNC_CHA_HITME_UPDATE__MASK__SPR_UNC_CHA_HITME_UPDATE__SHARED = 0x0400ull, // Update HitMe Cache to SHARed (experimental)
		UNC_CHA_IMC_READS_COUNT = 0x0059, // Memory controller reads from CHA
		UNC_CHA_IMC_READS_COUNT__MASK__SPR_UNC_CHA_IMC_READS_COUNT__NORMAL = 0x0100ull, // Normal priority reads issued to the memory controller from the CHA
		UNC_CHA_IMC_READS_COUNT__MASK__SPR_UNC_CHA_IMC_READS_COUNT__PRIORITY = 0x0200ull, // ISOCH (experimental)
		UNC_CHA_IMC_WRITES_COUNT = 0x005b, // Memory controller writes from CHA
		UNC_CHA_IMC_WRITES_COUNT__MASK__SPR_UNC_CHA_IMC_WRITES_COUNT__FULL = 0x0100ull, // CHA to iMC Full Line Writes Issued; Full Line Non-ISOCH
		UNC_CHA_IMC_WRITES_COUNT__MASK__SPR_UNC_CHA_IMC_WRITES_COUNT__FULL_PRIORITY = 0x0400ull, // ISOCH Full Line (experimental)
		UNC_CHA_IMC_WRITES_COUNT__MASK__SPR_UNC_CHA_IMC_WRITES_COUNT__PARTIAL = 0x0200ull, // Partial Non-ISOCH (experimental)
		UNC_CHA_IMC_WRITES_COUNT__MASK__SPR_UNC_CHA_IMC_WRITES_COUNT__PARTIAL_PRIORITY = 0x0800ull, // ISOCH Partial (experimental)
		UNC_CHA_LLC_LOOKUP = 0x0034, // LLC Cache Lookups
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__ALL = 0x1fff0000ff00ull, // Cache and Snoop Filter Lookups; Any Request (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__ALL_REMOTE = 0x17e00000ff00ull, // All transactions from Remote Agents (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__ANY_F = 0x2000000000ull, // All Requests (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__CODE = 0x1bd00000ff00ull, // CRd Requests (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__CODE_READ_F = 0x1000000000ull, // CRd Requests (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__COREPREF_OR_DMND_LOCAL_F = 0x4000000000ull, // Local non-prefetch requests (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__DATA_RD = 0x1bc10000ff00ull, // Cache and Snoop Filter Lookups; Data Read Request (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__DATA_READ_ALL = 0x1fc10000ff00ull, // Data Reads (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__DATA_READ_F = 0x100000000ull, // Data Read Request (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__DATA_READ_LOCAL = 0x8410000ff00ull, // Demand Data Reads
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__DATA_READ_MISS = 0x1fc100000100ull, // Data Read Misses (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__E_STATE = 0x2000ull, // E State (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__F_STATE = 0x8000ull, // F State (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__FLUSH_INV = 0x1a440000ff00ull, // Flush or Invalidate Requests (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__FLUSH_OR_INV_F = 0x400000000ull, // Flush (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__I_STATE = 0x0100ull, // I State (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LLCPREF_LOCAL_F = 0x8000000000ull, // Local LLC prefetch requests (from LLC) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCALLY_HOMED_ADDRESS = 0xbdf0000ff00ull, // Transactions homed locally (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_CODE = 0x19d00000ff00ull, // CRd Requests that come from the local socket (usually the core) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_DATA_RD = 0x19c10000ff00ull, // Cache and Snoop Filter Lookups; Data Read Request that come from the local socket (usually the core) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_DMND_CODE = 0x18500000ff00ull, // Demand CRd Requests that come from the local socket (usually the core) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_DMND_DATA_RD = 0x18410000ff00ull, // Cache and Snoop Filter Lookups; Demand Data Reads that come from the local socket (usually the core) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_DMND_RFO = 0x18480000ff00ull, // Demand RFO Requests that come from the local socket (usually the core) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_F = 0x80000000000ull, // Transactions homed locally (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_FLUSH_INV = 0x18440000ff00ull, // Flush or Invalidate Requests that come from the local socket (usually the core) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_LLC_PF = 0x189d0000ff00ull, // Cache and Snoop Filter Lookups; Prefetch requests to the LLC that come from the local socket (usually the core) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_PF = 0x199d0000ff00ull, // Cache and Snoop Filter Lookups; Data Read Prefetches that come from the local socket (usually the core) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_PF_CODE = 0x19100000ff00ull, // CRd Prefetches that come from the local socket (usually the core) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_PF_DATA_RD = 0x19810000ff00ull, // Cache and Snoop Filter Lookups; Data Read Prefetches that come from the local socket (usually the core) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_PF_RFO = 0x19080000ff00ull, // RFO Prefetches that come from the local socket (usually the core) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__LOCAL_RFO = 0x19c80000ff00ull, // RFO Requests that come from the local socket (usually the core) (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__M_STATE = 0x4000ull, // M State (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__MISS_ALL = 0x1fe000000100ull, // All Misses (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__OTHER_REQ_F = 0x200000000ull, // Write Requests (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__PREF_OR_DMND_REMOTE_F = 0x20000000000ull, // Remote non-snoop requests (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__REMOTELY_HOMED_ADDRESS = 0x15df0000ff00ull, // Transactions homed remotely (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__REMOTE_CODE = 0x1a100000ff00ull, // CRd Requests that come from a Remote socket. (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__REMOTE_DATA_RD = 0x1a010000ff00ull, // Cache and Snoop Filter Lookups; Data Read Requests that come from a Remote socket (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__REMOTE_F = 0x100000000000ull, // Transactions homed remotely (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__REMOTE_FLUSH_INV = 0x1a040000ff00ull, // Flush or Invalidate requests that come from a Remote socket. (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__REMOTE_OTHER = 0x1a020000ff00ull, // Filters Requests for those that write info into the cache that come from a remote socket (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__REMOTE_RFO = 0x1a080000ff00ull, // RFO Requests that come from a Remote socket. (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__REMOTE_SNOOP_F = 0x40000000000ull, // Remote snoop requests (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__REMOTE_SNP = 0x1c190000ff00ull, // Cache and Snoop Filter Lookups; Snoop Requests from a Remote Socket (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__RFO = 0x1bc80000ff00ull, // RFO Requests (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__RFO_F = 0x800000000ull, // RFO Request Filter (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__RFO_LOCAL = 0x9c80000ff00ull, // Locally HOMed RFOs - Demand and Prefetches (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__S_STATE = 0x1000ull, // S State (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__SF_E = 0x0400ull, // SnoopFilter - E State (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__SF_H = 0x0800ull, // SnoopFilter - H State (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__SF_S = 0x0200ull, // SnoopFilter - S State (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__WRITE_LOCAL = 0x8420000ff00ull, // Writes (experimental)
		UNC_CHA_LLC_LOOKUP__MASK__SPR_UNC_CHA_LLC_LOOKUP__WRITE_REMOTE = 0x17c20000ff00ull, // Remote Writes (experimental)
		UNC_CHA_LLC_VICTIMS = 0x0037, // LLC cache victims
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__E_STATE = 0x0200ull, // Lines in E state (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__IA = 0x2000ull, // IA traffic (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__IO = 0x1000ull, // IO traffic (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__IO_E = 0x1200ull, // All LLC lines in E state that are victimized on a fill from an IO device (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__IO_FS = 0x1c00ull, // All LLC lines in F or S state that are victimized on a fill from an IO device (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__IO_M = 0x1100ull, // All LLC lines in M state that are victimized on a fill from an IO device (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__IO_MESF = 0x1f00ull, // All LLC lines in any state that are victimized on a fill from an IO device (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__LOCAL_ALL = 0x2000000f00ull, // Lines Victimized; Local - All Lines (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__LOCAL_E = 0x2000000200ull, // Lines Victimized (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__LOCAL_M = 0x2000000100ull, // Lines Victimized (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__LOCAL_ONLY = 0x2000000000ull, // Local Only (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__LOCAL_S = 0x2000000400ull, // Lines Victimized (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__M_STATE = 0x0100ull, // Lines in M state (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__REMOTE_ALL = 0x8000000f00ull, // Lines Victimized; Remote - All Lines (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__REMOTE_E = 0x8000000200ull, // Lines Victimized (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__REMOTE_M = 0x8000000100ull, // Lines Victimized (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__REMOTE_ONLY = 0x8000000000ull, // Remote Only (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__REMOTE_S = 0x8000000400ull, // Lines Victimized (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__S_STATE = 0x0400ull, // Lines in S State (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__TOTAL_E = 0x0200ull, // All LLC lines in E state that are victimized on a fill (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__TOTAL_M = 0x0100ull, // All LLC lines in M state that are victimized on a fill (experimental)
		UNC_CHA_LLC_VICTIMS__MASK__SPR_UNC_CHA_LLC_VICTIMS__TOTAL_S = 0x0400ull, // All LLC lines in S state that are victimized on a fill (experimental)
		UNC_CHA_MISC = 0x0039, // Miscellaneous
		UNC_CHA_MISC__MASK__SPR_UNC_CHA_MISC__CV0_PREF_MISS = 0x2000ull, // CV0 Prefetch Miss (experimental)
		UNC_CHA_MISC__MASK__SPR_UNC_CHA_MISC__CV0_PREF_VIC = 0x1000ull, // CV0 Prefetch Victim (experimental)
		UNC_CHA_MISC__MASK__SPR_UNC_CHA_MISC__RFO_HIT_S = 0x0800ull, // Number of times that an RFO hit in S state. (experimental)
		UNC_CHA_MISC__MASK__SPR_UNC_CHA_MISC__RSPI_WAS_FSE = 0x0100ull, // Silent Snoop Eviction (experimental)
		UNC_CHA_MISC__MASK__SPR_UNC_CHA_MISC__WC_ALIASING = 0x0200ull, // Write Combining Aliasing (experimental)
		UNC_CHA_OSB = 0x0055, // OSB
		UNC_CHA_OSB__MASK__SPR_UNC_CHA_OSB__LOCAL_INVITOE = 0x0100ull, // Local InvItoE (experimental)
		UNC_CHA_OSB__MASK__SPR_UNC_CHA_OSB__LOCAL_READ = 0x0200ull, // Local Rd (experimental)
		UNC_CHA_OSB__MASK__SPR_UNC_CHA_OSB__OFF_PWRHEURISTIC = 0x2000ull, // Off (experimental)
		UNC_CHA_OSB__MASK__SPR_UNC_CHA_OSB__REMOTE_READ = 0x0400ull, // Remote Rd (experimental)
		UNC_CHA_OSB__MASK__SPR_UNC_CHA_OSB__REMOTE_READINVITOE = 0x0800ull, // Remote Rd InvItoE (experimental)
		UNC_CHA_OSB__MASK__SPR_UNC_CHA_OSB__RFO_HITS_SNP_BCAST = 0x1000ull, // RFO HitS Snoop Broadcast (experimental)
		UNC_CHA_PMM_MEMMODE_NM_INVITOX = 0x0065, // TBD
		UNC_CHA_PMM_MEMMODE_NM_INVITOX__MASK__SPR_UNC_CHA_PMM_MEMMODE_NM_INVITOX__LOCAL = 0x0100ull, // TBD (experimental)
		UNC_CHA_PMM_MEMMODE_NM_INVITOX__MASK__SPR_UNC_CHA_PMM_MEMMODE_NM_INVITOX__REMOTE = 0x0200ull, // TBD (experimental)
		UNC_CHA_PMM_MEMMODE_NM_INVITOX__MASK__SPR_UNC_CHA_PMM_MEMMODE_NM_INVITOX__SETCONFLICT = 0x0400ull, // TBD (experimental)
		UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS = 0x0064, // Memory Modes
		UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS__MASK__SPR_UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS__LLC = 0x0200ull, // Memory Mode related events; Counts the number of times CHA saw a Near Memory set conflict in SF/LLC (experimental)
		UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS__MASK__SPR_UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS__SF = 0x0100ull, // Memory Mode related events; Counts the number of times CHA saw a Near memory set conflict in SF/LLC (experimental)
		UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS__MASK__SPR_UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS__TOR = 0x0400ull, // Memory Mode related events; Counts the number of times CHA saw a Near Memory set conflict in TOR (experimental)
		UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS2 = 0x0070, // TBD
		UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS2__MASK__SPR_UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS2__IODC = 0x0100ull, // TBD (experimental)
		UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS2__MASK__SPR_UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS2__MEMWR = 0x0200ull, // TBD (experimental)
		UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS2__MASK__SPR_UNC_CHA_PMM_MEMMODE_NM_SETCONFLICTS2__MEMWRNI = 0x0400ull, // TBD (experimental)
		UNC_CHA_PMM_QOS = 0x0066, // TBD
		UNC_CHA_PMM_QOS__MASK__SPR_UNC_CHA_PMM_QOS__DDR4_FAST_INSERT = 0x0200ull, // TBD (experimental)
		UNC_CHA_PMM_QOS__MASK__SPR_UNC_CHA_PMM_QOS__REJ_IRQ = 0x0800ull, // TBD (experimental)
		UNC_CHA_PMM_QOS__MASK__SPR_UNC_CHA_PMM_QOS__SLOWTORQ_SKIP = 0x4000ull, // TBD (experimental)
		UNC_CHA_PMM_QOS__MASK__SPR_UNC_CHA_PMM_QOS__SLOW_INSERT = 0x0100ull, // TBD (experimental)
		UNC_CHA_PMM_QOS__MASK__SPR_UNC_CHA_PMM_QOS__THROTTLE = 0x0400ull, // TBD (experimental)
		UNC_CHA_PMM_QOS__MASK__SPR_UNC_CHA_PMM_QOS__THROTTLE_IRQ = 0x2000ull, // TBD (experimental)
		UNC_CHA_PMM_QOS__MASK__SPR_UNC_CHA_PMM_QOS__THROTTLE_PRQ = 0x1000ull, // TBD (experimental)
		UNC_CHA_PMM_QOS_OCCUPANCY = 0x0067, // TBD
		UNC_CHA_PMM_QOS_OCCUPANCY__MASK__SPR_UNC_CHA_PMM_QOS_OCCUPANCY__DDR_FAST_FIFO = 0x0200ull, // TBD (experimental)
		UNC_CHA_PMM_QOS_OCCUPANCY__MASK__SPR_UNC_CHA_PMM_QOS_OCCUPANCY__DDR_SLOW_FIFO = 0x0100ull, // Number of SLOW TOR Request inserted to ha_pmm_tor_req_fifo (experimental)
		UNC_CHA_READ_NO_CREDITS = 0x0058, // CHA iMC CHNx READ Credits Empty
		UNC_CHA_READ_NO_CREDITS__MASK__SPR_UNC_CHA_WRITE_NO_CREDITS__MC0 = 0x0100ull, // TBD (experimental)
		UNC_CHA_READ_NO_CREDITS__MASK__SPR_UNC_CHA_WRITE_NO_CREDITS__MC1 = 0x0200ull, // TBD (experimental)
		UNC_CHA_READ_NO_CREDITS__MASK__SPR_UNC_CHA_WRITE_NO_CREDITS__MC2 = 0x0400ull, // TBD (experimental)
		UNC_CHA_READ_NO_CREDITS__MASK__SPR_UNC_CHA_WRITE_NO_CREDITS__MC3 = 0x0800ull, // TBD (experimental)
		UNC_CHA_READ_NO_CREDITS__MASK__SPR_UNC_CHA_WRITE_NO_CREDITS__MC4 = 0x1000ull, // TBD (experimental)
		UNC_CHA_READ_NO_CREDITS__MASK__SPR_UNC_CHA_WRITE_NO_CREDITS__MC5 = 0x2000ull, // TBD (experimental)
		UNC_CHA_REQUESTS = 0x0050, // Requests
		UNC_CHA_REQUESTS__MASK__SPR_UNC_CHA_REQUESTS__INVITOE = 0x3000ull, // Requests for exclusive ownership of a cache line without receiving data (experimental)
		UNC_CHA_REQUESTS__MASK__SPR_UNC_CHA_REQUESTS__INVITOE_LOCAL = 0x1000ull, // Local requests for exclusive ownership of a cache line  without receiving data
		UNC_CHA_REQUESTS__MASK__SPR_UNC_CHA_REQUESTS__INVITOE_REMOTE = 0x2000ull, // Remote requests for exclusive ownership of a cache line  without receiving data
		UNC_CHA_REQUESTS__MASK__SPR_UNC_CHA_REQUESTS__READS = 0x0300ull, // Read requests made into the CHA
		UNC_CHA_REQUESTS__MASK__SPR_UNC_CHA_REQUESTS__READS_LOCAL = 0x0100ull, // Read requests from a unit on this socket
		UNC_CHA_REQUESTS__MASK__SPR_UNC_CHA_REQUESTS__READS_REMOTE = 0x0200ull, // Read requests from a remote socket
		UNC_CHA_REQUESTS__MASK__SPR_UNC_CHA_REQUESTS__WRITES = 0x0c00ull, // Write requests made into the CHA
		UNC_CHA_REQUESTS__MASK__SPR_UNC_CHA_REQUESTS__WRITES_LOCAL = 0x0400ull, // Write Requests from a unit on this socket
		UNC_CHA_REQUESTS__MASK__SPR_UNC_CHA_REQUESTS__WRITES_REMOTE = 0x0800ull, // Read and Write Requests; Writes Remote
		UNC_CHA_RxC_INSERTS = 0x0013, // Ingress (from CMS) Allocations
		UNC_CHA_RxC_INSERTS__MASK__SPR_UNC_CHA_RXC_INSERTS__IPQ = 0x0400ull, // TBD (experimental)
		UNC_CHA_RxC_INSERTS__MASK__SPR_UNC_CHA_RXC_INSERTS__IRQ = 0x0100ull, // TBD (experimental)
		UNC_CHA_RxC_INSERTS__MASK__SPR_UNC_CHA_RXC_INSERTS__IRQ_REJ = 0x0200ull, // IRQ Rejected (experimental)
		UNC_CHA_RxC_INSERTS__MASK__SPR_UNC_CHA_RXC_INSERTS__PRQ = 0x1000ull, // TBD (experimental)
		UNC_CHA_RxC_INSERTS__MASK__SPR_UNC_CHA_RXC_INSERTS__PRQ_REJ = 0x2000ull, // PRQ Rejected (experimental)
		UNC_CHA_RxC_INSERTS__MASK__SPR_UNC_CHA_RXC_INSERTS__RRQ = 0x4000ull, // TBD (experimental)
		UNC_CHA_RxC_INSERTS__MASK__SPR_UNC_CHA_RXC_INSERTS__WBQ = 0x8000ull, // TBD (experimental)
		UNC_CHA_RxC_IPQ0_REJECT = 0x0022, // IPQ Requests (from CMS) Rejected - Set 0
		UNC_CHA_RxC_IPQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__AD_REQ_VN0 = 0x0100ull, // AD REQ on VN0 (experimental)
		UNC_CHA_RxC_IPQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__AD_RSP_VN0 = 0x0200ull, // AD RSP on VN0 (experimental)
		UNC_CHA_RxC_IPQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__AK_NON_UPI = 0x4000ull, // Non UPI AK Request (experimental)
		UNC_CHA_RxC_IPQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__BL_NCB_VN0 = 0x1000ull, // BL NCB on VN0 (experimental)
		UNC_CHA_RxC_IPQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__BL_NCS_VN0 = 0x2000ull, // BL NCS on VN0 (experimental)
		UNC_CHA_RxC_IPQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__BL_RSP_VN0 = 0x0400ull, // BL RSP on VN0 (experimental)
		UNC_CHA_RxC_IPQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__BL_WB_VN0 = 0x0800ull, // BL WB on VN0 (experimental)
		UNC_CHA_RxC_IPQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__IV_NON_UPI = 0x8000ull, // Non UPI IV Request (experimental)
		UNC_CHA_RxC_IPQ1_REJECT = 0x0023, // IPQ Requests (from CMS) Rejected - Set 1
		UNC_CHA_RxC_IPQ1_REJECT__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__ALLOW_SNP = 0x4000ull, // Allow Snoop (experimental)
		UNC_CHA_RxC_IPQ1_REJECT__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__ANY0 = 0x0100ull, // TBD (experimental)
		UNC_CHA_RxC_IPQ1_REJECT__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__HA = 0x0200ull, // TBD (experimental)
		UNC_CHA_RxC_IPQ1_REJECT__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__LLC_OR_SF_WAY = 0x2000ull, // TBD (experimental)
		UNC_CHA_RxC_IPQ1_REJECT__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__LLC_VICTIM = 0x0400ull, // TBD (experimental)
		UNC_CHA_RxC_IPQ1_REJECT__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__SF_VICTIM = 0x0800ull, // TBD (experimental)
		UNC_CHA_RxC_IPQ1_REJECT__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__VICTIM = 0x1000ull, // TBD (experimental)
		UNC_CHA_RxC_IRQ0_REJECT = 0x0018, // IRQ Requests (from CMS) Rejected - Set 0
		UNC_CHA_RxC_IRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__AD_REQ_VN0 = 0x0100ull, // AD REQ on VN0 (experimental)
		UNC_CHA_RxC_IRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__AD_RSP_VN0 = 0x0200ull, // AD RSP on VN0 (experimental)
		UNC_CHA_RxC_IRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__AK_NON_UPI = 0x4000ull, // Non UPI AK Request (experimental)
		UNC_CHA_RxC_IRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__BL_NCB_VN0 = 0x1000ull, // BL NCB on VN0 (experimental)
		UNC_CHA_RxC_IRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__BL_NCS_VN0 = 0x2000ull, // BL NCS on VN0 (experimental)
		UNC_CHA_RxC_IRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__BL_RSP_VN0 = 0x0400ull, // BL RSP on VN0 (experimental)
		UNC_CHA_RxC_IRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__BL_WB_VN0 = 0x0800ull, // BL WB on VN0 (experimental)
		UNC_CHA_RxC_IRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ0_REJECT__IV_NON_UPI = 0x8000ull, // Non UPI IV Request (experimental)
		UNC_CHA_RxC_IRQ1_REJECT = 0x0019, // Ingress (from CMS) Request Queue Rejects
		UNC_CHA_RxC_IRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ1_REJECT__ALLOW_SNP = 0x4000ull, // Allow Snoop (experimental)
		UNC_CHA_RxC_IRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ1_REJECT__ANY0 = 0x0100ull, // ANY0 (experimental)
		UNC_CHA_RxC_IRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ1_REJECT__HA = 0x0200ull, // HA (experimental)
		UNC_CHA_RxC_IRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ1_REJECT__LLC_OR_SF_WAY = 0x2000ull, // LLC or SF Way (experimental)
		UNC_CHA_RxC_IRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ1_REJECT__LLC_VICTIM = 0x0400ull, // LLC Victim (experimental)
		UNC_CHA_RxC_IRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ1_REJECT__PA_MATCH = 0x8000ull, // Ingress (from CMS) Request Queue Rejects; PhyAddr Match (experimental)
		UNC_CHA_RxC_IRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ1_REJECT__SF_VICTIM = 0x0800ull, // SF Victim (experimental)
		UNC_CHA_RxC_IRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_IRQ1_REJECT__VICTIM = 0x1000ull, // Victim (experimental)
		UNC_CHA_RxC_ISMQ0_REJECT = 0x0024, // ISMQ Rejects - Set 0
		UNC_CHA_RxC_ISMQ0_REJECT__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__AD_REQ_VN0 = 0x0100ull, // AD REQ on VN0 (experimental)
		UNC_CHA_RxC_ISMQ0_REJECT__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__AD_RSP_VN0 = 0x0200ull, // AD RSP on VN0 (experimental)
		UNC_CHA_RxC_ISMQ0_REJECT__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__AK_NON_UPI = 0x4000ull, // Non UPI AK Request (experimental)
		UNC_CHA_RxC_ISMQ0_REJECT__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__BL_NCB_VN0 = 0x1000ull, // BL NCB on VN0 (experimental)
		UNC_CHA_RxC_ISMQ0_REJECT__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__BL_NCS_VN0 = 0x2000ull, // BL NCS on VN0 (experimental)
		UNC_CHA_RxC_ISMQ0_REJECT__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__BL_RSP_VN0 = 0x0400ull, // BL RSP on VN0 (experimental)
		UNC_CHA_RxC_ISMQ0_REJECT__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__BL_WB_VN0 = 0x0800ull, // BL WB on VN0 (experimental)
		UNC_CHA_RxC_ISMQ0_REJECT__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__IV_NON_UPI = 0x8000ull, // Non UPI IV Request (experimental)
		UNC_CHA_RxC_ISMQ0_RETRY = 0x002c, // ISMQ Retries - Set 0
		UNC_CHA_RxC_ISMQ0_RETRY__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__AD_REQ_VN0 = 0x0100ull, // AD REQ on VN0 (experimental)
		UNC_CHA_RxC_ISMQ0_RETRY__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__AD_RSP_VN0 = 0x0200ull, // AD RSP on VN0 (experimental)
		UNC_CHA_RxC_ISMQ0_RETRY__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__AK_NON_UPI = 0x4000ull, // Non UPI AK Request (experimental)
		UNC_CHA_RxC_ISMQ0_RETRY__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__BL_NCB_VN0 = 0x1000ull, // BL NCB on VN0 (experimental)
		UNC_CHA_RxC_ISMQ0_RETRY__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__BL_NCS_VN0 = 0x2000ull, // BL NCS on VN0 (experimental)
		UNC_CHA_RxC_ISMQ0_RETRY__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__BL_RSP_VN0 = 0x0400ull, // BL RSP on VN0 (experimental)
		UNC_CHA_RxC_ISMQ0_RETRY__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__BL_WB_VN0 = 0x0800ull, // BL WB on VN0 (experimental)
		UNC_CHA_RxC_ISMQ0_RETRY__MASK__SPR_UNC_CHA_RXC_ISMQ0_RETRY__IV_NON_UPI = 0x8000ull, // Non UPI IV Request (experimental)
		UNC_CHA_RxC_ISMQ1_REJECT = 0x0025, // ISMQ Rejects - Set 1
		UNC_CHA_RxC_ISMQ1_REJECT__MASK__SPR_UNC_CHA_RXC_ISMQ1_RETRY__ANY0 = 0x0100ull, // TBD (experimental)
		UNC_CHA_RxC_ISMQ1_REJECT__MASK__SPR_UNC_CHA_RXC_ISMQ1_RETRY__HA = 0x0200ull, // TBD (experimental)
		UNC_CHA_RxC_ISMQ1_RETRY = 0x002d, // ISMQ Retries - Set 1
		UNC_CHA_RxC_ISMQ1_RETRY__MASK__SPR_UNC_CHA_RXC_ISMQ1_RETRY__ANY0 = 0x0100ull, // TBD (experimental)
		UNC_CHA_RxC_ISMQ1_RETRY__MASK__SPR_UNC_CHA_RXC_ISMQ1_RETRY__HA = 0x0200ull, // TBD (experimental)
		UNC_CHA_RxC_OCCUPANCY = 0x0011, // Ingress (from CMS) Occupancy
		UNC_CHA_RxC_OCCUPANCY__MASK__SPR_UNC_CHA_RXC_OCCUPANCY__IPQ = 0x0400ull, // TBD (experimental)
		UNC_CHA_RxC_OCCUPANCY__MASK__SPR_UNC_CHA_RXC_OCCUPANCY__RRQ = 0x4000ull, // TBD (experimental)
		UNC_CHA_RxC_OCCUPANCY__MASK__SPR_UNC_CHA_RXC_OCCUPANCY__WBQ = 0x8000ull, // TBD (experimental)
		UNC_CHA_RxC_OTHER0_RETRY = 0x002e, // Other Retries - Set 0
		UNC_CHA_RxC_OTHER0_RETRY__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__AD_REQ_VN0 = 0x0100ull, // AD REQ on VN0 (experimental)
		UNC_CHA_RxC_OTHER0_RETRY__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__AD_RSP_VN0 = 0x0200ull, // AD RSP on VN0 (experimental)
		UNC_CHA_RxC_OTHER0_RETRY__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__AK_NON_UPI = 0x4000ull, // Non UPI AK Request (experimental)
		UNC_CHA_RxC_OTHER0_RETRY__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__BL_NCB_VN0 = 0x1000ull, // BL NCB on VN0 (experimental)
		UNC_CHA_RxC_OTHER0_RETRY__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__BL_NCS_VN0 = 0x2000ull, // BL NCS on VN0 (experimental)
		UNC_CHA_RxC_OTHER0_RETRY__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__BL_RSP_VN0 = 0x0400ull, // BL RSP on VN0 (experimental)
		UNC_CHA_RxC_OTHER0_RETRY__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__BL_WB_VN0 = 0x0800ull, // BL WB on VN0 (experimental)
		UNC_CHA_RxC_OTHER0_RETRY__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__IV_NON_UPI = 0x8000ull, // Non UPI IV Request (experimental)
		UNC_CHA_RxC_OTHER1_RETRY = 0x002f, // Other Retries - Set 1
		UNC_CHA_RxC_OTHER1_RETRY__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__ALLOW_SNP = 0x4000ull, // Allow Snoop (experimental)
		UNC_CHA_RxC_OTHER1_RETRY__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__ANY0 = 0x0100ull, // TBD (experimental)
		UNC_CHA_RxC_OTHER1_RETRY__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__HA = 0x0200ull, // TBD (experimental)
		UNC_CHA_RxC_OTHER1_RETRY__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__LLC_OR_SF_WAY = 0x2000ull, // TBD (experimental)
		UNC_CHA_RxC_OTHER1_RETRY__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__LLC_VICTIM = 0x0400ull, // TBD (experimental)
		UNC_CHA_RxC_OTHER1_RETRY__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__SF_VICTIM = 0x0800ull, // TBD (experimental)
		UNC_CHA_RxC_OTHER1_RETRY__MASK__SPR_UNC_CHA_RXC_OTHER1_RETRY__VICTIM = 0x1000ull, // TBD (experimental)
		UNC_CHA_RxC_PRQ0_REJECT = 0x0020, // PRQ Requests (from CMS) Rejected - Set 0
		UNC_CHA_RxC_PRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__AD_REQ_VN0 = 0x0100ull, // AD REQ on VN0 (experimental)
		UNC_CHA_RxC_PRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__AD_RSP_VN0 = 0x0200ull, // AD RSP on VN0 (experimental)
		UNC_CHA_RxC_PRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__AK_NON_UPI = 0x4000ull, // Non UPI AK Request (experimental)
		UNC_CHA_RxC_PRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__BL_NCB_VN0 = 0x1000ull, // BL NCB on VN0 (experimental)
		UNC_CHA_RxC_PRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__BL_NCS_VN0 = 0x2000ull, // BL NCS on VN0 (experimental)
		UNC_CHA_RxC_PRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__BL_RSP_VN0 = 0x0400ull, // BL RSP on VN0 (experimental)
		UNC_CHA_RxC_PRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__BL_WB_VN0 = 0x0800ull, // BL WB on VN0 (experimental)
		UNC_CHA_RxC_PRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_PRQ0_REJECT__IV_NON_UPI = 0x8000ull, // Non UPI IV Request (experimental)
		UNC_CHA_RxC_PRQ1_REJECT = 0x0021, // PRQ Requests (from CMS) Rejected - Set 1
		UNC_CHA_RxC_PRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__ALLOW_SNP = 0x4000ull, // Allow Snoop (experimental)
		UNC_CHA_RxC_PRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__ANY0 = 0x0100ull, // ANY0 (experimental)
		UNC_CHA_RxC_PRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__HA = 0x0200ull, // HA (experimental)
		UNC_CHA_RxC_PRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__LLC_OR_SF_WAY = 0x2000ull, // LLC OR SF Way (experimental)
		UNC_CHA_RxC_PRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__LLC_VICTIM = 0x0400ull, // LLC Victim (experimental)
		UNC_CHA_RxC_PRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__SF_VICTIM = 0x0800ull, // SF Victim (experimental)
		UNC_CHA_RxC_PRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__VICTIM = 0x1000ull, // Victim (experimental)
		UNC_CHA_RxC_REQ_Q0_RETRY = 0x002a, // Request Queue Retries - Set 0
		UNC_CHA_RxC_REQ_Q0_RETRY__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__AD_REQ_VN0 = 0x0100ull, // AD REQ on VN0 (experimental)
		UNC_CHA_RxC_REQ_Q0_RETRY__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__AD_RSP_VN0 = 0x0200ull, // AD RSP on VN0 (experimental)
		UNC_CHA_RxC_REQ_Q0_RETRY__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__AK_NON_UPI = 0x4000ull, // Non UPI AK Request (experimental)
		UNC_CHA_RxC_REQ_Q0_RETRY__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__BL_NCB_VN0 = 0x1000ull, // BL NCB on VN0 (experimental)
		UNC_CHA_RxC_REQ_Q0_RETRY__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__BL_NCS_VN0 = 0x2000ull, // BL NCS on VN0 (experimental)
		UNC_CHA_RxC_REQ_Q0_RETRY__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__BL_RSP_VN0 = 0x0400ull, // BL RSP on VN0 (experimental)
		UNC_CHA_RxC_REQ_Q0_RETRY__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__BL_WB_VN0 = 0x0800ull, // BL WB on VN0 (experimental)
		UNC_CHA_RxC_REQ_Q0_RETRY__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__IV_NON_UPI = 0x8000ull, // Non UPI IV Request (experimental)
		UNC_CHA_RxC_REQ_Q1_RETRY = 0x002b, // Request Queue Retries - Set 1
		UNC_CHA_RxC_REQ_Q1_RETRY__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__ALLOW_SNP = 0x4000ull, // Allow Snoop (experimental)
		UNC_CHA_RxC_REQ_Q1_RETRY__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__ANY0 = 0x0100ull, // ANY0 (experimental)
		UNC_CHA_RxC_REQ_Q1_RETRY__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__HA = 0x0200ull, // HA (experimental)
		UNC_CHA_RxC_REQ_Q1_RETRY__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__LLC_OR_SF_WAY = 0x2000ull, // LLC OR SF Way (experimental)
		UNC_CHA_RxC_REQ_Q1_RETRY__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__LLC_VICTIM = 0x0400ull, // LLC Victim (experimental)
		UNC_CHA_RxC_REQ_Q1_RETRY__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__SF_VICTIM = 0x0800ull, // SF Victim (experimental)
		UNC_CHA_RxC_REQ_Q1_RETRY__MASK__SPR_UNC_CHA_RXC_REQ_Q1_RETRY__VICTIM = 0x1000ull, // Victim (experimental)
		UNC_CHA_RxC_RRQ0_REJECT = 0x0026, // RRQ Rejects - Set 0
		UNC_CHA_RxC_RRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__AD_REQ_VN0 = 0x0100ull, // AD REQ on VN0 (experimental)
		UNC_CHA_RxC_RRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__AD_RSP_VN0 = 0x0200ull, // AD RSP on VN0 (experimental)
		UNC_CHA_RxC_RRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__AK_NON_UPI = 0x4000ull, // Non UPI AK Request (experimental)
		UNC_CHA_RxC_RRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__BL_NCB_VN0 = 0x1000ull, // BL NCB on VN0 (experimental)
		UNC_CHA_RxC_RRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__BL_NCS_VN0 = 0x2000ull, // BL NCS on VN0 (experimental)
		UNC_CHA_RxC_RRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__BL_RSP_VN0 = 0x0400ull, // BL RSP on VN0 (experimental)
		UNC_CHA_RxC_RRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__BL_WB_VN0 = 0x0800ull, // BL WB on VN0 (experimental)
		UNC_CHA_RxC_RRQ0_REJECT__MASK__SPR_UNC_CHA_RXC_RRQ0_REJECT__IV_NON_UPI = 0x8000ull, // Non UPI IV Request (experimental)
		UNC_CHA_RxC_RRQ1_REJECT = 0x0027, // RRQ Rejects - Set 1
		UNC_CHA_RxC_RRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__ALLOW_SNP = 0x4000ull, // Allow Snoop (experimental)
		UNC_CHA_RxC_RRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__ANY0 = 0x0100ull, // TBD (experimental)
		UNC_CHA_RxC_RRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__HA = 0x0200ull, // TBD (experimental)
		UNC_CHA_RxC_RRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__LLC_OR_SF_WAY = 0x2000ull, // TBD (experimental)
		UNC_CHA_RxC_RRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__LLC_VICTIM = 0x0400ull, // TBD (experimental)
		UNC_CHA_RxC_RRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__SF_VICTIM = 0x0800ull, // TBD (experimental)
		UNC_CHA_RxC_RRQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__VICTIM = 0x1000ull, // TBD (experimental)
		UNC_CHA_RxC_WBQ0_REJECT = 0x0028, // WBQ Rejects - Set 0
		UNC_CHA_RxC_WBQ0_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ0_REJECT__AD_REQ_VN0 = 0x0100ull, // AD REQ on VN0 (experimental)
		UNC_CHA_RxC_WBQ0_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ0_REJECT__AD_RSP_VN0 = 0x0200ull, // AD RSP on VN0 (experimental)
		UNC_CHA_RxC_WBQ0_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ0_REJECT__AK_NON_UPI = 0x4000ull, // Non UPI AK Request (experimental)
		UNC_CHA_RxC_WBQ0_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ0_REJECT__BL_NCB_VN0 = 0x1000ull, // BL NCB on VN0 (experimental)
		UNC_CHA_RxC_WBQ0_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ0_REJECT__BL_NCS_VN0 = 0x2000ull, // BL NCS on VN0 (experimental)
		UNC_CHA_RxC_WBQ0_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ0_REJECT__BL_RSP_VN0 = 0x0400ull, // BL RSP on VN0 (experimental)
		UNC_CHA_RxC_WBQ0_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ0_REJECT__BL_WB_VN0 = 0x0800ull, // BL WB on VN0 (experimental)
		UNC_CHA_RxC_WBQ0_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ0_REJECT__IV_NON_UPI = 0x8000ull, // Non UPI IV Request (experimental)
		UNC_CHA_RxC_WBQ1_REJECT = 0x0029, // WBQ Rejects - Set 1
		UNC_CHA_RxC_WBQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__ALLOW_SNP = 0x4000ull, // Allow Snoop (experimental)
		UNC_CHA_RxC_WBQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__ANY0 = 0x0100ull, // TBD (experimental)
		UNC_CHA_RxC_WBQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__HA = 0x0200ull, // TBD (experimental)
		UNC_CHA_RxC_WBQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__LLC_OR_SF_WAY = 0x2000ull, // TBD (experimental)
		UNC_CHA_RxC_WBQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__LLC_VICTIM = 0x0400ull, // TBD (experimental)
		UNC_CHA_RxC_WBQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__SF_VICTIM = 0x0800ull, // TBD (experimental)
		UNC_CHA_RxC_WBQ1_REJECT__MASK__SPR_UNC_CHA_RXC_WBQ1_REJECT__VICTIM = 0x1000ull, // TBD (experimental)
		UNC_CHA_SNOOPS_SENT = 0x0051, // Snoops Sent
		UNC_CHA_SNOOPS_SENT__MASK__SPR_UNC_CHA_SNOOPS_SENT__ALL = 0x0100ull, // All (experimental)
		UNC_CHA_SNOOPS_SENT__MASK__SPR_UNC_CHA_SNOOPS_SENT__BCST_LOCAL = 0x1000ull, // Broadcast snoop for Local Requests (experimental)
		UNC_CHA_SNOOPS_SENT__MASK__SPR_UNC_CHA_SNOOPS_SENT__BCST_REMOTE = 0x2000ull, // Broadcast snoops for Remote Requests (experimental)
		UNC_CHA_SNOOPS_SENT__MASK__SPR_UNC_CHA_SNOOPS_SENT__DIRECT_LOCAL = 0x4000ull, // Directed snoops for Local Requests (experimental)
		UNC_CHA_SNOOPS_SENT__MASK__SPR_UNC_CHA_SNOOPS_SENT__DIRECT_REMOTE = 0x8000ull, // Directed snoops for Remote Requests (experimental)
		UNC_CHA_SNOOPS_SENT__MASK__SPR_UNC_CHA_SNOOPS_SENT__LOCAL = 0x0400ull, // Broadcast or directed Snoops sent for Local Requests (experimental)
		UNC_CHA_SNOOPS_SENT__MASK__SPR_UNC_CHA_SNOOPS_SENT__REMOTE = 0x0800ull, // Broadcast or directed Snoops sent for Remote Requests (experimental)
		UNC_CHA_SNOOP_RESP = 0x005c, // Snoop Responses Received
		UNC_CHA_SNOOP_RESP__MASK__SPR_UNC_CHA_SNOOP_RESP__RSPCNFLCT = 0x4000ull, // TBD (experimental)
		UNC_CHA_SNOOP_RESP__MASK__SPR_UNC_CHA_SNOOP_RESP__RSPFWD = 0x8000ull, // TBD (experimental)
		UNC_CHA_SNOOP_RESP__MASK__SPR_UNC_CHA_SNOOP_RESP__RSPFWDWB = 0x2000ull, // TBD (experimental)
		UNC_CHA_SNOOP_RESP__MASK__SPR_UNC_CHA_SNOOP_RESP__RSPI = 0x0100ull, // RspI Snoop Responses Received (experimental)
		UNC_CHA_SNOOP_RESP__MASK__SPR_UNC_CHA_SNOOP_RESP__RSPIFWD = 0x0400ull, // RspIFwd Snoop Responses Received (experimental)
		UNC_CHA_SNOOP_RESP__MASK__SPR_UNC_CHA_SNOOP_RESP__RSPS = 0x0200ull, // RspS Snoop Responses Received (experimental)
		UNC_CHA_SNOOP_RESP__MASK__SPR_UNC_CHA_SNOOP_RESP__RSPSFWD = 0x0800ull, // RspSFwd Snoop Responses Received (experimental)
		UNC_CHA_SNOOP_RESP__MASK__SPR_UNC_CHA_SNOOP_RESP__RSPWB = 0x1000ull, // TBD (experimental)
		UNC_CHA_SNOOP_RESP_LOCAL = 0x005d, // Snoop Responses Received Local
		UNC_CHA_SNOOP_RESP_LOCAL__MASK__SPR_UNC_CHA_SNOOP_RESP_LOCAL__RSPCNFLCT = 0x4000ull, // TBD (experimental)
		UNC_CHA_SNOOP_RESP_LOCAL__MASK__SPR_UNC_CHA_SNOOP_RESP_LOCAL__RSPFWD = 0x8000ull, // TBD (experimental)
		UNC_CHA_SNOOP_RESP_LOCAL__MASK__SPR_UNC_CHA_SNOOP_RESP_LOCAL__RSPFWDWB = 0x2000ull, // TBD (experimental)
		UNC_CHA_SNOOP_RESP_LOCAL__MASK__SPR_UNC_CHA_SNOOP_RESP_LOCAL__RSPI = 0x0100ull, // TBD (experimental)
		UNC_CHA_SNOOP_RESP_LOCAL__MASK__SPR_UNC_CHA_SNOOP_RESP_LOCAL__RSPIFWD = 0x0400ull, // TBD (experimental)
		UNC_CHA_SNOOP_RESP_LOCAL__MASK__SPR_UNC_CHA_SNOOP_RESP_LOCAL__RSPS = 0x0200ull, // TBD (experimental)
		UNC_CHA_SNOOP_RESP_LOCAL__MASK__SPR_UNC_CHA_SNOOP_RESP_LOCAL__RSPSFWD = 0x0800ull, // TBD (experimental)
		UNC_CHA_SNOOP_RESP_LOCAL__MASK__SPR_UNC_CHA_SNOOP_RESP_LOCAL__RSPWB = 0x1000ull, // TBD (experimental)
		UNC_CHA_SNOOP_RSP_MISC = 0x006b, // Misc Snoop Responses Received
		UNC_CHA_SNOOP_RSP_MISC__MASK__SPR_UNC_CHA_SNOOP_RSP_MISC__MTOI_RSPDATAM = 0x0200ull, // TBD (experimental)
		UNC_CHA_SNOOP_RSP_MISC__MASK__SPR_UNC_CHA_SNOOP_RSP_MISC__MTOI_RSPIFWDM = 0x0100ull, // TBD (experimental)
		UNC_CHA_SNOOP_RSP_MISC__MASK__SPR_UNC_CHA_SNOOP_RSP_MISC__PULLDATAPTL_HITLLC = 0x2000ull, // Pull Data Partial - Hit LLC (experimental)
		UNC_CHA_SNOOP_RSP_MISC__MASK__SPR_UNC_CHA_SNOOP_RSP_MISC__PULLDATAPTL_HITSF = 0x1000ull, // Pull Data Partial - Hit SF (experimental)
		UNC_CHA_SNOOP_RSP_MISC__MASK__SPR_UNC_CHA_SNOOP_RSP_MISC__RSPIFWDMPTL_HITLLC = 0x0800ull, // TBD (experimental)
		UNC_CHA_SNOOP_RSP_MISC__MASK__SPR_UNC_CHA_SNOOP_RSP_MISC__RSPIFWDMPTL_HITSF = 0x0400ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS = 0x0035, // TOR Inserts
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__ALL = 0xc001ff0000ff00ull, // All (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__DDR = 0x400000000ull, // DDR Access (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__EVICT = 0x0200ull, // SF/LLC Evictions (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__HIT = 0x100000000ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA = 0xc001ff00000100ull, // All from Local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_CLFLUSH = 0xc8c7ff00000100ull, // CLFlush from Local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_CLFLUSHOPT = 0xc8d7ff00000100ull, // CLFlushOpt from Local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_CRD = 0xc80fff00000100ull, // CRd from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_CRD_PREF = 0xc88fff00000100ull, // Rd Pref from local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_DRD = 0xc817ff00000100ull, // Rd from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_DRDPTE = 0xc837ff00000100ull, // DRd PTEs issued by iA Cores (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_DRD_OPT = 0xc827ff00000100ull, // DRd Opt from local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_DRD_OPT_PREF = 0xc8a7ff00000100ull, // DRd Opt Pref from local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_DRD_PREF = 0xc897ff00000100ull, // DRd Pref from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT = 0xc001fd00000100ull, // Hits from Local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_CRD = 0xc80ffd00000100ull, // CRd hits from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_CRD_PREF = 0xc88ffd00000100ull, // CRd Pref hits from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_CXL_ACC = 0x10c0018100000100ull, // All requests issued from IA cores to CXL accelerator memory regions that hit the LLC. (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_CXL_ACC_LOCAL = 0x10c0008100000100ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_DRD = 0xc817fd00000100ull, // DRd hits from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_DRDPTE = 0xc837fd00000100ull, // DRd PTEs issued by iA Cores that Hit the LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_DRD_OPT = 0xc827fd00000100ull, // DRd Opt hits from local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_DRD_OPT_PREF = 0xc8a7fd00000100ull, // DRd Opt Pref hits from local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_DRD_PREF = 0xc897fd00000100ull, // DRd Pref hits from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_ITOM = 0xcc47fd00000100ull, // ItoMs issued by iA Cores that Hit LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_LLCPREFCODE = 0xcccffd00000100ull, // LLCPrefCode hits from local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_LLCPREFDATA = 0xccd7fd00000100ull, // LLCPrefData hits from local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_LLCPREFRFO = 0xccc7fd00000100ull, // LLCPrefRFO hits from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_RFO = 0xc807fd00000100ull, // RFO hits from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_RFO_PREF = 0xc887fd00000100ull, // RFO Pref hits from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_ITOM = 0xcc47ff00000100ull, // ItoM from Local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_ITOMCACHENEAR = 0xcd47ff00000100ull, // ItoMCacheNears issued by iA Cores (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_LLCPREFCODE = 0xcccfff00000100ull, // LLCPrefCode from local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_LLCPREFDATA = 0xccd7ff00000100ull, // LLCPrefData from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_LLCPREFRFO = 0xccc7ff00000100ull, // LLCPrefRFO from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS = 0xc001fe00000100ull, // misses from Local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRD = 0xc80ffe00000100ull, // CRd misses from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRDMORPH_CXL_ACC = 0x10c80b8200000100ull, // CRds and equivalent opcodes issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRD_LOCAL = 0xc80efe00000100ull, // CRd issued by iA Cores that Missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRD_PREF = 0xc88ffe00000100ull, // CRd Pref misses from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRD_PREF_LOCAL = 0xc88efe00000100ull, // CRd_Prefs issued by iA Cores that Missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRD_PREF_REMOTE = 0xc88f7e00000100ull, // CRd_Prefs issued by iA Cores that Missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRD_REMOTE = 0xc80f7e00000100ull, // CRd issued by iA Cores that Missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CXL_ACC = 0x10c0018200000100ull, // All requests issued from IA cores to CXL accelerator memory regions that miss the LLC. (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CXL_ACC_LOCAL = 0x10c0008200000100ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD = 0xc817fe00000100ull, // DRd misses from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRDMORPH_CXL_ACC = 0x10c8138200000100ull, // DRds and equivalent opcodes issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRDPTE = 0xc837fe00000100ull, // DRd PTEs issued by iA Cores that Missed the LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_CXL_ACC = 0x10c8178200000100ull, // DRds issued from an IA core which miss the L3 and target memory in a CXL type 2 memory expander card. (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_CXL_ACC_LOCAL = 0x10c8168200000100ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_DDR = 0xc8178600000100ull, // DRds issued by IA Cores targeting DDR Mem that Missed the LLC
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_LOCAL = 0xc816fe00000100ull, // DRd misses from local IA targeting local memory
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_LOCAL_DDR = 0xc8168600000100ull, // DRds issued by iA Cores targeting DDR Mem that Missed the LLC - HOMed locally
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_LOCAL_PMM = 0xc8168a00000100ull, // DRds issued by iA Cores targeting PMM Mem that Missed the LLC - HOMed locally
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_OPT = 0xc827fe00000100ull, // DRd Opt misses from local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_OPT_CXL_ACC_LOCAL = 0x10c8268200000100ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_OPT_PREF = 0xc8a7fe00000100ull, // DRd Opt Pref misses from local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_OPT_PREF_CXL_ACC_LOCAL = 0x10c8a68200000100ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PMM = 0xc8178a00000100ull, // DRds issued by iA Cores targeting PMM Mem that Missed the LLC
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF = 0xc897fe00000100ull, // DRd Pref misses from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_CXL_ACC = 0x10c8978200000100ull, // L2 data prefetches issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_CXL_ACC_LOCAL = 0x10c8968200000100ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_DDR = 0xc8978600000100ull, // DRd_Prefs issued by iA Cores targeting DDR Mem that Missed the LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_LOCAL = 0xc896fe00000100ull, // DRd Pref misses from local IA targeting local memory
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_LOCAL_DDR = 0xc8968600000100ull, // DRd_Prefs issued by iA Cores targeting DDR Mem that Missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_LOCAL_PMM = 0xc8968a00000100ull, // DRd_Prefs issued by iA Cores targeting PMM Mem that Missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_PMM = 0xc8978a00000100ull, // DRd_Prefs issued by iA Cores targeting PMM Mem that Missed the LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_REMOTE = 0xc8977e00000100ull, // DRd Pref misses from local IA targeting remote memory
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_REMOTE_DDR = 0xc8970600000100ull, // DRd_Prefs issued by iA Cores targeting DDR Mem that Missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_REMOTE_PMM = 0xc8970a00000100ull, // DRd_Prefs issued by iA Cores targeting PMM Mem that Missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_REMOTE = 0xc8177e00000100ull, // DRd misses from local IA targeting remote memory
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_REMOTE_DDR = 0xc8170600000100ull, // DRds issued by iA Cores targeting DDR Mem that Missed the LLC - HOMed remotely
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_REMOTE_PMM = 0xc8170a00000100ull, // DRds issued by iA Cores targeting PMM Mem that Missed the LLC - HOMed remotely
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_ITOM = 0xcc47fe00000100ull, // ItoMs issued by iA Cores that Missed LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFCODE = 0xcccffe00000100ull, // LLCPrefCode misses from local IA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFCODE_CXL_ACC = 0x10cccf8200000100ull, // LLC Prefetch Code transactions issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFDATA = 0xccd7fe00000100ull, // LLCPrefData misses from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFDATA_CXL_ACC = 0x10ccd78200000100ull, // LLC data prefetches issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFDATA_CXL_ACC_LOCAL = 0x10ccd68200000100ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFRFO = 0xccc7fe00000100ull, // LLCPrefRFO misses from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFRFO_CXL_ACC = 0x10c8878200000100ull, // L2 RFO prefetches issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFRFO_CXL_ACC_LOCAL = 0x10c8868200000100ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LOCAL_WCILF_DDR = 0xc8668600000100ull, // WCiLFs issued by iA Cores targeting DDR that missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LOCAL_WCILF_PMM = 0xc8668a00000100ull, // WCiLFs issued by iA Cores targeting PMM that missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LOCAL_WCIL_DDR = 0xc86e8600000100ull, // WCiLs issued by iA Cores targeting DDR that missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LOCAL_WCIL_PMM = 0xc86e8a00000100ull, // WCiLs issued by iA Cores targeting PMM that missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_REMOTE_WCILF_DDR = 0xc8670600000100ull, // WCiLFs issued by iA Cores targeting DDR that missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_REMOTE_WCILF_PMM = 0xc8670a00000100ull, // WCiLFs issued by iA Cores targeting PMM that missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_REMOTE_WCIL_DDR = 0xc86f0600000100ull, // WCiLs issued by iA Cores targeting DDR that missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_REMOTE_WCIL_PMM = 0xc86f0a00000100ull, // WCiLs issued by iA Cores targeting PMM that missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO = 0xc807fe00000100ull, // RFO misses from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFOMORPH_CXL_ACC = 0x10c8038200000100ull, // RFO and L2 RFO prefetches issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_CXL_ACC = 0x10c8078200000100ull, // RFOs issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_CXL_ACC_LOCAL = 0x10c8068200000100ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_LOCAL = 0xc806fe00000100ull, // RFO misses from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_PREF = 0xc887fe00000100ull, // RFO pref misses from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_PREF_CXL_ACC = 0x10ccc78200000100ull, // LLC RFO prefetches issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_PREF_CXL_ACC_LOCAL = 0x10ccc68200000100ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_PREF_LOCAL = 0xc886fe00000100ull, // RFO prefetch misses from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_PREF_REMOTE = 0xc8877e00000100ull, // RFO prefetch misses from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_REMOTE = 0xc8077e00000100ull, // RFO misses from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_UCRDF = 0xc877de00000100ull, // UCRdFs issued by iA Cores that Missed LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WCIL = 0xc86ffe00000100ull, // WCiLs issued by iA Cores that Missed the LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WCILF = 0xc867fe00000100ull, // WCiLF issued by iA Cores that Missed the LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WCILF_DDR = 0xc8678600000100ull, // WCiLFs issued by iA Cores targeting DDR that missed the LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WCILF_PMM = 0xc8678a00000100ull, // WCiLFs issued by iA Cores targeting PMM that missed the LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WCIL_DDR = 0xc86f8600000100ull, // WCiLs issued by iA Cores targeting DDR that missed the LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WCIL_PMM = 0xc86f8a00000100ull, // WCiLs issued by iA Cores targeting PMM that missed the LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WIL = 0xc87fde00000100ull, // WiLs issued by iA Cores that Missed LLC (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_RFO = 0xc807ff00000100ull, // RFO from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_RFO_PREF = 0xc887ff00000100ull, // RFO pref from local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_SPECITOM = 0xcc57ff00000100ull, // SpecItoM from Local IA
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WBEFTOE = 0xcc3fff00000100ull, // WBEFtoEs issued by an IA Core.  Non Modified Write Backs (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WBEFTOI = 0xcc37ff00000100ull, // WBEFtoEs issued by an IA Core.  Non Modified Write Backs (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WBMTOE = 0xcc2fff00000100ull, // WBEFtoEs issued by an IA Core.  Non Modified Write Backs (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WBMTOI = 0xcc27ff00000100ull, // WbMtoIs issued by an iA Cores. Modified Write Backs (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WBSTOI = 0xcc67ff00000100ull, // WBEFtoEs issued by an IA Core.  Non Modified Write Backs (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WCIL = 0xc86fff00000100ull, // WCiLs issued by iA Cores (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WCILF = 0xc867ff00000100ull, // WCiLF issued by iA Cores (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO = 0xc001ff00000400ull, // All from local IO
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_CLFLUSH = 0xc8c3ff00000400ull, // CLFlushes issued by IO Devices
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_HIT = 0xc001fd00000400ull, // Hits from local IO
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_HIT_ITOM = 0xcc43fd00000400ull, // ItoM hits from local IO
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_HIT_ITOMCACHENEAR = 0xcd43fd00000400ull, // ItoMCacheNears
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_HIT_PCIRDCUR = 0xc8f3fd00000400ull, // RdCur and FsRdCur hits from local IO
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_HIT_RFO = 0xc803fd00000400ull, // RFO hits from local IO
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_ITOM = 0xcc43ff00000400ull, // ItoM from local IO
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_ITOMCACHENEAR = 0xcd43ff00000400ull, // ItoMCacheNears from IO devices.
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_MISS = 0xc001fe00000400ull, // Misses from local IO
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_MISS_ITOM = 0xcc43fe00000400ull, // ItoM misses from local IO
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_MISS_ITOMCACHENEAR = 0xcd43fe00000400ull, // ItoMCacheNears
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_MISS_PCIRDCUR = 0xc8f3fe00000400ull, // RdCur and FsRdCur misses from local IO
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_MISS_RFO = 0xc803fe00000400ull, // RFO misses from local IO
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_PCIRDCUR = 0xc8f3ff00000400ull, // RdCur from local IO
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_RFO = 0xc803ff00000400ull, // RFO from local IO
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_WBMTOI = 0xcc23ff00000400ull, // WbMtoIs issued by IO Devices
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IPQ = 0x0800ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IRQ_IA = 0x0100ull, // IRQ - iA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__IRQ_NON_IA = 0x1000ull, // IRQ - Non iA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__ISOC = 0x200000000000000ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__LOCAL_TGT = 0x8000000000ull, // Local Targets (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__LOC_ALL = 0xc000ff00000500ull, // All from Local iA and IO (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__LOC_IA = 0xc000ff00000100ull, // All from Local iA (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__LOC_IO = 0xc000ff00000400ull, // All from Local IO (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__MISS = 0x200000000ull, // Just Misses (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__MMCFG = 0x2000000000ull, // MMCFG Access (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__MMIO = 0x4000000000ull, // MMIO Access (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__NEARMEM = 0x40000000000000ull, // Near Memory (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__NONCOH = 0x100000000000000ull, // Non Coherent (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__NOT_NEARMEM = 0x80000000000000ull, // Not Near Memory (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__PMM = 0x800000000ull, // PMM Access (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__PRQ_IOSF = 0x0400ull, // PRQ - IOSF (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__PRQ_NON_IOSF = 0x2000ull, // PRQ - Non IOSF (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__REMOTE_TGT = 0x10000000000ull, // Remote Targets (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__REM_ALL = 0xc001ff0000c800ull, // All from Remote (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__REM_SNPS = 0xc001ff00000800ull, // All Snoops from Remote (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__RRQ = 0x4000ull, // TBD (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__SNPS_FROM_REM = 0xc001ff00000800ull, // All Snoops from Remote (experimental)
		UNC_CHA_TOR_INSERTS__MASK__SPR_UNC_CHA_TOR_INSERTS__WBQ = 0x8000ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY = 0x0036, // TOR Occupancy
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__ALL = 0xc001ff0000ff00ull, // All (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__DDR = 0x400000000ull, // DDR Access (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__EVICT = 0x0200ull, // SF/LLC Evictions (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__HIT = 0x100000000ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA = 0xc001ff00000100ull, // All from Local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_CLFLUSH = 0xc8c7ff00000100ull, // CLFlush from Local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_CLFLUSHOPT = 0xc8d7ff00000100ull, // CLFlushOpt from Local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_CRD = 0xc80fff00000100ull, // CRd from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_CRD_PREF = 0xc88fff00000100ull, // Rd Pref from local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_DRD = 0xc817ff00000100ull, // Rd from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_DRDPTE = 0xc837ff00000100ull, // DRd PTEs issued by iA Cores (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_DRD_OPT = 0xc827ff00000100ull, // DRd Opt from local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_DRD_OPT_PREF = 0xc8a7ff00000100ull, // DRd Opt Pref from local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_DRD_PREF = 0xc897ff00000100ull, // DRd Pref from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT = 0xc001fd00000100ull, // Hits from Local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_CRD = 0xc80ffd00000100ull, // CRd hits from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_CRD_PREF = 0xc88ffd00000100ull, // CRd Pref hits from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_CXL_ACC = 0x10c0018100000100ull, // All requests issued from IA cores to CXL accelerator memory regions that hit the LLC. (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_CXL_ACC_LOCAL = 0x10c0008100000100ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_DRD = 0xc817fd00000100ull, // DRd hits from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_DRDPTE = 0xc837fd00000100ull, // DRd PTEs issued by iA Cores that Hit the LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_DRD_OPT = 0xc827fd00000100ull, // DRd Opt hits from local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_DRD_OPT_PREF = 0xc8a7fd00000100ull, // DRd Opt Pref hits from local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_DRD_PREF = 0xc897fd00000100ull, // DRd Pref hits from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_ITOM = 0xcc47fd00000100ull, // ItoMs issued by iA Cores that Hit LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_LLCPREFCODE = 0xcccffd00000100ull, // LLCPrefCode hits from local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_LLCPREFDATA = 0xccd7fd00000100ull, // LLCPrefData hits from local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_LLCPREFRFO = 0xccc7fd00000100ull, // LLCPrefRFO hits from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_RFO = 0xc807fd00000100ull, // RFO hits from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_HIT_RFO_PREF = 0xc887fd00000100ull, // RFO Pref hits from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_ITOM = 0xcc47ff00000100ull, // ItoM from Local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_ITOMCACHENEAR = 0xcd47ff00000100ull, // ItoMCacheNears issued by iA Cores (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_LLCPREFCODE = 0xcccfff00000100ull, // LLCPrefCode from local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_LLCPREFDATA = 0xccd7ff00000100ull, // LLCPrefData from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_LLCPREFRFO = 0xccc7ff00000100ull, // LLCPrefRFO from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS = 0xc001fe00000100ull, // misses from Local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRD = 0xc80ffe00000100ull, // CRd misses from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRDMORPH_CXL_ACC = 0x10c80b8200000100ull, // CRds and equivalent opcodes issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRD_LOCAL = 0xc80efe00000100ull, // CRd issued by iA Cores that Missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRD_PREF = 0xc88ffe00000100ull, // CRd Pref misses from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRD_PREF_LOCAL = 0xc88efe00000100ull, // CRd_Prefs issued by iA Cores that Missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRD_PREF_REMOTE = 0xc88f7e00000100ull, // CRd_Prefs issued by iA Cores that Missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CRD_REMOTE = 0xc80f7e00000100ull, // CRd issued by iA Cores that Missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CXL_ACC = 0x10c0018200000100ull, // All requests issued from IA cores to CXL accelerator memory regions that miss the LLC. (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_CXL_ACC_LOCAL = 0x10c0008200000100ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD = 0xc817fe00000100ull, // DRd misses from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRDMORPH_CXL_ACC = 0x10c8138200000100ull, // DRds and equivalent opcodes issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRDPTE = 0xc837fe00000100ull, // DRd PTEs issued by iA Cores that Missed the LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_CXL_ACC = 0x10c8178200000100ull, // DRds issued from an IA core which miss the L3 and target memory in a CXL type 2 memory expander card. (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_CXL_ACC_LOCAL = 0x10c8168200000100ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_DDR = 0xc8178600000100ull, // DRds issued by IA Cores targeting DDR Mem that Missed the LLC
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_LOCAL = 0xc816fe00000100ull, // DRd misses from local IA targeting local memory
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_LOCAL_DDR = 0xc8168600000100ull, // DRds issued by iA Cores targeting DDR Mem that Missed the LLC - HOMed locally
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_LOCAL_PMM = 0xc8168a00000100ull, // DRds issued by iA Cores targeting PMM Mem that Missed the LLC - HOMed locally
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_OPT = 0xc827fe00000100ull, // DRd Opt misses from local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_OPT_CXL_ACC_LOCAL = 0x10c8268200000100ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_OPT_PREF = 0xc8a7fe00000100ull, // DRd Opt Pref misses from local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_OPT_PREF_CXL_ACC_LOCAL = 0x10c8a68200000100ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PMM = 0xc8178a00000100ull, // DRds issued by iA Cores targeting PMM Mem that Missed the LLC
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF = 0xc897fe00000100ull, // DRd Pref misses from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_CXL_ACC = 0x10c8978200000100ull, // L2 data prefetches issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_CXL_ACC_LOCAL = 0x10c8968200000100ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_DDR = 0xc8978600000100ull, // DRd_Prefs issued by iA Cores targeting DDR Mem that Missed the LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_LOCAL = 0xc896fe00000100ull, // DRd Pref misses from local IA targeting local memory
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_LOCAL_DDR = 0xc8968600000100ull, // DRd_Prefs issued by iA Cores targeting DDR Mem that Missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_LOCAL_PMM = 0xc8968a00000100ull, // DRd_Prefs issued by iA Cores targeting PMM Mem that Missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_PMM = 0xc8978a00000100ull, // DRd_Prefs issued by iA Cores targeting PMM Mem that Missed the LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_REMOTE = 0xc8977e00000100ull, // DRd Pref misses from local IA targeting remote memory
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_REMOTE_DDR = 0xc8970600000100ull, // DRd_Prefs issued by iA Cores targeting DDR Mem that Missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_PREF_REMOTE_PMM = 0xc8970a00000100ull, // DRd_Prefs issued by iA Cores targeting PMM Mem that Missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_REMOTE = 0xc8177e00000100ull, // DRd misses from local IA targeting remote memory
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_REMOTE_DDR = 0xc8170600000100ull, // DRds issued by iA Cores targeting DDR Mem that Missed the LLC - HOMed remotely
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_DRD_REMOTE_PMM = 0xc8170a00000100ull, // DRds issued by iA Cores targeting PMM Mem that Missed the LLC - HOMed remotely
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_ITOM = 0xcc47fe00000100ull, // ItoMs issued by iA Cores that Missed LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFCODE = 0xcccffe00000100ull, // LLCPrefCode misses from local IA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFCODE_CXL_ACC = 0x10cccf8200000100ull, // LLC Prefetch Code transactions issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFDATA = 0xccd7fe00000100ull, // LLCPrefData misses from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFDATA_CXL_ACC = 0x10ccd78200000100ull, // LLC data prefetches issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFDATA_CXL_ACC_LOCAL = 0x10ccd68200000100ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFRFO = 0xccc7fe00000100ull, // LLCPrefRFO misses from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFRFO_CXL_ACC = 0x10c8878200000100ull, // L2 RFO prefetches issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LLCPREFRFO_CXL_ACC_LOCAL = 0x10c8868200000100ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LOCAL_WCILF_DDR = 0xc8668600000100ull, // WCiLFs issued by iA Cores targeting DDR that missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LOCAL_WCILF_PMM = 0xc8668a00000100ull, // WCiLFs issued by iA Cores targeting PMM that missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LOCAL_WCIL_DDR = 0xc86e8600000100ull, // WCiLs issued by iA Cores targeting DDR that missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_LOCAL_WCIL_PMM = 0xc86e8a00000100ull, // WCiLs issued by iA Cores targeting PMM that missed the LLC - HOMed locally (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_REMOTE_WCILF_DDR = 0xc8670600000100ull, // WCiLFs issued by iA Cores targeting DDR that missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_REMOTE_WCILF_PMM = 0xc8670a00000100ull, // WCiLFs issued by iA Cores targeting PMM that missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_REMOTE_WCIL_DDR = 0xc86f0600000100ull, // WCiLs issued by iA Cores targeting DDR that missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_REMOTE_WCIL_PMM = 0xc86f0a00000100ull, // WCiLs issued by iA Cores targeting PMM that missed the LLC - HOMed remotely (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO = 0xc807fe00000100ull, // RFO misses from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFOMORPH_CXL_ACC = 0x10c8038200000100ull, // RFO and L2 RFO prefetches issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_CXL_ACC = 0x10c8078200000100ull, // RFOs issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_CXL_ACC_LOCAL = 0x10c8068200000100ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_LOCAL = 0xc806fe00000100ull, // RFO misses from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_PREF = 0xc887fe00000100ull, // RFO pref misses from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_PREF_CXL_ACC = 0x10ccc78200000100ull, // LLC RFO prefetches issued from an IA core which miss the L3 and target memory in a CXL type 2 accelerator. (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_PREF_CXL_ACC_LOCAL = 0x10ccc68200000100ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_PREF_LOCAL = 0xc886fe00000100ull, // RFO prefetch misses from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_PREF_REMOTE = 0xc8877e00000100ull, // RFO prefetch misses from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_RFO_REMOTE = 0xc8077e00000100ull, // RFO misses from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_UCRDF = 0xc877de00000100ull, // UCRdFs issued by iA Cores that Missed LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WCIL = 0xc86ffe00000100ull, // WCiLs issued by iA Cores that Missed the LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WCILF = 0xc867fe00000100ull, // WCiLF issued by iA Cores that Missed the LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WCILF_DDR = 0xc8678600000100ull, // WCiLFs issued by iA Cores targeting DDR that missed the LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WCILF_PMM = 0xc8678a00000100ull, // WCiLFs issued by iA Cores targeting PMM that missed the LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WCIL_DDR = 0xc86f8600000100ull, // WCiLs issued by iA Cores targeting DDR that missed the LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WCIL_PMM = 0xc86f8a00000100ull, // WCiLs issued by iA Cores targeting PMM that missed the LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_MISS_WIL = 0xc87fde00000100ull, // WiLs issued by iA Cores that Missed LLC (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_RFO = 0xc807ff00000100ull, // RFO from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_RFO_PREF = 0xc887ff00000100ull, // RFO pref from local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_SPECITOM = 0xcc57ff00000100ull, // SpecItoM from Local IA
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WBEFTOE = 0xcc3fff00000100ull, // WBEFtoEs issued by an IA Core.  Non Modified Write Backs (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WBEFTOI = 0xcc37ff00000100ull, // WBEFtoEs issued by an IA Core.  Non Modified Write Backs (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WBMTOE = 0xcc2fff00000100ull, // WBEFtoEs issued by an IA Core.  Non Modified Write Backs (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WBMTOI = 0xcc27ff00000100ull, // WbMtoIs issued by an iA Cores. Modified Write Backs (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WBSTOI = 0xcc67ff00000100ull, // WBEFtoEs issued by an IA Core.  Non Modified Write Backs (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WCIL = 0xc86fff00000100ull, // WCiLs issued by iA Cores (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IA_WCILF = 0xc867ff00000100ull, // WCiLF issued by iA Cores (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO = 0xc001ff00000400ull, // All from local IO
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_CLFLUSH = 0xc8c3ff00000400ull, // CLFlushes issued by IO Devices
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_HIT = 0xc001fd00000400ull, // Hits from local IO
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_HIT_ITOM = 0xcc43fd00000400ull, // ItoM hits from local IO
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_HIT_ITOMCACHENEAR = 0xcd43fd00000400ull, // ItoMCacheNears
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_HIT_PCIRDCUR = 0xc8f3fd00000400ull, // RdCur and FsRdCur hits from local IO
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_HIT_RFO = 0xc803fd00000400ull, // RFO hits from local IO
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_ITOM = 0xcc43ff00000400ull, // ItoM from local IO
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_ITOMCACHENEAR = 0xcd43ff00000400ull, // ItoMCacheNears from IO devices.
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_MISS = 0xc001fe00000400ull, // Misses from local IO
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_MISS_ITOM = 0xcc43fe00000400ull, // ItoM misses from local IO
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_MISS_ITOMCACHENEAR = 0xcd43fe00000400ull, // ItoMCacheNears
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_MISS_PCIRDCUR = 0xc8f3fe00000400ull, // RdCur and FsRdCur misses from local IO
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_MISS_RFO = 0xc803fe00000400ull, // RFO misses from local IO
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_PCIRDCUR = 0xc8f3ff00000400ull, // RdCur from local IO
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_RFO = 0xc803ff00000400ull, // RFO from local IO
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IO_WBMTOI = 0xcc23ff00000400ull, // WbMtoIs issued by IO Devices
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IPQ = 0x0800ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IRQ_IA = 0x0100ull, // IRQ - iA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__IRQ_NON_IA = 0x1000ull, // IRQ - Non iA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__ISOC = 0x200000000000000ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__LOCAL_TGT = 0x8000000000ull, // Local Targets (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__LOC_ALL = 0xc000ff00000500ull, // All from Local iA and IO (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__LOC_IA = 0xc000ff00000100ull, // All from Local iA (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__LOC_IO = 0xc000ff00000400ull, // All from Local IO (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__MISS = 0x200000000ull, // Just Misses (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__MMCFG = 0x2000000000ull, // MMCFG Access (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__MMIO = 0x4000000000ull, // MMIO Access (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__NEARMEM = 0x40000000000000ull, // Near Memory (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__NONCOH = 0x100000000000000ull, // Non Coherent (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__NOT_NEARMEM = 0x80000000000000ull, // Not Near Memory (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__PMM = 0x800000000ull, // PMM Access (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__PRQ_IOSF = 0x0400ull, // PRQ - IOSF (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__PRQ_NON_IOSF = 0x2000ull, // PRQ - Non IOSF (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__REMOTE_TGT = 0x10000000000ull, // Remote Targets (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__REM_ALL = 0xc001ff0000c800ull, // All from Remote (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__REM_SNPS = 0xc001ff00000800ull, // All Snoops from Remote (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__RRQ = 0x4000ull, // TBD (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__SNPS_FROM_REM = 0xc001ff00000800ull, // All Snoops from Remote (experimental)
		UNC_CHA_TOR_OCCUPANCY__MASK__SPR_UNC_CHA_TOR_INSERTS__WBQ = 0x8000ull, // TBD (experimental)
		UNC_CHA_WB_PUSH_MTOI = 0x0056, // WbPushMtoI
		UNC_CHA_WB_PUSH_MTOI__MASK__SPR_UNC_CHA_WB_PUSH_MTOI__LLC = 0x0100ull, // Pushed to LLC (experimental)
		UNC_CHA_WB_PUSH_MTOI__MASK__SPR_UNC_CHA_WB_PUSH_MTOI__MEM = 0x0200ull, // Pushed to Memory (experimental)
		UNC_CHA_WRITE_NO_CREDITS = 0x005a, // CHA iMC CHNx WRITE Credits Empty
		UNC_CHA_WRITE_NO_CREDITS__MASK__SPR_UNC_CHA_WRITE_NO_CREDITS__MC0 = 0x0100ull, // TBD (experimental)
		UNC_CHA_WRITE_NO_CREDITS__MASK__SPR_UNC_CHA_WRITE_NO_CREDITS__MC1 = 0x0200ull, // TBD (experimental)
		UNC_CHA_WRITE_NO_CREDITS__MASK__SPR_UNC_CHA_WRITE_NO_CREDITS__MC2 = 0x0400ull, // TBD (experimental)
		UNC_CHA_WRITE_NO_CREDITS__MASK__SPR_UNC_CHA_WRITE_NO_CREDITS__MC3 = 0x0800ull, // TBD (experimental)
		UNC_CHA_WRITE_NO_CREDITS__MASK__SPR_UNC_CHA_WRITE_NO_CREDITS__MC4 = 0x1000ull, // TBD (experimental)
		UNC_CHA_WRITE_NO_CREDITS__MASK__SPR_UNC_CHA_WRITE_NO_CREDITS__MC5 = 0x2000ull, // TBD (experimental)
		UNC_CHA_XPT_PREF = 0x006f, // XPT Prefetches
		UNC_CHA_XPT_PREF__MASK__SPR_UNC_CHA_XPT_PREF__DROP0_CONFLICT = 0x0800ull, // Dropped (on 0?) - Conflict (experimental)
		UNC_CHA_XPT_PREF__MASK__SPR_UNC_CHA_XPT_PREF__DROP0_NOCRD = 0x0400ull, // Dropped (on 0?) - No Credits (experimental)
		UNC_CHA_XPT_PREF__MASK__SPR_UNC_CHA_XPT_PREF__DROP1_CONFLICT = 0x8000ull, // Dropped (on 1?) - Conflict (experimental)
		UNC_CHA_XPT_PREF__MASK__SPR_UNC_CHA_XPT_PREF__DROP1_NOCRD = 0x4000ull, // Dropped (on 1?) - No Credits (experimental)
		UNC_CHA_XPT_PREF__MASK__SPR_UNC_CHA_XPT_PREF__SENT0 = 0x0100ull, // Sent (on 0?) (experimental)
		UNC_CHA_XPT_PREF__MASK__SPR_UNC_CHA_XPT_PREF__SENT1 = 0x1000ull, // Sent (on 1?) (experimental)
		
	};
};

namespace spr_unc_cha = optkit::intel::spr_unc_cha;

#undef INTEL_X86_EDGE_BIT
#undef INTEL_X86_ANY_BIT
#undef INTEL_X86_INV_BIT
#undef INTEL_X86_CMASK_BIT
#undef INTEL_X86_MOD_EDGE
#undef INTEL_X86_MOD_ANY
#undef INTEL_X86_MOD_INV
