#pragma once
#include <cstdint>
#define INTEL_X86_EDGE_BIT	18
#define INTEL_X86_ANY_BIT	21
#define INTEL_X86_INV_BIT	23
#define INTEL_X86_CMASK_BIT 24
#define INTEL_X86_MOD_EDGE	(1 << INTEL_X86_EDGE_BIT)
#define INTEL_X86_MOD_ANY	(1 << INTEL_X86_ANY_BIT)
#define INTEL_X86_MOD_INV	(1 << INTEL_X86_INV_BIT)
namespace optkit::intel::spr_unc_upi_ll{
	enum spr_unc_upi_ll : uint64_t {
		UNC_UPI_CLOCKTICKS = 0x0001, // UPI Clockticks
		UNC_UPI_DIRECT_ATTEMPTS = 0x0012, // Direct packet attempts
		UNC_UPI_DIRECT_ATTEMPTS__MASK__SPR_UNC_UPI_DIRECT_ATTEMPTS__D2C = 0x0100ull, // D2C (experimental)
		UNC_UPI_DIRECT_ATTEMPTS__MASK__SPR_UNC_UPI_DIRECT_ATTEMPTS__D2K = 0x0200ull, // D2K (experimental)
		UNC_UPI_FLOWQ_NO_VNA_CRD = 0x0018, // TBD
		UNC_UPI_FLOWQ_NO_VNA_CRD__MASK__SPR_UNC_UPI_FLOWQ_NO_VNA_CRD__AD_VNA_EQ0 = 0x0100ull, // TBD (experimental)
		UNC_UPI_FLOWQ_NO_VNA_CRD__MASK__SPR_UNC_UPI_FLOWQ_NO_VNA_CRD__AD_VNA_EQ1 = 0x0200ull, // TBD (experimental)
		UNC_UPI_FLOWQ_NO_VNA_CRD__MASK__SPR_UNC_UPI_FLOWQ_NO_VNA_CRD__AD_VNA_EQ2 = 0x0400ull, // TBD (experimental)
		UNC_UPI_FLOWQ_NO_VNA_CRD__MASK__SPR_UNC_UPI_FLOWQ_NO_VNA_CRD__AK_VNA_EQ0 = 0x1000ull, // TBD (experimental)
		UNC_UPI_FLOWQ_NO_VNA_CRD__MASK__SPR_UNC_UPI_FLOWQ_NO_VNA_CRD__AK_VNA_EQ1 = 0x2000ull, // TBD (experimental)
		UNC_UPI_FLOWQ_NO_VNA_CRD__MASK__SPR_UNC_UPI_FLOWQ_NO_VNA_CRD__AK_VNA_EQ2 = 0x4000ull, // TBD (experimental)
		UNC_UPI_FLOWQ_NO_VNA_CRD__MASK__SPR_UNC_UPI_FLOWQ_NO_VNA_CRD__AK_VNA_EQ3 = 0x8000ull, // TBD (experimental)
		UNC_UPI_FLOWQ_NO_VNA_CRD__MASK__SPR_UNC_UPI_FLOWQ_NO_VNA_CRD__BL_VNA_EQ0 = 0x0800ull, // TBD (experimental)
		UNC_UPI_L1_POWER_CYCLES = 0x0021, // Cycles in L1
		UNC_UPI_M3_BYP_BLOCKED = 0x0014, // TBD
		UNC_UPI_M3_BYP_BLOCKED__MASK__SPR_UNC_UPI_M3_BYP_BLOCKED__BGF_CRD = 0x0800ull, // TBD (experimental)
		UNC_UPI_M3_BYP_BLOCKED__MASK__SPR_UNC_UPI_M3_BYP_BLOCKED__FLOWQ_AD_VNA_LE2 = 0x0100ull, // TBD (experimental)
		UNC_UPI_M3_BYP_BLOCKED__MASK__SPR_UNC_UPI_M3_BYP_BLOCKED__FLOWQ_AK_VNA_LE3 = 0x0400ull, // TBD (experimental)
		UNC_UPI_M3_BYP_BLOCKED__MASK__SPR_UNC_UPI_M3_BYP_BLOCKED__FLOWQ_BL_VNA_EQ0 = 0x0200ull, // TBD (experimental)
		UNC_UPI_M3_BYP_BLOCKED__MASK__SPR_UNC_UPI_M3_BYP_BLOCKED__GV_BLOCK = 0x1000ull, // TBD (experimental)
		UNC_UPI_M3_CRD_RETURN_BLOCKED = 0x0016, // TBD (experimental)
		UNC_UPI_M3_RXQ_BLOCKED = 0x0015, // TBD
		UNC_UPI_M3_RXQ_BLOCKED__MASK__SPR_UNC_UPI_M3_RXQ_BLOCKED__BGF_CRD = 0x2000ull, // TBD (experimental)
		UNC_UPI_M3_RXQ_BLOCKED__MASK__SPR_UNC_UPI_M3_RXQ_BLOCKED__FLOWQ_AD_VNA_BTW_2_THRESH = 0x0200ull, // TBD (experimental)
		UNC_UPI_M3_RXQ_BLOCKED__MASK__SPR_UNC_UPI_M3_RXQ_BLOCKED__FLOWQ_AD_VNA_LE2 = 0x0100ull, // TBD (experimental)
		UNC_UPI_M3_RXQ_BLOCKED__MASK__SPR_UNC_UPI_M3_RXQ_BLOCKED__FLOWQ_AK_VNA_LE3 = 0x1000ull, // TBD (experimental)
		UNC_UPI_M3_RXQ_BLOCKED__MASK__SPR_UNC_UPI_M3_RXQ_BLOCKED__FLOWQ_BL_VNA_BTW_0_THRESH = 0x0800ull, // TBD (experimental)
		UNC_UPI_M3_RXQ_BLOCKED__MASK__SPR_UNC_UPI_M3_RXQ_BLOCKED__FLOWQ_BL_VNA_EQ0 = 0x0400ull, // TBD (experimental)
		UNC_UPI_M3_RXQ_BLOCKED__MASK__SPR_UNC_UPI_M3_RXQ_BLOCKED__GV_BLOCK = 0x4000ull, // TBD (experimental)
		UNC_UPI_PHY_INIT_CYCLES = 0x0020, // PHY Cycles (experimental)
		UNC_UPI_POWER_L1_NACK = 0x0023, // L1 Req Nack (experimental)
		UNC_UPI_POWER_L1_REQ = 0x0022, // L1 Req (same as L1 Ack). (experimental)
		UNC_UPI_REQ_SLOT2_FROM_M3 = 0x0046, // TBD
		UNC_UPI_REQ_SLOT2_FROM_M3__MASK__SPR_UNC_UPI_REQ_SLOT2_FROM_M3__ACK = 0x0800ull, // TBD (experimental)
		UNC_UPI_REQ_SLOT2_FROM_M3__MASK__SPR_UNC_UPI_REQ_SLOT2_FROM_M3__VN0 = 0x0200ull, // TBD (experimental)
		UNC_UPI_REQ_SLOT2_FROM_M3__MASK__SPR_UNC_UPI_REQ_SLOT2_FROM_M3__VN1 = 0x0400ull, // TBD (experimental)
		UNC_UPI_REQ_SLOT2_FROM_M3__MASK__SPR_UNC_UPI_REQ_SLOT2_FROM_M3__VNA = 0x0100ull, // TBD (experimental)
		UNC_UPI_RxL0P_POWER_CYCLES = 0x0025, // Cycles in L0p (experimental)
		UNC_UPI_RxL0_POWER_CYCLES = 0x0024, // Cycles in L0 (experimental)
		UNC_UPI_RxL_ANY_FLITS = 0x004b, // TBD
		UNC_UPI_RxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__DATA = 0x0800ull, // TBD (experimental)
		UNC_UPI_RxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__LLCRD = 0x1000ull, // TBD (experimental)
		UNC_UPI_RxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__LLCTRL = 0x4000ull, // TBD (experimental)
		UNC_UPI_RxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__NULL = 0x2000ull, // TBD (experimental)
		UNC_UPI_RxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__PROTHDR = 0x8000ull, // TBD (experimental)
		UNC_UPI_RxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__SLOT0 = 0x0100ull, // TBD (experimental)
		UNC_UPI_RxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__SLOT1 = 0x0200ull, // TBD (experimental)
		UNC_UPI_RxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__SLOT2 = 0x0400ull, // TBD (experimental)
		UNC_UPI_RxL_BYPASSED = 0x0031, // RxQ Flit Buffer Bypassed
		UNC_UPI_RxL_BYPASSED__MASK__SPR_UNC_UPI_RXL_INSERTS__SLOT0 = 0x0100ull, // Slot 0 (experimental)
		UNC_UPI_RxL_BYPASSED__MASK__SPR_UNC_UPI_RXL_INSERTS__SLOT1 = 0x0200ull, // Slot 1 (experimental)
		UNC_UPI_RxL_BYPASSED__MASK__SPR_UNC_UPI_RXL_INSERTS__SLOT2 = 0x0400ull, // Slot 2 (experimental)
		UNC_UPI_RxL_CRC_ERRORS = 0x000b, // CRC Errors Detected (experimental)
		UNC_UPI_RxL_CRC_LLR_REQ_TRANSMIT = 0x0008, // LLR Requests Sent (experimental)
		UNC_UPI_RxL_CREDITS_CONSUMED_VN0 = 0x0039, // VN0 Credit Consumed (experimental)
		UNC_UPI_RxL_CREDITS_CONSUMED_VN1 = 0x003a, // VN1 Credit Consumed (experimental)
		UNC_UPI_RxL_CREDITS_CONSUMED_VNA = 0x0038, // VNA Credit Consumed (experimental)
		UNC_UPI_RxL_FLITS = 0x0003, // Flits Received
		UNC_UPI_RxL_FLITS__MASK__SPR_UNC_UPI_RXL_FLITS__ALL_DATA = 0x0f00ull, // All Data
		UNC_UPI_RxL_FLITS__MASK__SPR_UNC_UPI_RXL_FLITS__ALL_NULL = 0x2700ull, // Null FLITs received from any slot
		UNC_UPI_RxL_FLITS__MASK__SPR_UNC_UPI_RXL_FLITS__DATA = 0x0800ull, // Data (experimental)
		UNC_UPI_RxL_FLITS__MASK__SPR_UNC_UPI_RXL_FLITS__IDLE = 0x4700ull, // Idle (experimental)
		UNC_UPI_RxL_FLITS__MASK__SPR_UNC_UPI_RXL_FLITS__LLCRD = 0x1000ull, // LLCRD Not Empty (experimental)
		UNC_UPI_RxL_FLITS__MASK__SPR_UNC_UPI_RXL_FLITS__LLCTRL = 0x4000ull, // LLCTRL (experimental)
		UNC_UPI_RxL_FLITS__MASK__SPR_UNC_UPI_RXL_FLITS__NON_DATA = 0x9700ull, // All Non Data
		UNC_UPI_RxL_FLITS__MASK__SPR_UNC_UPI_RXL_FLITS__NULL = 0x2000ull, // Slot NULL or LLCRD Empty (experimental)
		UNC_UPI_RxL_FLITS__MASK__SPR_UNC_UPI_RXL_FLITS__PROTHDR = 0x8000ull, // Protocol Header (experimental)
		UNC_UPI_RxL_FLITS__MASK__SPR_UNC_UPI_RXL_FLITS__SLOT0 = 0x0100ull, // Slot 0 (experimental)
		UNC_UPI_RxL_FLITS__MASK__SPR_UNC_UPI_RXL_FLITS__SLOT1 = 0x0200ull, // Slot 1 (experimental)
		UNC_UPI_RxL_FLITS__MASK__SPR_UNC_UPI_RXL_FLITS__SLOT2 = 0x0400ull, // Slot 2 (experimental)
		UNC_UPI_RxL_INSERTS = 0x0030, // Receive Flit Buffer Allocations
		UNC_UPI_RxL_INSERTS__MASK__SPR_UNC_UPI_RXL_INSERTS__SLOT0 = 0x0100ull, // Slot 0 (experimental)
		UNC_UPI_RxL_INSERTS__MASK__SPR_UNC_UPI_RXL_INSERTS__SLOT1 = 0x0200ull, // Slot 1 (experimental)
		UNC_UPI_RxL_INSERTS__MASK__SPR_UNC_UPI_RXL_INSERTS__SLOT2 = 0x0400ull, // Slot 2 (experimental)
		UNC_UPI_RxL_OCCUPANCY = 0x0032, // RxQ Occupancy
		UNC_UPI_RxL_OCCUPANCY__MASK__SPR_UNC_UPI_RXL_OCCUPANCY__SLOT0 = 0x0100ull, // Slot 0 (experimental)
		UNC_UPI_RxL_OCCUPANCY__MASK__SPR_UNC_UPI_RXL_OCCUPANCY__SLOT1 = 0x0200ull, // Slot 1 (experimental)
		UNC_UPI_RxL_OCCUPANCY__MASK__SPR_UNC_UPI_RXL_OCCUPANCY__SLOT2 = 0x0400ull, // Slot 2 (experimental)
		UNC_UPI_RxL_SLOT_BYPASS = 0x0033, // TBD
		UNC_UPI_RxL_SLOT_BYPASS__MASK__SPR_UNC_UPI_RXL_SLOT_BYPASS__S0_RXQ1 = 0x0100ull, // TBD (experimental)
		UNC_UPI_RxL_SLOT_BYPASS__MASK__SPR_UNC_UPI_RXL_SLOT_BYPASS__S0_RXQ2 = 0x0200ull, // TBD (experimental)
		UNC_UPI_RxL_SLOT_BYPASS__MASK__SPR_UNC_UPI_RXL_SLOT_BYPASS__S1_RXQ0 = 0x0400ull, // TBD (experimental)
		UNC_UPI_RxL_SLOT_BYPASS__MASK__SPR_UNC_UPI_RXL_SLOT_BYPASS__S1_RXQ2 = 0x0800ull, // TBD (experimental)
		UNC_UPI_RxL_SLOT_BYPASS__MASK__SPR_UNC_UPI_RXL_SLOT_BYPASS__S2_RXQ0 = 0x1000ull, // TBD (experimental)
		UNC_UPI_RxL_SLOT_BYPASS__MASK__SPR_UNC_UPI_RXL_SLOT_BYPASS__S2_RXQ1 = 0x2000ull, // TBD (experimental)
		UNC_UPI_TxL0P_CLK_ACTIVE = 0x002a, // TBD
		UNC_UPI_TxL0P_CLK_ACTIVE__MASK__SPR_UNC_UPI_TXL0P_CLK_ACTIVE__CFG_CTL = 0x0100ull, // TBD (experimental)
		UNC_UPI_TxL0P_CLK_ACTIVE__MASK__SPR_UNC_UPI_TXL0P_CLK_ACTIVE__DFX = 0x4000ull, // TBD (experimental)
		UNC_UPI_TxL0P_CLK_ACTIVE__MASK__SPR_UNC_UPI_TXL0P_CLK_ACTIVE__RETRY = 0x2000ull, // TBD (experimental)
		UNC_UPI_TxL0P_CLK_ACTIVE__MASK__SPR_UNC_UPI_TXL0P_CLK_ACTIVE__RXQ = 0x0200ull, // TBD (experimental)
		UNC_UPI_TxL0P_CLK_ACTIVE__MASK__SPR_UNC_UPI_TXL0P_CLK_ACTIVE__RXQ_BYPASS = 0x0400ull, // TBD (experimental)
		UNC_UPI_TxL0P_CLK_ACTIVE__MASK__SPR_UNC_UPI_TXL0P_CLK_ACTIVE__RXQ_CRED = 0x0800ull, // TBD (experimental)
		UNC_UPI_TxL0P_CLK_ACTIVE__MASK__SPR_UNC_UPI_TXL0P_CLK_ACTIVE__SPARE = 0x8000ull, // TBD (experimental)
		UNC_UPI_TxL0P_CLK_ACTIVE__MASK__SPR_UNC_UPI_TXL0P_CLK_ACTIVE__TXQ = 0x1000ull, // TBD (experimental)
		UNC_UPI_TxL0P_POWER_CYCLES = 0x0027, // Cycles in L0p (experimental)
		UNC_UPI_TxL0P_POWER_CYCLES_LL_ENTER = 0x0028, // TBD (experimental)
		UNC_UPI_TxL0P_POWER_CYCLES_M3_EXIT = 0x0029, // TBD (experimental)
		UNC_UPI_TxL0_POWER_CYCLES = 0x0026, // Cycles in L0 (experimental)
		UNC_UPI_TxL_ANY_FLITS = 0x004a, // TBD
		UNC_UPI_TxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__DATA = 0x0800ull, // TBD (experimental)
		UNC_UPI_TxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__LLCRD = 0x1000ull, // TBD (experimental)
		UNC_UPI_TxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__LLCTRL = 0x4000ull, // TBD (experimental)
		UNC_UPI_TxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__NULL = 0x2000ull, // TBD (experimental)
		UNC_UPI_TxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__PROTHDR = 0x8000ull, // TBD (experimental)
		UNC_UPI_TxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__SLOT0 = 0x0100ull, // TBD (experimental)
		UNC_UPI_TxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__SLOT1 = 0x0200ull, // TBD (experimental)
		UNC_UPI_TxL_ANY_FLITS__MASK__SPR_UNC_UPI_TXL_ANY_FLITS__SLOT2 = 0x0400ull, // TBD (experimental)
		UNC_UPI_TxL_BYPASSED = 0x0041, // Transmitted Flit Buffer Bypassed (experimental)
		UNC_UPI_TxL_FLITS = 0x0002, // Flits transmitted
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__ALL_DATA = 0x0f00ull, // All Data
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__ALL_LLCRD = 0x1700ull, // All LLCRD Not Empty (experimental)
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__ALL_LLCTRL = 0x4700ull, // All LLCTRL (experimental)
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__ALL_NULL = 0x2700ull, // All Null Flits
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__ALL_PROTHDR = 0x8700ull, // All Protocol Header (experimental)
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__DATA = 0x0800ull, // Data (experimental)
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__IDLE = 0x4700ull, // Idle (experimental)
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__LLCRD = 0x1000ull, // LLCRD Not Empty (experimental)
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__LLCTRL = 0x4000ull, // LLCTRL (experimental)
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__NON_DATA = 0x9700ull, // All Non Data
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__NULL = 0x2000ull, // Slot NULL or LLCRD Empty (experimental)
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__PROTHDR = 0x8000ull, // Protocol Header (experimental)
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__SLOT0 = 0x0100ull, // Slot 0 (experimental)
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__SLOT1 = 0x0200ull, // Slot 1 (experimental)
		UNC_UPI_TxL_FLITS__MASK__SPR_UNC_UPI_TXL_FLITS__SLOT2 = 0x0400ull, // Slot 2 (experimental)
		UNC_UPI_TxL_INSERTS = 0x0040, // Transmitted Flit Buffer Allocations (experimental)
		UNC_UPI_TxL_OCCUPANCY = 0x0042, // Transmitted Flit Buffer Occupancy (experimental)
		UNC_UPI_VNA_CREDIT_RETURN_BLOCKED_VN01 = 0x0045, // TBD (experimental)
		UNC_UPI_VNA_CREDIT_RETURN_OCCUPANCY = 0x0044, // VNA Credits Pending Return - Occupancy (experimental)
		
	};
};

namespace spr_unc_upi_ll = optkit::intel::spr_unc_upi_ll;

#undef INTEL_X86_EDGE_BIT
#undef INTEL_X86_ANY_BIT
#undef INTEL_X86_INV_BIT
#undef INTEL_X86_CMASK_BIT
#undef INTEL_X86_MOD_EDGE
#undef INTEL_X86_MOD_ANY
#undef INTEL_X86_MOD_INV
