#pragma once
#include <cstdint>
namespace optkit::amd64::fam19h_zen4{
	enum fam19h_zen4 : uint64_t {
		RETIRED_X87_FP_OPS = 0x2, // Number of X87 floating-point ops retired
		RETIRED_X87_FP_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_X87_FP_OPS__ADD_SUB_OPS = 0x100ull, // Number of add/subtract ops
		RETIRED_X87_FP_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_X87_FP_OPS__MUL_OPS = 0x200ull, // Number of multiply ops
		RETIRED_X87_FP_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_X87_FP_OPS__DIV_SQRT_OPS = 0x400ull, // Number of divide and square root ops
		RETIRED_SSE_AVX_FLOPS = 0x3, // This is a retire-based event. The number of retired SSE/AVX FLOPS. The number of events logged per cycle can vary from 0 to 64. This event can count above 15 and therefore requires the MergeEvent
		RETIRED_SSE_AVX_FLOPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_SSE_AVX_FLOPS__ADD_SUB_FLOPS = 0x100ull, // Addition/subtraction FLOPS
		RETIRED_SSE_AVX_FLOPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_SSE_AVX_FLOPS__MULT_FLOPS = 0x200ull, // Multiplication FLOPS
		RETIRED_SSE_AVX_FLOPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_SSE_AVX_FLOPS__DIV_FLOPS = 0x400ull, // Division/Square-root FLOPS
		RETIRED_SSE_AVX_FLOPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_SSE_AVX_FLOPS__MAC_FLOPS = 0x800ull, // Multiply-Accumulate flops. Each MAC operation is counted as 2 FLOPS. This event does not include bfloat MAC operations
		RETIRED_SSE_AVX_FLOPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_SSE_AVX_FLOPS__BFLOAT_MAC_FLOPS = 0x1000ull, // Bfloat Multiply-Accumulate flops. Each MAC operation is counted as 2 FLOPS
		RETIRED_SSE_AVX_FLOPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_SSE_AVX_FLOPS__ANY = 0x1f00ull, // Double precision add/subtract flops
		RETIRED_SERIALIZING_OPS = 0x5, // The number of serializing ops retired
		RETIRED_SERIALIZING_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_SERIALIZING_OPS__X87_CTRL_RET = 0x100ull, // x87 control word mispredict traps due to mispredction in RC or PC
		RETIRED_SERIALIZING_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_SERIALIZING_OPS__X87_BOT_RET = 0x200ull, // x87 bottom-executing ops retired
		RETIRED_SERIALIZING_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_SERIALIZING_OPS__SSE_CTRL_RET = 0x400ull, // SSE/AVX control word mispredict traps
		RETIRED_SERIALIZING_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_SERIALIZING_OPS__SSE_BOT_RET = 0x800ull, // SSE/AVX bottom-executing ops retired
		RETIRED_FP_OPS_BY_WIDTH = 0x8, // The number of retired floating-point ops by width
		RETIRED_FP_OPS_BY_WIDTH__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_WIDTH__X87_UOPS_RETIRED = 0x100ull, // X87 uops retired
		RETIRED_FP_OPS_BY_WIDTH__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_WIDTH__MMX_UOPS_RETIRED = 0x200ull, // MMX uops retired
		RETIRED_FP_OPS_BY_WIDTH__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_WIDTH__SCALAR_UOPS_RETIRED = 0x400ull, // Scalar uops retired
		RETIRED_FP_OPS_BY_WIDTH__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_WIDTH__PACK128_UOPS_RETIRED = 0x800ull, // Packed 128-bit uops retired
		RETIRED_FP_OPS_BY_WIDTH__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_WIDTH__PACK256_UOPS_RETIRED = 0x1000ull, // Packed 256-bit uops retired
		RETIRED_FP_OPS_BY_WIDTH__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_WIDTH__PACK512_UOPS_RETIRED = 0x2000ull, // Packed 512-bit uops retired
		RETIRED_FP_OPS_BY_TYPE = 0xa, // The number of retired floating-point ops by type
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__SCALAR_ADD = 0x100ull, // Number of scalar ADD ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__SCALAR_SUB = 0x200ull, // Number of scalar SUB ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__SCALAR_MUL = 0x300ull, // Number of scalar MUL ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__SCALAR_MAC = 0x400ull, // Number of scalar MAC ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__SCALAR_DIV = 0x500ull, // Number of scalar DIV ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__SCALAR_SQRT = 0x600ull, // Number of scalar SQRT ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__SCALAR_CMP = 0x700ull, // Number of scalar CMP ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__SCALAR_CVT = 0x800ull, // Number of scalar CVT ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__SCALAR_BLEND = 0x900ull, // Number of scalar BLEND ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__SCALAR_OTHER = 0xe00ull, // Number of other scalar ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__SCALAR_ALL = 0xf00ull, // Number of anyscalar ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_ADD = 0x1000ull, // Number of vector ADD ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_SUB = 0x2000ull, // Number of vector SUB ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_MUL = 0x3000ull, // Number of vector MUL ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_MAC = 0x4000ull, // Number of vector MAC ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_DIV = 0x5000ull, // Number of DIV ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_SQRT = 0x6000ull, // Number of vector SQRT ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_CMP = 0x7000ull, // Number of vector CMP ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_CVT = 0x8000ull, // Number of vector CVT ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_BLEND = 0x9000ull, // Number of vector BLEND ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_SHUFFLE = 0xb000ull, // Number of vector SHUFFLE ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_LOGICAL = 0xd000ull, // Number of vector LOGICAL ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_OTHER = 0xe000ull, // Number of other vector ops retired
		RETIRED_FP_OPS_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_RETIRED_FP_OPS_BY_TYPE__VECTOR_ALL = 0xf000ull, // Number of scalar ADD and vector ALL ops retired
		RETIRED_INT_OPS = 0xb, // The number of retired integer ops (SSE/AVX)
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__MMX_ADD = 0x100ull, // Number of MMX ADD ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__MMX_SUB = 0x200ull, // Number of MMX SUB ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__MMX_MUL = 0x300ull, // Number of MMX MUL ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__MMX_MAC = 0x400ull, // Number of MMX MAC ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__MMX_CMP = 0x700ull, // Number of MMX CMP ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__MMX_SHIFT = 0x900ull, // Number of MMX SHIFT ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__MMX_MOV = 0xa00ull, // Number of MMX MOV ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__MMX_SHUFFLE = 0xb00ull, // Number of MMX SHUFFLE ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__MMX_PACK = 0xc00ull, // Number of MMX PACK ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__MMX_LOGICAL = 0xd00ull, // Number of MMX LOGICAL ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__MMX_OTHER = 0xe00ull, // Number of other MMX ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__MMX_ALL = 0xf00ull, // Any MMX ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_ADD = 0x1000ull, // Number of SSE/AVX ADD ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_SUB = 0x2000ull, // Number of SSE/AVX SUB ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_MUL = 0x3000ull, // Number of SSE/AVX MUL ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_MAC = 0x4000ull, // Number of SSE/AVX MAC ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_AES = 0x5000ull, // Number of SSE/AVX AES ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_SHA = 0x6000ull, // Number of SSE/AVX SHA ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_CMP = 0x7000ull, // Number of SSE/AVX CMP ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_CLM = 0x8000ull, // Number of SSE/AVX CLM ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_SHIFT = 0x9000ull, // Number of SSE/AVX SHIFT ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_MOV = 0xa000ull, // Number of SSE/AVX MOV ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_SHUFFLE = 0xb000ull, // Number of SSE/AVX SHUFFLE ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_PACK = 0xc000ull, // Number of SSE/AVX PACK ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_LOGICAL = 0xd000ull, // Number of SSE/AVX LOGICAL ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_OTHER = 0xe000ull, // Number of other SSE/AVX ops retired
		RETIRED_INT_OPS__MASK__AMD64_FAM19H_ZEN4_RETIRED_INT_OPS__SSE_AVX_ALL = 0xf000ull, // Any SSE/AVX ops retired
		PACKED_FP_OPS_RETIRED = 0xc, // The number of packed floating-point operations
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_ADD = 0x100ull, // Number of floating-point 128-bit ADD ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_SUB = 0x200ull, // Number of floating-point 128-bit SUB ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_MUL = 0x300ull, // Number of floating-point 128-bit MUL ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_MAC = 0x400ull, // Number of floating-point 128-bit MAC ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_DIV = 0x500ull, // Number of floating-point 128-bit DIV ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_SQRT = 0x600ull, // Number of floating-point 128-bit SQRT ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_CMP = 0x700ull, // Number of floating-point 128-bit CMP ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_CVT = 0x800ull, // Number of floating-point 128-bit CVT ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_BLEND = 0x900ull, // Number of floating-point 128-bit 256-bit BLEND ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_SHUFFLE = 0xb00ull, // Number of floating-point 128-bit SHUFFLE ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_LOGICAL = 0xd00ull, // Number of floating-point 128-bit LOGICAL ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_OTHER = 0xe00ull, // Number of other floating-point 128-bit ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP128_ALL = 0xf00ull, // Number of any  floating-point 128-bit ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_ADD = 0x1000ull, // Number of floating-point 256-bit ADD ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_SUB = 0x2000ull, // Number of floating-point 256-bit SUB ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_MUL = 0x3000ull, // Number of floating-point 256-bit MUL ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_MAC = 0x4000ull, // Number of floating-point 256-bit MAC ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_DIV = 0x5000ull, // Number of floating-point 256-bit DIV ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_SQRT = 0x6000ull, // Number of floating-point 256-bit SQRT ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_CMP = 0x7000ull, // Number of floating-point 256-bit CMP ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_CVT = 0x8000ull, // Number of floating-point 256-bit CVT ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_BLEND = 0x9000ull, // Number of floating-point 256-bit BLEND ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_SHUFFLE = 0xb000ull, // Number of floating-point 256-bit SHUFFLE ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_LOGICAL = 0xd000ull, // Number of floating-point 256-bit LOGICAL ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_OTHER = 0xe000ull, // Number of other floating-point 256-bit ops retired
		PACKED_FP_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_FP_OPS_RETIRED__FP256_ALL = 0xf000ull, // Any floating-point 256-bit ops retired
		PACKED_INT_OPS_RETIRED = 0xd, // The number of packed integer operations
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_ADD = 0x100ull, // Number of integer 128-bit ADD ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_SUB = 0x200ull, // Number of integer 128-bit SUB ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_MUL = 0x300ull, // Number of integer 128-bit MUL ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_MAC = 0x400ull, // Number of integer 256-bit MAC ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_AES = 0x500ull, // Number of integer 128-bit AES ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_SHA = 0x600ull, // Number of integer 128-bit SHA ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_CMP = 0x700ull, // Number of integer 128-bit CMP ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_CLM = 0x800ull, // Number of integer 128-bit CLM ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_SHIFT = 0x900ull, // Number of integer 128-bit SHIFT ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_MOV = 0xa00ull, // Number of integer 128-bit MOV ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_SHUFFLE = 0xb00ull, // Number of integer 128-bit SHUFFLE ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_PACK = 0xc00ull, // Number of integer 128-bit PACK ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_LOGICAL = 0xd00ull, // Number of integer 128-bit LOGICAL ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_OTHER = 0xe00ull, // Number of other integer 128-bit ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT128_ALL = 0xf00ull, // Any integer 128-bit ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT256_ADD = 0x1000ull, // Number of integer 256-bit ADD ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT256_SUB = 0x2000ull, // Number of integer 256-bit SHIFT ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT256_MUL = 0x3000ull, // Number of integer 256-bit MUL ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT256_MAC = 0x4000ull, // Number of integer 256-bit MAC ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT256_CMP = 0x7000ull, // Number of integer 256-bit CMP ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT256_SHIFT = 0x9000ull, // Number of integer 256-bit SHIFT ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT256_MOV = 0xa000ull, // Number of integer 256-bit MOV ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT256_SHUFFLE = 0xb000ull, // Number of integer 256-bit SHUFFLE ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT256_PACK = 0xc000ull, // Number of integer 256-bit NONE ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT256_LOGICAL = 0xd000ull, // Number of integer 256-bit LOGICAL ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT256_OTHER = 0xe000ull, // Number of other integer 256-bit ops retired
		PACKED_INT_OPS_RETIRED__MASK__AMD64_FAM19H_ZEN4_PACKED_INT_OPS_RETIRED__INT256_ALL = 0xf000ull, // Any integer 256-bit ops retired
		FP_DISPATCH_FAULTS = 0xe, // Floating-point dispatch faults
		FP_DISPATCH_FAULTS__MASK__AMD64_FAM19H_ZEN4_FP_DISPATCH_FAULTS__X87_FILL_FAULT = 0x100ull, // x87 fill faults
		FP_DISPATCH_FAULTS__MASK__AMD64_FAM19H_ZEN4_FP_DISPATCH_FAULTS__XMM_FILL_FAULT = 0x200ull, // XMM fill faults
		FP_DISPATCH_FAULTS__MASK__AMD64_FAM19H_ZEN4_FP_DISPATCH_FAULTS__YMM_FILL_FAULT = 0x400ull, // YMM fill faults
		FP_DISPATCH_FAULTS__MASK__AMD64_FAM19H_ZEN4_FP_DISPATCH_FAULTS__YMM_SPILL_FAULT = 0x800ull, // YMM spill faults
		FP_DISPATCH_FAULTS__MASK__AMD64_FAM19H_ZEN4_FP_DISPATCH_FAULTS__ANY = 0xf00ull, // Any FP dispatch faults
		BAD_STATUS_2 = 0x24, // TBD
		BAD_STATUS_2__MASK__AMD64_FAM19H_ZEN4_BAD_STATUS_2__STLI_OTHER = 0x200ull, // Store-to-load conflicts. A load was unable to complete due to a non-forwardable conflict with an older store
		RETIRED_LOCK_INSTRUCTIONS = 0x25, // Counts the number of retired locked instructions
		RETIRED_LOCK_INSTRUCTIONS__MASK__AMD64_FAM19H_ZEN4_RETIRED_LOCK_INSTRUCTIONS__BUS_LOCK = 0x100ull, // Number of bus locks
		RETIRED_CLFLUSH_INSTRUCTIONS = 0x26, // Counts the number of retired non-speculative clflush instructions
		RETIRED_CPUID_INSTRUCTIONS = 0x27, // Counts the number of retired cpuid instructions
		LS_DISPATCH = 0x29, // Counts the number of operations dispatched to the LS unit. Unit Masks ADDed
		LS_DISPATCH__MASK__AMD64_FAM19H_ZEN4_LS_DISPATCH__LD_ST_DISPATCH = 0x400ull, // Dispatched op that performs a load from and store to the same memory address
		LS_DISPATCH__MASK__AMD64_FAM19H_ZEN4_LS_DISPATCH__STORE_DISPATCH = 0x200ull, // Store ops dispatched
		LS_DISPATCH__MASK__AMD64_FAM19H_ZEN4_LS_DISPATCH__LD_DISPATCH = 0x100ull, // Load ops dispatched
		SMI_RECEIVED = 0x2b, // Counts the number system management interrupts (SMI) received
		INTERRUPT_TAKEN = 0x2c, // Counts the number of interrupts taken
		STORE_TO_LOAD_FORWARD = 0x35, // Number of STore to Load Forward hits
		STORE_COMMIT_CANCELS_2 = 0x37, // TBD
		STORE_COMMIT_CANCELS_2__MASK__AMD64_FAM19H_ZEN4_STORE_COMMIT_CANCELS_2__WCB_FULL = 0x100ull, // Non cacheable store and the non-cacheable commit buffer is full
		MAB_ALLOCATION_BY_TYPE = 0x41, // Counts when a LS pipe allocates a MAB entry
		MAB_ALLOCATION_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_MAB_ALLOCATION_BY_TYPE__LS = 0x3f00ull, // Load store allocations
		MAB_ALLOCATION_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_MAB_ALLOCATION_BY_TYPE__HW_PF = 0x4000ull, // Hardware prefetcher allocations
		MAB_ALLOCATION_BY_TYPE__MASK__AMD64_FAM19H_ZEN4_MAB_ALLOCATION_BY_TYPE__ALL = 0x7f00ull, // All allocations
		DEMAND_DATA_CACHE_FILLS_FROM_SYSTEM = 0x43, // Demand Data Cache fills by data source
		DEMAND_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__LCL_L2 = 0x100ull, // Fill from local L2 to the core
		DEMAND_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__LOCAL_CCX = 0x200ull, // Fill from L3 or different L2 in same CCX
		DEMAND_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__NEAR_CACHE_NEAR_FAR = 0x400ull, // Fill from cache of different CCX in same node
		DEMAND_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__DRAM_IO_NEAR = 0x800ull, // Fill from DRAM or IO connected to same node
		DEMAND_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__FAR_CACHE_NEAR_FAR = 0x1000ull, // Fill from CCX cache in different node
		DEMAND_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__DRAM_IO_FAR = 0x4000ull, // Fill from DRAM or IO connected from a different node (same socket or remote)
		DEMAND_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__ALT_MEM_NEAR_FAR = 0x8000ull, // Fill from Extension Memory
		ANY_DATA_CACHE_FILLS_FROM_SYSTEM = 0x44, // Any Data Cache fills by data source
		ANY_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__LCL_L2 = 0x100ull, // Fill from local L2 to the core
		ANY_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__LOCAL_CCX = 0x200ull, // Fill from L3 or different L2 in same CCX
		ANY_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__NEAR_CACHE_NEAR_FAR = 0x400ull, // Fill from cache of different CCX in same node
		ANY_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__DRAM_IO_NEAR = 0x800ull, // Fill from DRAM or IO connected to same node
		ANY_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__FAR_CACHE_NEAR_FAR = 0x1000ull, // Fill from CCX cache in different node
		ANY_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__DRAM_IO_FAR = 0x4000ull, // Fill from DRAM or IO connected from a different node (same socket or remote)
		ANY_DATA_CACHE_FILLS_FROM_SYSTEM__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__ALT_MEM_NEAR_FAR = 0x8000ull, // Fill from Extension Memory
		L1_DTLB_MISS = 0x45, // L1 Data TLB misses
		L1_DTLB_MISS__MASK__AMD64_FAM19H_ZEN4_L1_DTLB_MISS__TLB_RELOAD_1G_L2_MISS = 0x8000ull, // Data TLB reload to a 1GB page that missed in the L2 TLB
		L1_DTLB_MISS__MASK__AMD64_FAM19H_ZEN4_L1_DTLB_MISS__TLB_RELOAD_2M_L2_MISS = 0x4000ull, // Data TLB reload to a 2MB page that missed in the L2 TLB
		L1_DTLB_MISS__MASK__AMD64_FAM19H_ZEN4_L1_DTLB_MISS__TLB_RELOAD_COALESCED_PAGE_MISS = 0x2000ull, // Data TLB reload to a coalesced page that also missed in the L2 TLB
		L1_DTLB_MISS__MASK__AMD64_FAM19H_ZEN4_L1_DTLB_MISS__TLB_RELOAD_4K_L2_MISS = 0x1000ull, // Data TLB reload to a 4KB page that missed in the L2 TLB
		L1_DTLB_MISS__MASK__AMD64_FAM19H_ZEN4_L1_DTLB_MISS__TLB_RELOAD_1G_L2_HIT = 0x800ull, // Data TLB reload to a 1GB page that hit in the L2 TLB
		L1_DTLB_MISS__MASK__AMD64_FAM19H_ZEN4_L1_DTLB_MISS__TLB_RELOAD_2M_L2_HIT = 0x400ull, // Data TLB reload to a 2MB page that hit in the L2 TLB
		L1_DTLB_MISS__MASK__AMD64_FAM19H_ZEN4_L1_DTLB_MISS__TLB_RELOAD_COALESCED_PAGE_HIT = 0x200ull, // Data TLB reload to a coalesced page that hit in the L2 TLB
		L1_DTLB_MISS__MASK__AMD64_FAM19H_ZEN4_L1_DTLB_MISS__TLB_RELOAD_4K_L2_HIT = 0x100ull, // Data TLB reload to a 4KB page that hit in the L2 TLB
		MISALIGNED_LOADS = 0x47, // Misaligned loads retired
		MISALIGNED_LOADS__MASK__AMD64_FAM19H_ZEN4_MISALIGNED_LOADS__MA4K = 0x200ull, // The number of 4KB misaligned (page crossing) loads
		MISALIGNED_LOADS__MASK__AMD64_FAM19H_ZEN4_MISALIGNED_LOADS__MA64 = 0x100ull, // The number of 64B misaligned (cacheline crossing) loads
		PREFETCH_INSTRUCTIONS_DISPATCHED = 0x4b, // Software Prefetch Instructions Dispatched. This is a speculative event
		PREFETCH_INSTRUCTIONS_DISPATCHED__MASK__AMD64_FAM19H_ZEN4_PREFETCH_INSTRUCTIONS_DISPATCHED__PREFETCH_T0_T1_T2 = 0x100ull, // Number of prefetcht0
		PREFETCH_INSTRUCTIONS_DISPATCHED__MASK__AMD64_FAM19H_ZEN4_PREFETCH_INSTRUCTIONS_DISPATCHED__PREFETCHW = 0x200ull, // Number of prefetchtw instructions dispatched
		PREFETCH_INSTRUCTIONS_DISPATCHED__MASK__AMD64_FAM19H_ZEN4_PREFETCH_INSTRUCTIONS_DISPATCHED__PREFETCHNTA = 0x400ull, // Number of prefetchtnta instructions dispatched
		PREFETCH_INSTRUCTIONS_DISPATCHED__MASK__AMD64_FAM19H_ZEN4_PREFETCH_INSTRUCTIONS_DISPATCHED__ANY = 0x700ull, // Any prefetch
		INEFFECTIVE_SOFTWARE_PREFETCH = 0x52, // Number of software prefetches that did not fetch data outside of the processor core
		INEFFECTIVE_SOFTWARE_PREFETCH__MASK__AMD64_FAM19H_ZEN4_INEFFECTIVE_SOFTWARE_PREFETCH__MAB_MCH_CNT = 0x200ull, // Software prefetch instructions saw a match on an already allocated miss request buffer
		INEFFECTIVE_SOFTWARE_PREFETCH__MASK__AMD64_FAM19H_ZEN4_INEFFECTIVE_SOFTWARE_PREFETCH__DATA_PIPE_SW_PF_DC_HIT = 0x100ull, // Software Prefetch instruction saw a DC hit
		SOFTWARE_PREFETCH_DATA_CACHE_FILLS = 0x59, // Number of software prefetches fills by data source
		SOFTWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__LCL_L2 = 0x100ull, // Fill from local L2 to the core
		SOFTWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__LOCAL_CCX = 0x200ull, // Fill from L3 or different L2 in same CCX
		SOFTWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__NEAR_CACHE_NEAR_FAR = 0x400ull, // Fill from cache of different CCX in same node
		SOFTWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__DRAM_IO_NEAR = 0x800ull, // Fill from DRAM or IO connected to same node
		SOFTWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__FAR_CACHE_NEAR_FAR = 0x1000ull, // Fill from CCX cache in different node
		SOFTWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__DRAM_IO_FAR = 0x4000ull, // Fill from DRAM or IO connected from a different node (same socket or remote)
		SOFTWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__ALT_MEM_NEAR_FAR = 0x8000ull, // Fill from Extension Memory
		HARDWARE_PREFETCH_DATA_CACHE_FILLS = 0x5a, // Number of hardware prefetches fills by data source
		HARDWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__LCL_L2 = 0x100ull, // Fill from local L2 to the core
		HARDWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__LOCAL_CCX = 0x200ull, // Fill from L3 or different L2 in same CCX
		HARDWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__NEAR_CACHE_NEAR_FAR = 0x400ull, // Fill from cache of different CCX in same node
		HARDWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__DRAM_IO_NEAR = 0x800ull, // Fill from DRAM or IO connected to same node
		HARDWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__FAR_CACHE_NEAR_FAR = 0x1000ull, // Fill from CCX cache in different node
		HARDWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__DRAM_IO_FAR = 0x4000ull, // Fill from DRAM or IO connected from a different node (same socket or remote)
		HARDWARE_PREFETCH_DATA_CACHE_FILLS__MASK__AMD64_FAM19H_ZEN4_DEMAND_DATA_FILLS_FROM_SYSTEM__ALT_MEM_NEAR_FAR = 0x8000ull, // Fill from Extension Memory
		ALLOC_MAB_COUNT = 0x5f, // Counts the in-flight L1 data cache misses (allocated Miss Address Buffers) divided by 4 and rounded down each cycle unless used with the MergeEvent functionality. If the MergeEvent is used
		CYCLES_NOT_IN_HALT = 0x76, // Number of core cycles not in halted state
		TLB_FLUSHES = 0x78, // Number of TLB flushes
		TLB_FLUSHES__MASK__AMD64_FAM19H_ZEN4_TLB_FLUSHES__ALL = 0xff00ull, // Any TLB flush
		P0_FREQ_CYCLES_NOT_IN_HALT = 0x120, // Number of core cycle4s not in halted state by P-level
		INSTRUCTION_CACHE_REFILLS_FROM_L2 = 0x82, // Number of 64-byte instruction cachelines that was fulfilled by the L2 cache
		INSTRUCTION_CACHE_REFILLS_FROM_SYSTEM = 0x83, // Number of 64-byte instruction cachelines fulfilled from system memory or another cache
		L1_ITLB_MISS_L2_ITLB_HIT = 0x84, // Number of instruction fetches that miss in the L1 ITLB but hit in the L2 ITLB
		L1_ITLB_MISS_L2_ITLB_MISS = 0x85, // The number of valid fills into the ITLB originating from the LS Page-Table Walker. Tablewalk requests are issued for L1-ITLB and L2-ITLB misses
		L1_ITLB_MISS_L2_ITLB_MISS__MASK__AMD64_FAM19H_ZEN4_L1_ITLB_MISS_L2_ITLB_MISS__COALESCED4K = 0x800ull, // Number of instruction fetches to a >4K coalesced page
		L1_ITLB_MISS_L2_ITLB_MISS__MASK__AMD64_FAM19H_ZEN4_L1_ITLB_MISS_L2_ITLB_MISS__IF1G = 0x400ull, // Number of instruction fetches to a 1GB page
		L1_ITLB_MISS_L2_ITLB_MISS__MASK__AMD64_FAM19H_ZEN4_L1_ITLB_MISS_L2_ITLB_MISS__IF2M = 0x200ull, // Number of instruction fetches to a 2MB page
		L1_ITLB_MISS_L2_ITLB_MISS__MASK__AMD64_FAM19H_ZEN4_L1_ITLB_MISS_L2_ITLB_MISS__IF4K = 0x100ull, // Number of instruction fetches to a 4KB page
		L2_BTB_CORRECTION = 0x8b, // Number of L2 branch prediction overrides of existing prediction. This is a speculative event
		DYNAMIC_INDIRECT_PREDICTIONS = 0x8e, // Number of times a branch used the indirect predictor to make a prediction
		DECODER_OVERRIDE_BRANCH_PRED = 0x91, // Number of decoder overrides of existing branch prediction
		L1_ITLB_FETCH_HIT = 0x94, // Instruction fetches that hit in the L1 ITLB
		L1_ITLB_FETCH_HIT__MASK__AMD64_FAM19H_ZEN4_ITLB_FETCH_HIT__IF1G = 0x400ull, // L1 instruction fetch TLB hit a 1GB page size
		L1_ITLB_FETCH_HIT__MASK__AMD64_FAM19H_ZEN4_ITLB_FETCH_HIT__IF2M = 0x200ull, // L1 instruction fetch TLB hit a 2MB page size
		L1_ITLB_FETCH_HIT__MASK__AMD64_FAM19H_ZEN4_ITLB_FETCH_HIT__IF4K = 0x100ull, // L1 instruction fetch TLB hit a 4KB or 16KB page size
		RESYNCS = 0x96, // Number of HW resyncs (pipeline restarts) or NC redirects. NC redirects occur when front-end transitions to fetching from un-cacheable memory
		IC_TAG_HIT_MISS = 0x18e, // Counts various IC tag related hit and miss events
		IC_TAG_HIT_MISS__MASK__AMD64_FAM19H_ZEN4_IC_TAG_HIT_MISS__IC_HIT = 0x700ull, // Instruction cache hit
		IC_TAG_HIT_MISS__MASK__AMD64_FAM19H_ZEN4_IC_TAG_HIT_MISS__IC_MISS = 0x1800ull, // Instruction cache miss
		IC_TAG_HIT_MISS__MASK__AMD64_FAM19H_ZEN4_IC_TAG_HIT_MISS__ALL_IC_ACCESS = 0x1f00ull, // All instruction cache accesses
		OP_CACHE_HIT_MISS = 0x28f, // Counts op cache micro-tag hit/miss events
		OP_CACHE_HIT_MISS__MASK__AMD64_FAM19H_ZEN4_OP_CACHE_HIT_MISS__OC_HIT = 0x300ull, // Op cache hit
		OP_CACHE_HIT_MISS__MASK__AMD64_FAM19H_ZEN4_OP_CACHE_HIT_MISS__OC_MISS = 0x400ull, // Op cache miss
		OP_CACHE_HIT_MISS__MASK__AMD64_FAM19H_ZEN4_OP_CACHE_HIT_MISS__ALL_OC_ACCESS = 0x700ull, // All op cache accesses
		OPS_QUEUE_EMPTY = 0xa9, // Number of cycles where the uop queue is empty
		OPS_SOURCE_DISPATCHED_FROM_DECODER = 0xaa, // Number of ops dispatched from the decoder classified by op source
		OPS_SOURCE_DISPATCHED_FROM_DECODER__MASK__AMD64_FAM19H_ZEN4_OPS_SOURCE_DISPATCHED_FROM_DECODER__DECODER = 0x100ull, // Number of ops fetched from Instruction Cache and dispatched
		OPS_SOURCE_DISPATCHED_FROM_DECODER__MASK__AMD64_FAM19H_ZEN4_OPS_SOURCE_DISPATCHED_FROM_DECODER__OPCACHE = 0x200ull, // Number of ops fetched from Op Cache and dispatched
		OPS_SOURCE_DISPATCHED_FROM_DECODER__MASK__AMD64_FAM19H_ZEN4_OPS_SOURCE_DISPATCHED_FROM_DECODER__LOOP_BUFFER = 0x400ull, // Number of ops fetched from Loop buffer
		OPS_TYPE_DISPATCHED_FROM_DECODER = 0xab, // Number of ops dispatched from the decoder classified by op type
		OPS_TYPE_DISPATCHED_FROM_DECODER__MASK__AMD64_FAM19H_ZEN4_OPS_TYPE_DISPATCHED_FROM_DECODER__FP_DISPATCH = 0x400ull, // Any FP dispatch
		OPS_TYPE_DISPATCHED_FROM_DECODER__MASK__AMD64_FAM19H_ZEN4_OPS_TYPE_DISPATCHED_FROM_DECODER__INTEGER_DISPATCH = 0x800ull, // Any Integer dispatch
		DISPATCH_RESOURCE_STALL_CYCLES_1 = 0xae, // Number of cycles where a dispatch group is valid but does not get dispatched due to a Token Stall
		DISPATCH_RESOURCE_STALL_CYCLES_1__MASK__AMD64_FAM19H_ZEN4_DISPATCH_RESOURCE_STALL_CYCLES_1__INT_PHY_REG_FILE_RSRC_STALL = 0x100ull, // Number of cycles stalled due to integer physical register file resource stalls. Applies to all ops that have integer destination register
		DISPATCH_RESOURCE_STALL_CYCLES_1__MASK__AMD64_FAM19H_ZEN4_DISPATCH_RESOURCE_STALL_CYCLES_1__LOAD_QUEUE_RSRC_STALL = 0x200ull, // Number of cycles stalled due to load queue resource stalls
		DISPATCH_RESOURCE_STALL_CYCLES_1__MASK__AMD64_FAM19H_ZEN4_DISPATCH_RESOURCE_STALL_CYCLES_1__STORE_QUEUE_RSRC_STALL = 0x400ull, // Number of cycles stalled due to store queue resource stalls
		DISPATCH_RESOURCE_STALL_CYCLES_1__MASK__AMD64_FAM19H_ZEN4_DISPATCH_RESOURCE_STALL_CYCLES_1__TAKEN_BRANCH_BUFFER_RSRC_STALL = 0x1000ull, // Number of cycles stalled due to taken branch buffer resource stalls
		DISPATCH_RESOURCE_STALL_CYCLES_1__MASK__AMD64_FAM19H_ZEN4_DISPATCH_RESOURCE_STALL_CYCLES_1__FP_REG_FILE_RSRC_STALL = 0x2000ull, // Number of cycles stalled due to floating-point register file resource stalls. Applies to all FP ops that have a destination register
		DISPATCH_RESOURCE_STALL_CYCLES_1__MASK__AMD64_FAM19H_ZEN4_DISPATCH_RESOURCE_STALL_CYCLES_1__FP_SCHEDULER_RSRC_STALL = 0x4000ull, // Number of cycles stalled due to floating-point scheduler resource stalls
		DISPATCH_RESOURCE_STALL_CYCLES_1__MASK__AMD64_FAM19H_ZEN4_DISPATCH_RESOURCE_STALL_CYCLES_1__FP_FLUSH_RECOVERY_STALL = 0x8000ull, // Number of cycles stalled due to floating-point flush recovery
		DISPATCH_RESOURCE_STALL_CYCLES_2 = 0xaf, // Number of cycles where a dispatch group is valid but does not get dispatched due to a Token Stall
		DISPATCH_RESOURCE_STALL_CYCLES_2__MASK__AMD64_FAM19H_ZEN4_DISPATCH_RESOURCE_STALL_CYCLES_2__INT_SCHEDULER_0_TOKEN_STALL = 0x100ull, // Number of cycles stalled due to no tokens available for Integer Scheduler Queue 0
		DISPATCH_RESOURCE_STALL_CYCLES_2__MASK__AMD64_FAM19H_ZEN4_DISPATCH_RESOURCE_STALL_CYCLES_2__INT_SCHEDULER_1_TOKEN_STALL = 0x200ull, // Number of cycles stalled due to no tokens available for Integer Scheduler Queue 1
		DISPATCH_RESOURCE_STALL_CYCLES_2__MASK__AMD64_FAM19H_ZEN4_DISPATCH_RESOURCE_STALL_CYCLES_2__INT_SCHEDULER_2_TOKEN_STALL = 0x400ull, // Number of cycles stalled due to no tokens available for Integer Scheduler Queue 2
		DISPATCH_RESOURCE_STALL_CYCLES_2__MASK__AMD64_FAM19H_ZEN4_DISPATCH_RESOURCE_STALL_CYCLES_2__INT_SCHEDULER_3_TOKEN_STALL = 0x800ull, // Number of cycles stalled due to no tokens available for Integer Scheduler Queue 3
		DISPATCH_RESOURCE_STALL_CYCLES_2__MASK__AMD64_FAM19H_ZEN4_DISPATCH_RESOURCE_STALL_CYCLES_2__RETIRE_TOKEN_STALL = 0x2000ull, // Number of cycles stalled due to insufficient tokens available for Retire Queue
		DISPATCH_STALLS_1 = 0x1a0, // For each cycle
		DISPATCH_STALLS_1__MASK__AMD64_FAM19H_ZEN4_DISPATCH_STALLS_1__P0_FREQ_CYCLES = 0x100ull, // Counts at P0 frequency (same as MPERF) when CPU is not in halted state
		DISPATCH_STALLS_1__MASK__AMD64_FAM19H_ZEN4_DISPATCH_STALLS_1__BE_STALLS = 0x1e00ull, // Counts uops unable to dispatch due to back-end stalls
		DISPATCH_STALLS_2 = 0x1a2, // For each cycle
		DISPATCH_STALLS_2__MASK__AMD64_FAM19H_ZEN4_DISPATCH_STALLS_2__SMT_CONTENTION = 0x6000ull, // Counts dispatch slots left empty because of back-end stalls
		RETIRED_INSTRUCTIONS = 0xc0, // Number of instructions retired
		RETIRED_OPS = 0xc1, // Number of macro-ops retired
		RETIRED_BRANCH_INSTRUCTIONS = 0xc2, // Number of branch instructions retired. This includes all types of architectural control flow changes
		RETIRED_BRANCH_INSTRUCTIONS_MISPREDICTED = 0xc3, // Number of retired branch instructions
		RETIRED_TAKEN_BRANCH_INSTRUCTIONS = 0xc4, // Number of taken branches that were retired. This includes all types of architectural control flow changes
		RETIRED_TAKEN_BRANCH_INSTRUCTIONS_MISPREDICTED = 0xc5, // Number of retired taken branch instructions that were mispredicted
		RETIRED_FAR_CONTROL_TRANSFERS = 0xc6, // Number of far control transfers retired including far call/jump/return
		RETIRED_NEAR_RETURNS = 0xc8, // Number of near return instructions (RET or RET Iw) retired
		RETIRED_NEAR_RETURNS_MISPREDICTED = 0xc9, // Number of near returns retired that were not correctly predicted by the return address predictor. Each such mispredict incurs the same penalty as a mispredicted conditional branch instruction
		RETIRED_INDIRECT_BRANCH_INSTRUCTIONS_MISPREDICTED = 0xca, // Number of indirect branches retired there were not correctly predicted. Each such mispredict incurs the same penalty as a mispredicted condition branch instruction. Only EX mispredicts are counted
		RETIRED_MMX_FP_INSTRUCTIONS = 0xcb, // Number of MMX
		RETIRED_MMX_FP_INSTRUCTIONS__MASK__AMD64_FAM19H_ZEN4_RETIRED_MMX_FP_INSTRUCTIONS__SSE_INSTR = 0x400ull, // Number of SSE instructions (SSE
		RETIRED_MMX_FP_INSTRUCTIONS__MASK__AMD64_FAM19H_ZEN4_RETIRED_MMX_FP_INSTRUCTIONS__MMX_INSTR = 0x200ull, // Number of MMX instructions
		RETIRED_MMX_FP_INSTRUCTIONS__MASK__AMD64_FAM19H_ZEN4_RETIRED_MMX_FP_INSTRUCTIONS__X87_INSTR = 0x100ull, // Number of x87 instructions
		RETIRED_INDIRECT_BRANCH_INSTRUCTIONS = 0xcc, // Number of indirect branches retired
		RETIRED_CONDITIONAL_BRANCH_INSTRUCTIONS = 0xd1, // Number of retired conditional branch instructions
		DIV_CYCLES_BUSY_COUNT = 0xd3, // Number of cycles when the divider is busy
		DIV_OP_COUNT = 0xd4, // Number of divide ops
		CYCLES_NO_RETIRE = 0xd6, // Counts cycles when the hardware does not retire any ops for a given reason. Event can only track one reason at a time. If multiple reasons apply for a given cycle
		CYCLES_NO_RETIRE__MASK__AMD64_FAM19H_ZEN4_CYCLES_NO_RETIRE__EMPTY = 0x100ull, // Number of cycles when there were no valid ops in the retire queue. This may be caused by front-end bottlenecks or pipeline redirects
		CYCLES_NO_RETIRE__MASK__AMD64_FAM19H_ZEN4_CYCLES_NO_RETIRE__NOT_COMPLETE_LOAD_AND_ALU = 0x200ull, // Number of cycles when the oldest retire slot did not have its completion bits set. Only load and ALU completion considered
		CYCLES_NO_RETIRE__MASK__AMD64_FAM19H_ZEN4_CYCLES_NO_RETIRE__NOT_COMPLETE_MISSING_LOAD = 0xa200ull, // Number of cycles when the oldest retire slot did not have its completion bits set. Only missing Load completion considered
		CYCLES_NO_RETIRE__MASK__AMD64_FAM19H_ZEN4_CYCLES_NO_RETIRE__OTHER = 0x800ull, // Number of cycles where ops could have retired but were stopped from retirement for other reasons: retire breaks
		CYCLES_NO_RETIRE__MASK__AMD64_FAM19H_ZEN4_CYCLES_NO_RETIRE__THREAD_NOT_SELECTED = 0x1000ull, // Number of cycles where ops could have retired but did not because thread arbitration did not select the thread for retire
		RETIRED_UCODE_INSTRUCTIONS = 0x1c1, // Number of microcode instructions retired
		RETIRED_UCODE_OPS = 0x1c2, // Number of microcode ops retired
		RETIRED_BRANCH_MISPREDICTED_DIRECTION_MISMATCH = 0x1c7, // Number of retired conditional branch instructions that were not correctly predicted because of branch direction mismatch
		RETIRED_UNCONDITIONAL_INDIRECT_BRANCH_INSTRUCTIONS_MISPREDICTED = 0x1c8, // Number of retired unconditional indirect branch instructions that were mispredicted
		RETIRED_UNCONDITIONAL_BRANCH_INSTRUCTIONS = 0x1c9, // Number of retired unconditional branch instructions
		TAGGED_IBS_OPS = 0x1cf, // Counts Op IBS related events
		TAGGED_IBS_OPS__MASK__AMD64_FAM19H_ZEN4_TAGGED_IBS_OPS__IBS_COUNT_ROLLOVER = 0x400ull, // Number of times a op could not be tagged by IBS because of a previous tagged op that has not retired
		TAGGED_IBS_OPS__MASK__AMD64_FAM19H_ZEN4_TAGGED_IBS_OPS__IBS_TAGGED_OPS_RET = 0x200ull, // Number of ops tagged by IBS that retired
		TAGGED_IBS_OPS__MASK__AMD64_FAM19H_ZEN4_TAGGED_IBS_OPS__IBS_TAGGED_OPS = 0x100ull, // Number of ops tagged by IBS
		RETIRED_FUSED_INSTRUCTIONS = 0x1d0, // Counts retired fused instructions
		REQUESTS_TO_L2_GROUP1 = 0x60, // All L2 cache requests
		REQUESTS_TO_L2_GROUP1__MASK__AMD64_FAM19H_ZEN4_REQUESTS_TO_L2_GROUP1__RD_BLK_L = 0x8000ull, // Number of data cache reads (including software and hardware prefetches)
		REQUESTS_TO_L2_GROUP1__MASK__AMD64_FAM19H_ZEN4_REQUESTS_TO_L2_GROUP1__RD_BLK_X = 0x4000ull, // Number of data cache stores
		REQUESTS_TO_L2_GROUP1__MASK__AMD64_FAM19H_ZEN4_REQUESTS_TO_L2_GROUP1__LS_RD_BLK_C_S = 0x2000ull, // Number of data cache shared reads
		REQUESTS_TO_L2_GROUP1__MASK__AMD64_FAM19H_ZEN4_REQUESTS_TO_L2_GROUP1__CACHEABLE_IC_READ = 0x1000ull, // Number of instruction cache reads
		REQUESTS_TO_L2_GROUP1__MASK__AMD64_FAM19H_ZEN4_REQUESTS_TO_L2_GROUP1__CHANGE_TO_X = 0x800ull, // Number of data requests change to writable
		REQUESTS_TO_L2_GROUP1__MASK__AMD64_FAM19H_ZEN4_REQUESTS_TO_L2_GROUP1__PREFETCH_L2_CMD = 0x400ull, // TBD
		REQUESTS_TO_L2_GROUP1__MASK__AMD64_FAM19H_ZEN4_REQUESTS_TO_L2_GROUP1__L2_HW_PF = 0x200ull, // Number of prefetches accepted by L2 pipeline
		REQUESTS_TO_L2_GROUP1__MASK__AMD64_FAM19H_ZEN4_REQUESTS_TO_L2_GROUP1__MISC = 0x100ull, // Count various non-cacheable requests: non-cached data read
		CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS = 0x64, // L2 cache request outcomes. This event does not count accesses to the L2 cache by the L2 prefetcher
		CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__MASK__AMD64_FAM19H_ZEN4_CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__LS_RD_BLK_C_S = 0x8000ull, // Number of data cache shared read hitting in the L2
		CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__MASK__AMD64_FAM19H_ZEN4_CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__LS_RD_BLK_L_HIT_X = 0x4000ull, // Number of data cache reads hitting in the L2
		CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__MASK__AMD64_FAM19H_ZEN4_CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__LS_RD_BLK_L_HIT_S = 0x2000ull, // Number of data cache reads hitting a non-modifiable line in the L2
		CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__MASK__AMD64_FAM19H_ZEN4_CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__LS_RD_BLK_X = 0x1000ull, // Number of data cache store or state change requests hitting in the L2
		CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__MASK__AMD64_FAM19H_ZEN4_CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__LS_RD_BLK_C = 0x800ull, // Number of data cache requests missing in the L2 (all types)
		CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__MASK__AMD64_FAM19H_ZEN4_CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__IC_FILL_HIT_X = 0x400ull, // Number of instruction cache fill requests hitting a modifiable line in the L2
		CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__MASK__AMD64_FAM19H_ZEN4_CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__IC_FILL_HIT_S = 0x200ull, // Number of instruction cache fill requests hitting a non-modifiable line in the L2
		CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__MASK__AMD64_FAM19H_ZEN4_CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS__IC_FILL_MISS = 0x100ull, // Number of instruction cache fill requests missing the L2
		L2_PREFETCH_HIT_L2 = 0x70, // Number of L2 prefetches that hit in the L2
		L2_PREFETCH_HIT_L2__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_STREAM = 0x100ull, // Number of requests from the L2Stream prefetcher
		L2_PREFETCH_HIT_L2__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_NEXT_LINE = 0x200ull, // Number of requests from the L2 Next Line prefetcher
		L2_PREFETCH_HIT_L2__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_UP_DOWN = 0x400ull, // Number of requests from the L2 Up Down prefetcher
		L2_PREFETCH_HIT_L2__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_BURST = 0x800ull, // Number of requests from the L2 Burst  prefetcher
		L2_PREFETCH_HIT_L2__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_STRIDE = 0x1000ull, // Number of requests from the L2 Stride prefetcher
		L2_PREFETCH_HIT_L2__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L1_STREAM = 0x2000ull, // Number of requests from the L2 Stream prefetcher
		L2_PREFETCH_HIT_L2__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L1_STRIDE = 0x4000ull, // Number of requests from the L1 Stride prefetcher
		L2_PREFETCH_HIT_L2__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L1_REGION = 0x8000ull, // Number of requests from the L1 Region prefetcher
		L2_PREFETCH_HIT_L3 = 0x71, // Number of L2 prefetches accepted by the L2 pipeline which miss the L2 cache and hit the L3
		L2_PREFETCH_HIT_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_STREAM = 0x100ull, // Number of requests from the L2Stream prefetcher
		L2_PREFETCH_HIT_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_NEXT_LINE = 0x200ull, // Number of requests from the L2 Next Line prefetcher
		L2_PREFETCH_HIT_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_UP_DOWN = 0x400ull, // Number of requests from the L2 Up Down prefetcher
		L2_PREFETCH_HIT_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_BURST = 0x800ull, // Number of requests from the L2 Burst  prefetcher
		L2_PREFETCH_HIT_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_STRIDE = 0x1000ull, // Number of requests from the L2 Stride prefetcher
		L2_PREFETCH_HIT_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L1_STREAM = 0x2000ull, // Number of requests from the L2 Stream prefetcher
		L2_PREFETCH_HIT_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L1_STRIDE = 0x4000ull, // Number of requests from the L1 Stride prefetcher
		L2_PREFETCH_HIT_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L1_REGION = 0x8000ull, // Number of requests from the L1 Region prefetcher
		L2_PREFETCH_MISS_L3 = 0x72, // Number of L2 prefetches accepted by the L2 pipeline which miss the L2 and the L3 caches
		L2_PREFETCH_MISS_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_STREAM = 0x100ull, // Number of requests from the L2Stream prefetcher
		L2_PREFETCH_MISS_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_NEXT_LINE = 0x200ull, // Number of requests from the L2 Next Line prefetcher
		L2_PREFETCH_MISS_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_UP_DOWN = 0x400ull, // Number of requests from the L2 Up Down prefetcher
		L2_PREFETCH_MISS_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_BURST = 0x800ull, // Number of requests from the L2 Burst  prefetcher
		L2_PREFETCH_MISS_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L2_STRIDE = 0x1000ull, // Number of requests from the L2 Stride prefetcher
		L2_PREFETCH_MISS_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L1_STREAM = 0x2000ull, // Number of requests from the L2 Stream prefetcher
		L2_PREFETCH_MISS_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L1_STRIDE = 0x4000ull, // Number of requests from the L1 Stride prefetcher
		L2_PREFETCH_MISS_L3__MASK__AMD64_FAM19H_ZEN4_L2_PREFETCH_HIT_L2__L1_REGION = 0x8000ull, // Number of requests from the L1 Region prefetcher
		
	};
};

namespace fam19h_zen4 = optkit::amd64::fam19h_zen4;

