#pragma once
#include "utils/deployment/deployment_config.hh"
#if OPTKIT_ENV_LIB_NVML
#include <string>
#include <vector>
namespace optkit::metrics::performance::gpu::nvidia
{
        /**
         * @brief These are the core events to be monitored for metrics. It is expected to exists in every CPUs
         * for CPU specific events, check their respective CoreEvents.
         */
        enum class NativeEvents
        {
                BEGIN = 0,
                PCIE_TX_PER_SEC,
                PCIE_RX_PER_SEC,
                NVDEC_0_UTIL,
                NVDEC_1_UTIL,
                NVDEC_2_UTIL,
                NVDEC_3_UTIL,
                NVDEC_4_UTIL,
                NVDEC_5_UTIL,
                NVDEC_6_UTIL,
                NVDEC_7_UTIL,
                NVJPG_0_UTIL,
                NVJPG_1_UTIL,
                NVJPG_2_UTIL,
                NVJPG_3_UTIL,
                NVJPG_4_UTIL,
                NVJPG_5_UTIL,
                NVJPG_6_UTIL,
                NVJPG_7_UTIL,
                NVOFA_0_UTIL,
                NVLINK_TOTAL_RX_PER_SEC,
                NVLINK_TOTAL_TX_PER_SEC,
                NVLINK_L0_RX_PER_SEC,
                NVLINK_L0_TX_PER_SEC,
                NVLINK_L1_RX_PER_SEC,
                NVLINK_L1_TX_PER_SEC,
                NVLINK_L2_RX_PER_SEC,
                NVLINK_L2_TX_PER_SEC,
                NVLINK_L3_RX_PER_SEC,
                NVLINK_L3_TX_PER_SEC,
                NVLINK_L4_RX_PER_SEC,
                NVLINK_L4_TX_PER_SEC,
                NVLINK_L5_RX_PER_SEC,
                NVLINK_L5_TX_PER_SEC,
                NVLINK_L6_RX_PER_SEC,
                NVLINK_L6_TX_PER_SEC,
                NVLINK_L7_RX_PER_SEC,
                NVLINK_L7_TX_PER_SEC,
                NVLINK_L8_RX_PER_SEC,
                NVLINK_L8_TX_PER_SEC,
                NVLINK_L9_RX_PER_SEC,
                NVLINK_L9_TX_PER_SEC,
                NVLINK_L10_RX_PER_SEC,
                NVLINK_L10_TX_PER_SEC,
                NVLINK_L11_RX_PER_SEC,
                NVLINK_L11_TX_PER_SEC,
                NVLINK_L12_RX_PER_SEC,
                NVLINK_L12_TX_PER_SEC,
                NVLINK_L13_RX_PER_SEC,
                NVLINK_L13_TX_PER_SEC,
                NVLINK_L14_RX_PER_SEC,
                NVLINK_L14_TX_PER_SEC,
                NVLINK_L15_RX_PER_SEC,
                NVLINK_L15_TX_PER_SEC,
                NVLINK_L16_RX_PER_SEC,
                NVLINK_L16_TX_PER_SEC,
                NVLINK_L17_RX_PER_SEC,
                NVLINK_L17_TX_PER_SEC,
                END,
        };
        static const std::vector<std::string> &get_native_events()
        {
                static std::vector<std::string> native_events{
                    "PCIE_TX_PER_SEC",
                    "PCIE_RX_PER_SEC",
                    "NVDEC_0_UTIL",
                    "NVDEC_1_UTIL",
                    "NVDEC_2_UTIL",
                    "NVDEC_3_UTIL",
                    "NVDEC_4_UTIL",
                    "NVDEC_5_UTIL",
                    "NVDEC_6_UTIL",
                    "NVDEC_7_UTIL",
                    "NVJPG_0_UTIL",
                    "NVJPG_1_UTIL",
                    "NVJPG_2_UTIL",
                    "NVJPG_3_UTIL",
                    "NVJPG_4_UTIL",
                    "NVJPG_5_UTIL",
                    "NVJPG_6_UTIL",
                    "NVJPG_7_UTIL",
                    "NVOFA_0_UTIL",
                    "NVLINK_TOTAL_RX_PER_SEC",
                    "NVLINK_TOTAL_TX_PER_SEC",
                    "NVLINK_L0_RX_PER_SEC",
                    "NVLINK_L0_TX_PER_SEC",
                    "NVLINK_L1_RX_PER_SEC",
                    "NVLINK_L1_TX_PER_SEC",
                    "NVLINK_L2_RX_PER_SEC",
                    "NVLINK_L2_TX_PER_SEC",
                    "NVLINK_L3_RX_PER_SEC",
                    "NVLINK_L3_TX_PER_SEC",
                    "NVLINK_L4_RX_PER_SEC",
                    "NVLINK_L4_TX_PER_SEC",
                    "NVLINK_L5_RX_PER_SEC",
                    "NVLINK_L5_TX_PER_SEC",
                    "NVLINK_L6_RX_PER_SEC",
                    "NVLINK_L6_TX_PER_SEC",
                    "NVLINK_L7_RX_PER_SEC",
                    "NVLINK_L7_TX_PER_SEC",
                    "NVLINK_L8_RX_PER_SEC",
                    "NVLINK_L8_TX_PER_SEC",
                    "NVLINK_L9_RX_PER_SEC",
                    "NVLINK_L9_TX_PER_SEC",
                    "NVLINK_L10_RX_PER_SEC",
                    "NVLINK_L10_TX_PER_SEC",
                    "NVLINK_L11_RX_PER_SEC",
                    "NVLINK_L11_TX_PER_SEC",
                    "NVLINK_L12_RX_PER_SEC",
                    "NVLINK_L12_TX_PER_SEC",
                    "NVLINK_L13_RX_PER_SEC",
                    "NVLINK_L13_TX_PER_SEC",
                    "NVLINK_L14_RX_PER_SEC",
                    "NVLINK_L14_TX_PER_SEC",
                    "NVLINK_L15_RX_PER_SEC",
                    "NVLINK_L15_TX_PER_SEC",
                    "NVLINK_L16_RX_PER_SEC",
                    "NVLINK_L16_TX_PER_SEC",
                    "NVLINK_L17_RX_PER_SEC",
                    "NVLINK_L17_TX_PER_SEC",
                };
                return native_events;
        }
        std::string to_string(NativeEvents event);
        std::ostream &operator<<(std::ostream &os, NativeEvents event);

}
#endif // OPTKIT_ENV_LIB_NVML