#pragma once
#include <cstdint>
#define INTEL_X86_EDGE_BIT	18
#define INTEL_X86_ANY_BIT	21
#define INTEL_X86_INV_BIT	23
#define INTEL_X86_CMASK_BIT 24
#define INTEL_X86_MOD_EDGE	(1 << INTEL_X86_EDGE_BIT)
#define INTEL_X86_MOD_ANY	(1 << INTEL_X86_ANY_BIT)
#define INTEL_X86_MOD_INV	(1 << INTEL_X86_INV_BIT)
namespace optkit::intel::knl_unc_m2pcie{
	enum knl_unc_m2pcie : uint64_t {
		UNC_M2P_INGRESS_CYCLES_NE = 0x10, // Ingress Queue Cycles Not Empty. Counts the number of cycles when the M2PCIe Ingress is not empty
		UNC_M2P_INGRESS_CYCLES_NE__MASK__KNL_UNC_M2P_INGRESS_CYCLES_NE__CBO_IDI = 0x100ull, // CBO_IDI
		UNC_M2P_INGRESS_CYCLES_NE__MASK__KNL_UNC_M2P_INGRESS_CYCLES_NE__CBO_NCB = 0x200ull, // CBO_NCB
		UNC_M2P_INGRESS_CYCLES_NE__MASK__KNL_UNC_M2P_INGRESS_CYCLES_NE__CBO_NCS = 0x400ull, // CBO_NCS
		UNC_M2P_INGRESS_CYCLES_NE__MASK__KNL_UNC_M2P_INGRESS_CYCLES_NE__ALL = 0x800ull, // All
		UNC_M2P_EGRESS_CYCLES_NE = 0x23, // Egress (to CMS) Cycles Not Empty. Counts the number of cycles when the M2PCIe Egress is not empty
		UNC_M2P_EGRESS_CYCLES_NE__MASK__KNL_UNC_M2P_EGRESS_CYCLES__AD_0 = 0x100ull, // AD_0
		UNC_M2P_EGRESS_CYCLES_NE__MASK__KNL_UNC_M2P_EGRESS_CYCLES__AK_0 = 0x200ull, // AK_0
		UNC_M2P_EGRESS_CYCLES_NE__MASK__KNL_UNC_M2P_EGRESS_CYCLES__BL_0 = 0x400ull, // BL_0
		UNC_M2P_EGRESS_CYCLES_NE__MASK__KNL_UNC_M2P_EGRESS_CYCLES__AD_1 = 0x800ull, // AD_1
		UNC_M2P_EGRESS_CYCLES_NE__MASK__KNL_UNC_M2P_EGRESS_CYCLES__AK_1 = 0x1000ull, // AK_1
		UNC_M2P_EGRESS_CYCLES_NE__MASK__KNL_UNC_M2P_EGRESS_CYCLES__BL_1 = 0x2000ull, // BL_1
		UNC_M2P_EGRESS_INSERTS = 0x24, // Egress (to CMS) Ingress. Counts the number of number of messages inserted into the  the M2PCIe Egress queue
		UNC_M2P_EGRESS_INSERTS__MASK__KNL_UNC_M2P_EGRESS_INSERTS__AD_0 = 0x100ull, // AD_0
		UNC_M2P_EGRESS_INSERTS__MASK__KNL_UNC_M2P_EGRESS_INSERTS__AK_0 = 0x200ull, // AK_0
		UNC_M2P_EGRESS_INSERTS__MASK__KNL_UNC_M2P_EGRESS_INSERTS__BL_0 = 0x400ull, // BL_0
		UNC_M2P_EGRESS_INSERTS__MASK__KNL_UNC_M2P_EGRESS_INSERTS__AK_CRD_0 = 0x800ull, // AK_CRD_0
		UNC_M2P_EGRESS_INSERTS__MASK__KNL_UNC_M2P_EGRESS_INSERTS__AD_1 = 0x1000ull, // AD_1
		UNC_M2P_EGRESS_INSERTS__MASK__KNL_UNC_M2P_EGRESS_INSERTS__AK_1 = 0x2000ull, // AK_1
		UNC_M2P_EGRESS_INSERTS__MASK__KNL_UNC_M2P_EGRESS_INSERTS__BL_1 = 0x4000ull, // BL_1
		UNC_M2P_EGRESS_INSERTS__MASK__KNL_UNC_M2P_EGRESS_INSERTS__AK_CRD_1 = 0x8000ull, // AK_CRD_1
		UNC_M2P_EGRESS_CYCLES_FULL = 0x25, // Egress (to CMS) Cycles Full. Counts the number of cycles when the M2PCIe Egress is full
		UNC_M2P_EGRESS_CYCLES_FULL__MASK__KNL_UNC_M2P_EGRESS_CYCLES__AD_0 = 0x100ull, // AD_0
		UNC_M2P_EGRESS_CYCLES_FULL__MASK__KNL_UNC_M2P_EGRESS_CYCLES__AK_0 = 0x200ull, // AK_0
		UNC_M2P_EGRESS_CYCLES_FULL__MASK__KNL_UNC_M2P_EGRESS_CYCLES__BL_0 = 0x400ull, // BL_0
		UNC_M2P_EGRESS_CYCLES_FULL__MASK__KNL_UNC_M2P_EGRESS_CYCLES__AD_1 = 0x800ull, // AD_1
		UNC_M2P_EGRESS_CYCLES_FULL__MASK__KNL_UNC_M2P_EGRESS_CYCLES__AK_1 = 0x1000ull, // AK_1
		UNC_M2P_EGRESS_CYCLES_FULL__MASK__KNL_UNC_M2P_EGRESS_CYCLES__BL_1 = 0x2000ull, // BL_1
		
	};
};

namespace knl_unc_m2pcie = optkit::intel::knl_unc_m2pcie;

#undef INTEL_X86_EDGE_BIT
#undef INTEL_X86_ANY_BIT
#undef INTEL_X86_INV_BIT
#undef INTEL_X86_CMASK_BIT
#undef INTEL_X86_MOD_EDGE
#undef INTEL_X86_MOD_ANY
#undef INTEL_X86_MOD_INV
