#pragma once

/**
 * @brief LOGGING
 *
 */

#ifndef CONF_LOG_PRINT_GUID_LENGTH
#define CONF_LOG_PRINT_GUID_LENGTH 5
#endif

#ifndef CONF_LOG_DISABLE_DEBUG
#define CONF_LOG_DISABLE_DEBUG 1
#endif

#ifndef CONF_LOG_DISABLE_TRACE
#define CONF_LOG_DISABLE_TRACE 1
#endif

#ifndef CONF_LOG_DISABLE_INFO
#define CONF_LOG_DISABLE_INFO  0
#endif

#ifndef CONF_LOG_DISABLE_WARN
#define CONF_LOG_DISABLE_WARN  0
#endif

#ifndef CONF_LOG_DISABLE_ERROR
#define CONF_LOG_DISABLE_ERROR 0
#endif
