#pragma once

#undef OPTKIT_GPU_ENERGY_SAMPLING
#undef OPTKIT_GPU_ENERGY_SAMPLING_WITH_METRICS

#define OPTKIT_GPU_ENERGY_SAMPLING(block_name)
#define OPTKIT_GPU_ENERGY_SAMPLING_WITH_METRICS(block_name, metric_builder, ...)